using CreatureGen.CharacterClasses;
using CreatureGen.Domain.Tables;
using CreatureGen.Creatures;
using NUnit.Framework;
using System.Linq;

namespace CreatureGen.Tests.Integration.Tables.CharacterClasses
{
    [TestFixture]
    public class SpecialistFieldsTests : CollectionTests
    {
        protected override string tableName
        {
            get { return TableNameConstants.Set.Collection.SpecialistFields; }
        }

        [Test]
        public override void CollectionNames()
        {
            var baseRaceGroups = CollectionsMapper.Map(TableNameConstants.Set.Collection.BaseRaceGroups);
            var metaraceGroups = CollectionsMapper.Map(TableNameConstants.Set.Collection.MetaraceGroups);
            var classGroups = CollectionsMapper.Map(TableNameConstants.Set.Collection.ClassNameGroups);
            var names = baseRaceGroups[GroupConstants.All].Union(metaraceGroups[GroupConstants.All]).Union(classGroups[GroupConstants.All]);

            AssertCollectionNames(names);
        }

        [TestCase(CharacterClassConstants.Adept)]
        [TestCase(CharacterClassConstants.Aristocrat)]
        [TestCase(CharacterClassConstants.Barbarian)]
        [TestCase(CharacterClassConstants.Bard)]
        [TestCase(CharacterClassConstants.Cleric,
            CharacterClassConstants.Domains.Air,
            CharacterClassConstants.Domains.Animal,
            CharacterClassConstants.Domains.Chaos,
            CharacterClassConstants.Domains.Death,
            CharacterClassConstants.Domains.Destruction,
            CharacterClassConstants.Domains.Earth,
            CharacterClassConstants.Domains.Evil,
            CharacterClassConstants.Domains.Fire,
            CharacterClassConstants.Domains.Good,
            CharacterClassConstants.Domains.Healing,
            CharacterClassConstants.Domains.Knowledge,
            CharacterClassConstants.Domains.Law,
            CharacterClassConstants.Domains.Luck,
            CharacterClassConstants.Domains.Magic,
            CharacterClassConstants.Domains.Plant,
            CharacterClassConstants.Domains.Protection,
            CharacterClassConstants.Domains.Strength,
            CharacterClassConstants.Domains.Sun,
            CharacterClassConstants.Domains.Travel,
            CharacterClassConstants.Domains.Trickery,
            CharacterClassConstants.Domains.War,
            CharacterClassConstants.Domains.Water)]
        [TestCase(CharacterClassConstants.Commoner)]
        [TestCase(CharacterClassConstants.Druid)]
        [TestCase(CharacterClassConstants.Expert)]
        [TestCase(CharacterClassConstants.Fighter)]
        [TestCase(CharacterClassConstants.Monk)]
        [TestCase(CharacterClassConstants.Paladin)]
        [TestCase(CharacterClassConstants.Ranger)]
        [TestCase(CharacterClassConstants.Rogue)]
        [TestCase(CharacterClassConstants.Sorcerer)]
        [TestCase(CharacterClassConstants.Warrior)]
        [TestCase(CharacterClassConstants.Wizard,
            CharacterClassConstants.Schools.Abjuration,
            CharacterClassConstants.Schools.Conjuration,
            CharacterClassConstants.Schools.Divination,
            CharacterClassConstants.Schools.Enchantment,
            CharacterClassConstants.Schools.Evocation,
            CharacterClassConstants.Schools.Illusion,
            CharacterClassConstants.Schools.Necromancy,
            CharacterClassConstants.Schools.Transmutation)]
        [TestCase(SizeConstants.BaseRaces.CloudGiant,
            CharacterClassConstants.Domains.Death,
            CharacterClassConstants.Domains.Evil,
            CharacterClassConstants.Domains.Good,
            CharacterClassConstants.Domains.Strength,
            CharacterClassConstants.Domains.Sun,
            CharacterClassConstants.Domains.Trickery,
            CharacterClassConstants.Schools.Abjuration,
            CharacterClassConstants.Schools.Conjuration,
            CharacterClassConstants.Schools.Divination,
            CharacterClassConstants.Schools.Enchantment,
            CharacterClassConstants.Schools.Evocation,
            CharacterClassConstants.Schools.Illusion,
            CharacterClassConstants.Schools.Necromancy,
            CharacterClassConstants.Schools.Transmutation)]
        [TestCase(SizeConstants.BaseRaces.FireGiant,
            CharacterClassConstants.Domains.Evil,
            CharacterClassConstants.Domains.Law,
            CharacterClassConstants.Domains.Trickery,
            CharacterClassConstants.Domains.War,
            CharacterClassConstants.Schools.Abjuration,
            CharacterClassConstants.Schools.Conjuration,
            CharacterClassConstants.Schools.Divination,
            CharacterClassConstants.Schools.Enchantment,
            CharacterClassConstants.Schools.Evocation,
            CharacterClassConstants.Schools.Illusion,
            CharacterClassConstants.Schools.Necromancy,
            CharacterClassConstants.Schools.Transmutation)]
        [TestCase(SizeConstants.BaseRaces.FrostGiant,
            CharacterClassConstants.Domains.Chaos,
            CharacterClassConstants.Domains.Destruction,
            CharacterClassConstants.Domains.Evil,
            CharacterClassConstants.Domains.War,
            CharacterClassConstants.Schools.Abjuration,
            CharacterClassConstants.Schools.Conjuration,
            CharacterClassConstants.Schools.Divination,
            CharacterClassConstants.Schools.Enchantment,
            CharacterClassConstants.Schools.Evocation,
            CharacterClassConstants.Schools.Illusion,
            CharacterClassConstants.Schools.Necromancy,
            CharacterClassConstants.Schools.Transmutation)]
        [TestCase(SizeConstants.BaseRaces.Githyanki,
            CharacterClassConstants.Schools.Abjuration,
            CharacterClassConstants.Schools.Conjuration,
            CharacterClassConstants.Schools.Divination,
            CharacterClassConstants.Schools.Enchantment,
            CharacterClassConstants.Schools.Evocation,
            CharacterClassConstants.Schools.Illusion,
            CharacterClassConstants.Schools.Necromancy,
            CharacterClassConstants.Schools.Transmutation)]
        [TestCase(SizeConstants.BaseRaces.KuoToa,
            CharacterClassConstants.Domains.Destruction,
            CharacterClassConstants.Domains.Evil,
            CharacterClassConstants.Domains.Water,
            CharacterClassConstants.Schools.Abjuration,
            CharacterClassConstants.Schools.Conjuration,
            CharacterClassConstants.Schools.Divination,
            CharacterClassConstants.Schools.Enchantment,
            CharacterClassConstants.Schools.Evocation,
            CharacterClassConstants.Schools.Illusion,
            CharacterClassConstants.Schools.Necromancy,
            CharacterClassConstants.Schools.Transmutation)]
        [TestCase(SizeConstants.BaseRaces.Orc,
            CharacterClassConstants.Domains.Air,
            CharacterClassConstants.Domains.Animal,
            CharacterClassConstants.Domains.Chaos,
            CharacterClassConstants.Domains.Death,
            CharacterClassConstants.Domains.Destruction,
            CharacterClassConstants.Domains.Earth,
            CharacterClassConstants.Domains.Evil,
            CharacterClassConstants.Domains.Fire,
            CharacterClassConstants.Domains.Good,
            CharacterClassConstants.Domains.Healing,
            CharacterClassConstants.Domains.Knowledge,
            CharacterClassConstants.Domains.Law,
            CharacterClassConstants.Domains.Luck,
            CharacterClassConstants.Domains.Magic,
            CharacterClassConstants.Domains.Plant,
            CharacterClassConstants.Domains.Protection,
            CharacterClassConstants.Domains.Strength,
            CharacterClassConstants.Domains.Travel,
            CharacterClassConstants.Domains.Trickery,
            CharacterClassConstants.Domains.War,
            CharacterClassConstants.Domains.Water,
            CharacterClassConstants.Schools.Abjuration,
            CharacterClassConstants.Schools.Conjuration,
            CharacterClassConstants.Schools.Divination,
            CharacterClassConstants.Schools.Enchantment,
            CharacterClassConstants.Schools.Evocation,
            CharacterClassConstants.Schools.Illusion,
            CharacterClassConstants.Schools.Necromancy,
            CharacterClassConstants.Schools.Transmutation)]
        [TestCase(SizeConstants.BaseRaces.StormGiant,
            CharacterClassConstants.Domains.Chaos,
            CharacterClassConstants.Domains.Good,
            CharacterClassConstants.Domains.Protection,
            CharacterClassConstants.Domains.War,
            CharacterClassConstants.Schools.Abjuration,
            CharacterClassConstants.Schools.Conjuration,
            CharacterClassConstants.Schools.Divination,
            CharacterClassConstants.Schools.Enchantment,
            CharacterClassConstants.Schools.Evocation,
            CharacterClassConstants.Schools.Illusion,
            CharacterClassConstants.Schools.Necromancy,
            CharacterClassConstants.Schools.Transmutation)]
        [TestCase(SizeConstants.Metaraces.Vampire,
            CharacterClassConstants.Domains.Chaos,
            CharacterClassConstants.Domains.Destruction,
            CharacterClassConstants.Domains.Evil,
            CharacterClassConstants.Domains.Trickery,
            CharacterClassConstants.Schools.Abjuration,
            CharacterClassConstants.Schools.Conjuration,
            CharacterClassConstants.Schools.Divination,
            CharacterClassConstants.Schools.Enchantment,
            CharacterClassConstants.Schools.Evocation,
            CharacterClassConstants.Schools.Illusion,
            CharacterClassConstants.Schools.Necromancy,
            CharacterClassConstants.Schools.Transmutation)]
        public void SpecialistFields(string name, params string[] fields)
        {
            base.DistinctCollection(name, fields);
        }

        [TestCase(SizeConstants.BaseRaces.Aasimar)]
        [TestCase(SizeConstants.BaseRaces.AquaticElf)]
        [TestCase(SizeConstants.BaseRaces.Azer)]
        [TestCase(SizeConstants.BaseRaces.BlueSlaad)]
        [TestCase(SizeConstants.BaseRaces.Bugbear)]
        [TestCase(SizeConstants.BaseRaces.Centaur)]
        [TestCase(SizeConstants.BaseRaces.DeathSlaad)]
        [TestCase(SizeConstants.BaseRaces.DeepDwarf)]
        [TestCase(SizeConstants.BaseRaces.DeepHalfling)]
        [TestCase(SizeConstants.BaseRaces.Derro)]
        [TestCase(SizeConstants.BaseRaces.Doppelganger)]
        [TestCase(SizeConstants.BaseRaces.Drow)]
        [TestCase(SizeConstants.BaseRaces.DuergarDwarf)]
        [TestCase(SizeConstants.BaseRaces.ForestGnome)]
        [TestCase(SizeConstants.BaseRaces.Gargoyle)]
        [TestCase(SizeConstants.BaseRaces.Githzerai)]
        [TestCase(SizeConstants.BaseRaces.Gnoll)]
        [TestCase(SizeConstants.BaseRaces.Goblin)]
        [TestCase(SizeConstants.BaseRaces.GrayElf)]
        [TestCase(SizeConstants.BaseRaces.GraySlaad)]
        [TestCase(SizeConstants.BaseRaces.GreenSlaad)]
        [TestCase(SizeConstants.BaseRaces.Grimlock)]
        [TestCase(SizeConstants.BaseRaces.HalfElf)]
        [TestCase(SizeConstants.BaseRaces.HalfOrc)]
        [TestCase(SizeConstants.BaseRaces.Harpy)]
        [TestCase(SizeConstants.BaseRaces.HighElf)]
        [TestCase(SizeConstants.BaseRaces.HillDwarf)]
        [TestCase(SizeConstants.BaseRaces.HillGiant)]
        [TestCase(SizeConstants.BaseRaces.Hobgoblin)]
        [TestCase(SizeConstants.BaseRaces.HoundArchon)]
        [TestCase(SizeConstants.BaseRaces.Human)]
        [TestCase(SizeConstants.BaseRaces.Janni)]
        [TestCase(SizeConstants.BaseRaces.Kapoacinth)]
        [TestCase(SizeConstants.BaseRaces.Kobold)]
        [TestCase(SizeConstants.BaseRaces.LightfootHalfling)]
        [TestCase(SizeConstants.BaseRaces.Lizardfolk)]
        [TestCase(SizeConstants.BaseRaces.Locathah)]
        [TestCase(SizeConstants.BaseRaces.Merfolk)]
        [TestCase(SizeConstants.BaseRaces.Merrow)]
        [TestCase(SizeConstants.BaseRaces.MindFlayer)]
        [TestCase(SizeConstants.BaseRaces.Minotaur)]
        [TestCase(SizeConstants.BaseRaces.MountainDwarf)]
        [TestCase(SizeConstants.BaseRaces.Ogre)]
        [TestCase(SizeConstants.BaseRaces.OgreMage)]
        [TestCase(SizeConstants.BaseRaces.Pixie)]
        [TestCase(SizeConstants.BaseRaces.Rakshasa)]
        [TestCase(SizeConstants.BaseRaces.RedSlaad)]
        [TestCase(SizeConstants.BaseRaces.RockGnome)]
        [TestCase(SizeConstants.BaseRaces.Sahuagin)]
        [TestCase(SizeConstants.BaseRaces.Satyr)]
        [TestCase(SizeConstants.BaseRaces.Scorpionfolk)]
        [TestCase(SizeConstants.BaseRaces.Scrag)]
        [TestCase(SizeConstants.BaseRaces.StoneGiant)]
        [TestCase(SizeConstants.BaseRaces.Svirfneblin)]
        [TestCase(SizeConstants.BaseRaces.TallfellowHalfling)]
        [TestCase(SizeConstants.BaseRaces.Tiefling)]
        [TestCase(SizeConstants.BaseRaces.Troglodyte)]
        [TestCase(SizeConstants.BaseRaces.Troll)]
        [TestCase(SizeConstants.BaseRaces.WildElf)]
        [TestCase(SizeConstants.BaseRaces.WoodElf)]
        [TestCase(SizeConstants.BaseRaces.YuanTiAbomination)]
        [TestCase(SizeConstants.BaseRaces.YuanTiHalfblood)]
        [TestCase(SizeConstants.BaseRaces.YuanTiPureblood)]
        [TestCase(SizeConstants.Metaraces.Ghost)]
        [TestCase(SizeConstants.Metaraces.HalfCelestial)]
        [TestCase(SizeConstants.Metaraces.HalfDragon)]
        [TestCase(SizeConstants.Metaraces.HalfFiend)]
        [TestCase(SizeConstants.Metaraces.Lich)]
        [TestCase(SizeConstants.Metaraces.Mummy)]
        [TestCase(SizeConstants.Metaraces.None)]
        [TestCase(SizeConstants.Metaraces.Werebear)]
        [TestCase(SizeConstants.Metaraces.Wereboar)]
        [TestCase(SizeConstants.Metaraces.Wererat)]
        [TestCase(SizeConstants.Metaraces.Weretiger)]
        [TestCase(SizeConstants.Metaraces.Werewolf)]
        public void RaceHasAllSpecialistFields(string race)
        {
            var fields = new[]
            {
                CharacterClassConstants.Domains.Air,
                CharacterClassConstants.Domains.Animal,
                CharacterClassConstants.Domains.Chaos,
                CharacterClassConstants.Domains.Death,
                CharacterClassConstants.Domains.Destruction,
                CharacterClassConstants.Domains.Earth,
                CharacterClassConstants.Domains.Evil,
                CharacterClassConstants.Domains.Fire,
                CharacterClassConstants.Domains.Good,
                CharacterClassConstants.Domains.Healing,
                CharacterClassConstants.Domains.Knowledge,
                CharacterClassConstants.Domains.Law,
                CharacterClassConstants.Domains.Luck,
                CharacterClassConstants.Domains.Magic,
                CharacterClassConstants.Domains.Plant,
                CharacterClassConstants.Domains.Protection,
                CharacterClassConstants.Domains.Strength,
                CharacterClassConstants.Domains.Sun,
                CharacterClassConstants.Domains.Travel,
                CharacterClassConstants.Domains.Trickery,
                CharacterClassConstants.Domains.War,
                CharacterClassConstants.Domains.Water,
                CharacterClassConstants.Schools.Abjuration,
                CharacterClassConstants.Schools.Conjuration,
                CharacterClassConstants.Schools.Divination,
                CharacterClassConstants.Schools.Enchantment,
                CharacterClassConstants.Schools.Evocation,
                CharacterClassConstants.Schools.Illusion,
                CharacterClassConstants.Schools.Necromancy,
                CharacterClassConstants.Schools.Transmutation,
            };

            DistinctCollection(race, fields);
        }
    }
}