using CreatureGen.Creatures;
using NUnit.Framework;

namespace CreatureGen.Tests.Unit.Generators.Creatures
{
    [TestFixture]
    public class CreatureConstantsTests
    {
        [TestCase(CreatureConstants.Aasimar, "Aasimar")]
        [TestCase(CreatureConstants.Aboleth, "Aboleth")]
        [TestCase(CreatureConstants.Achaierai, "Achaierai")]
        [TestCase(CreatureConstants.Allip, "Allip")]
        [TestCase(CreatureConstants.Androsphinx, "Androsphinx")]
        [TestCase(CreatureConstants.Angel, "Angel")]
        [TestCase(CreatureConstants.AnimatedObject, "Animated object")]
        [TestCase(CreatureConstants.Ankheg, "Ankheg")]
        [TestCase(CreatureConstants.Annis, "Annis")]
        [TestCase(CreatureConstants.Ant_Giant, "Giant ant")]
        [TestCase(CreatureConstants.Ape, "Ape")]
        [TestCase(CreatureConstants.Ape_Dire, "Dire ape")]
        [TestCase(CreatureConstants.Aranea, "Aranea")]
        [TestCase(CreatureConstants.Archon, "Archon")]
        [TestCase(CreatureConstants.Arrowhawk, "Arrowhawk")]
        [TestCase(CreatureConstants.AssassinVine, "Assassin vine")]
        [TestCase(CreatureConstants.AstralDeva, "Astral deva")]
        [TestCase(CreatureConstants.Athach, "Athach")]
        [TestCase(CreatureConstants.Avoral, "Avoral")]
        [TestCase(CreatureConstants.Azer, "Azer")]
        [TestCase(CreatureConstants.Babau, "Babau")]
        [TestCase(CreatureConstants.Baboon, "Baboon")]
        [TestCase(CreatureConstants.Badger, "Badger")]
        [TestCase(CreatureConstants.Badger_Dire, "Dire badger")]
        [TestCase(CreatureConstants.Balor, "Balor")]
        [TestCase(CreatureConstants.BarbedDevil, "Barbed Devil")]
        [TestCase(CreatureConstants.BeardedDevil, "Bearded Devil")]
        [TestCase(CreatureConstants.Barghest, "Barghest")]
        [TestCase(CreatureConstants.Basilisk, "Basilisk")]
        [TestCase(CreatureConstants.Bat, "Bat")]
        [TestCase(CreatureConstants.Bat_Dire, "Dire bat")]
        [TestCase(CreatureConstants.Bat_Swarm, "Bat swarm")]
        [TestCase(CreatureConstants.Bear, "Bear")]
        [TestCase(CreatureConstants.Bear_Black, "Black bear")]
        [TestCase(CreatureConstants.Bear_Brown, "Brown bear")]
        [TestCase(CreatureConstants.Bear_Dire, "Dire bear")]
        [TestCase(CreatureConstants.Bear_Polar, "Polar bear")]
        [TestCase(CreatureConstants.Bebilith, "Bebilith")]
        [TestCase(CreatureConstants.Bee_Giant, "Giant bee")]
        [TestCase(CreatureConstants.Behir, "Behir")]
        [TestCase(CreatureConstants.Beholder, "Beholder")]
        [TestCase(CreatureConstants.Belker, "Belker")]
        [TestCase(CreatureConstants.Bison, "Bison")]
        [TestCase(CreatureConstants.BlackPudding, "Black pudding")]
        [TestCase(CreatureConstants.BlinkDog, "Blink dog")]
        [TestCase(CreatureConstants.Boar, "Boar")]
        [TestCase(CreatureConstants.Boar_Dire, "Dire boar")]
        [TestCase(CreatureConstants.Bodak, "Bodak")]
        [TestCase(CreatureConstants.BombardierBeetle_Giant, "Giant bombardier beetle")]
        [TestCase(CreatureConstants.Bralani, "Bralani")]
        [TestCase(CreatureConstants.Bugbear, "Bugbear")]
        [TestCase(CreatureConstants.Bulette, "Bulette")]
        [TestCase(CreatureConstants.Camel, "Camel")]
        [TestCase(CreatureConstants.CarrionCrawler, "Carrion crawler")]
        [TestCase(CreatureConstants.Cat, "Cat")]
        [TestCase(CreatureConstants.CelestialCreature, "Celestial creature")]
        [TestCase(CreatureConstants.Centaur, "Centaur")]
        [TestCase(CreatureConstants.Centipede_Monstrous, "Monstrous centipede")]
        [TestCase(CreatureConstants.Centipede_Swarm, "Centipede swarm")]
        [TestCase(CreatureConstants.ChainDevil, "Chain Devil")]
        [TestCase(CreatureConstants.ChaosBeast, "Chaos beast")]
        [TestCase(CreatureConstants.Cheetah, "Cheetah")]
        [TestCase(CreatureConstants.Chimera, "Chimera")]
        [TestCase(CreatureConstants.Choker, "Choker")]
        [TestCase(CreatureConstants.Chuul, "Chuul")]
        [TestCase(CreatureConstants.Cloaker, "Cloaker")]
        [TestCase(CreatureConstants.Cockatrice, "Cockatrice")]
        [TestCase(CreatureConstants.Couatl, "Couatl")]
        [TestCase(CreatureConstants.Criosphinx, "Criosphinx")]
        [TestCase(CreatureConstants.Crocodile, "Crocodile")]
        [TestCase(CreatureConstants.Crocodile_Giant, "Giant crocodile")]
        [TestCase(CreatureConstants.Cryohydra, "Cryohydra")]
        [TestCase(CreatureConstants.Darkmantle, "Darkmantle")]
        [TestCase(CreatureConstants.Deinonychus, "Deinonychus")]
        [TestCase(CreatureConstants.Derro, "Derro")]
        [TestCase(CreatureConstants.Destrachan, "Destrachan")]
        [TestCase(CreatureConstants.Devourer, "Devourer")]
        [TestCase(CreatureConstants.Delver, "Delver")]
        [TestCase(CreatureConstants.Demon, "Demon")]
        [TestCase(CreatureConstants.Devil, "Devil")]
        [TestCase(CreatureConstants.Digester, "Digester")]
        [TestCase(CreatureConstants.Dinosaur, "Dinosaur")]
        [TestCase(CreatureConstants.DisplacerBeast, "Displacer beast")]
        [TestCase(CreatureConstants.Djinni, "Djinni")]
        [TestCase(CreatureConstants.Dog, "Dog")]
        [TestCase(CreatureConstants.Donkey, "Donkey")]
        [TestCase(CreatureConstants.Doppelganger, "Doppelganger")]
        [TestCase(CreatureConstants.Dragon_Black, "Black dragon")]
        [TestCase(CreatureConstants.Dragon_Blue, "Blue dragon")]
        [TestCase(CreatureConstants.Dragon_Brass, "Brass dragon")]
        [TestCase(CreatureConstants.Dragon_Bronze, "Bronze dragon")]
        [TestCase(CreatureConstants.Dragon_Copper, "Copper dragon")]
        [TestCase(CreatureConstants.Dragon_Gold, "Gold dragon")]
        [TestCase(CreatureConstants.Dragon_Green, "Green dragon")]
        [TestCase(CreatureConstants.Dragon_Red, "Red dragon")]
        [TestCase(CreatureConstants.Dragon_Silver, "Silver dragon")]
        [TestCase(CreatureConstants.Dragon_White, "White dragon")]
        [TestCase(CreatureConstants.DragonTurtle, "Dragon turtle")]
        [TestCase(CreatureConstants.Dragonne, "Dragonne")]
        [TestCase(CreatureConstants.Dretch, "Dretch")]
        [TestCase(CreatureConstants.Drider, "Drider")]
        [TestCase(CreatureConstants.Dryad, "Dryad")]
        [TestCase(CreatureConstants.Duergar, "Duergar")]
        [TestCase(CreatureConstants.Dwarf, "Dwarf")]
        [TestCase(CreatureConstants.Dwarf_Deep, "Deep Dwarf")]
        [TestCase(CreatureConstants.Dwarf_Hill, "Hill Dwarf")]
        [TestCase(CreatureConstants.Dwarf_Mountain, "Mountain Dwarf")]
        [TestCase(CreatureConstants.Eagle, "Eagle")]
        [TestCase(CreatureConstants.Eagle_Giant, "Giant eagle")]
        [TestCase(CreatureConstants.Efreeti, "Efreeti")]
        [TestCase(CreatureConstants.Elasmosaurus, "Elasmosaurus")]
        [TestCase(CreatureConstants.Elemental, "Elemental")]
        [TestCase(CreatureConstants.Elephant, "Elephant")]
        [TestCase(CreatureConstants.Elf_Aquatic, "Aquatic Elf")]
        [TestCase(CreatureConstants.Elf_Drow, "Drow")]
        [TestCase(CreatureConstants.Elf_Gray, "Gray Elf")]
        [TestCase(CreatureConstants.Elf_High, "High Elf")]
        [TestCase(CreatureConstants.Elf_Half, "Half-Elf")]
        [TestCase(CreatureConstants.Elf_Wood, "Wood Elf")]
        [TestCase(CreatureConstants.Elf_Wild, "Wild Elf")]
        [TestCase(CreatureConstants.Erinyes, "Erinyes")]
        [TestCase(CreatureConstants.EtherealFilcher, "Ethereal filcher")]
        [TestCase(CreatureConstants.EtherealMarauder, "Ethereal marauder")]
        [TestCase(CreatureConstants.Ettercap, "Ettercap")]
        [TestCase(CreatureConstants.Ettin, "Ettin")]
        [TestCase(CreatureConstants.FireBeetle_Giant, "Giant fire beetle")]
        [TestCase(CreatureConstants.Formian, "Formian")]
        [TestCase(CreatureConstants.FrostWorm, "Frost worm")]
        [TestCase(CreatureConstants.Fungus, "Fungus")]
        [TestCase(CreatureConstants.Gargoyle, "Gargoyle")]
        [TestCase(CreatureConstants.GelatinousCube, "Gelatinous cube")]
        [TestCase(CreatureConstants.Genie, "Genie")]
        [TestCase(CreatureConstants.Ghaele, "Ghaele")]
        [TestCase(CreatureConstants.Ghoul, "Ghoul")]
        [TestCase(CreatureConstants.Giant_Cloud, "Cloud giant")]
        [TestCase(CreatureConstants.Giant_Fire, "Fire giant")]
        [TestCase(CreatureConstants.Giant_Frost, "Frost giant")]
        [TestCase(CreatureConstants.Giant_Hill, "Hill giant")]
        [TestCase(CreatureConstants.Giant_Stone, "Stone giant")]
        [TestCase(CreatureConstants.Giant_Storm, "Storm giant")]
        [TestCase(CreatureConstants.GibberingMouther, "Gibbering mouther")]
        [TestCase(CreatureConstants.Girallon, "Girallon")]
        [TestCase(CreatureConstants.Githyanki, "Githyanki")]
        [TestCase(CreatureConstants.Githzerai, "Githzerai")]
        [TestCase(CreatureConstants.Glabrezu, "Glabrezu")]
        [TestCase(CreatureConstants.Gnoll, "Gnoll")]
        [TestCase(CreatureConstants.Gnome, "Gnome")]
        [TestCase(CreatureConstants.Gnome_Forest, "Forest Gnome")]
        [TestCase(CreatureConstants.Gnome_Rock, "Rock Gnome")]
        [TestCase(CreatureConstants.Goblin, "Goblin")]
        [TestCase(CreatureConstants.Golem, "Golem")]
        [TestCase(CreatureConstants.Gorgon, "Gorgon")]
        [TestCase(CreatureConstants.GrayRender, "Gray render")]
        [TestCase(CreatureConstants.GreenHag, "Green hag")]
        [TestCase(CreatureConstants.Grick, "Grick")]
        [TestCase(CreatureConstants.Griffon, "Griffon")]
        [TestCase(CreatureConstants.Grig, "Grig")]
        [TestCase(CreatureConstants.Grimlock, "Grimlock")]
        [TestCase(CreatureConstants.Gynosphinx, "Gynosphinx")]
        [TestCase(CreatureConstants.Hag, "Hag")]
        [TestCase(CreatureConstants.Halfling, "Halfling")]
        [TestCase(CreatureConstants.Halfling_Deep, "Deep Halfling")]
        [TestCase(CreatureConstants.Halfling_Lightfoot, "Lightfoot Halfling")]
        [TestCase(CreatureConstants.Halfling_Tallfellow, "Tallfellow Halfling")]
        [TestCase(CreatureConstants.Harpy, "Harpy")]
        [TestCase(CreatureConstants.Hawk, "Hawk")]
        [TestCase(CreatureConstants.Hellcat, "Hellcat")]
        [TestCase(CreatureConstants.HellHound, "Hell hound")]
        [TestCase(CreatureConstants.Hellwasp, "Hellwasp")]
        [TestCase(CreatureConstants.Hellwasp_Swarm, "Hellwasp swarm")]
        [TestCase(CreatureConstants.Hezrou, "Hezrou")]
        [TestCase(CreatureConstants.Hieracosphinx, "Hieracosphinx")]
        [TestCase(CreatureConstants.Hippogriff, "Hippogriff")]
        [TestCase(CreatureConstants.Hobgoblin, "Hobgoblin")]
        [TestCase(CreatureConstants.Homunculus, "Homunculus")]
        [TestCase(CreatureConstants.HornedDevil, "Horned Devil")]
        [TestCase(CreatureConstants.Horse, "Horse")]
        [TestCase(CreatureConstants.Horse_Heavy, "Heavy horse")]
        [TestCase(CreatureConstants.Horse_Heavy_War, "Heavy warhorse")]
        [TestCase(CreatureConstants.Horse_Light, "Light horse")]
        [TestCase(CreatureConstants.Horse_Light_War, "Light warhorse")]
        [TestCase(CreatureConstants.HoundArchon, "Hound archon")]
        [TestCase(CreatureConstants.Howler, "Howler")]
        [TestCase(CreatureConstants.Human, "Human")]
        [TestCase(CreatureConstants.Hydra, "Hydra")]
        [TestCase(CreatureConstants.Hyena, "Hyena")]
        [TestCase(CreatureConstants.IceDevil, "Ice Devil")]
        [TestCase(CreatureConstants.Imp, "Imp")]
        [TestCase(CreatureConstants.Inevitable, "Inevitable")]
        [TestCase(CreatureConstants.InvisibleStalker, "Invisible stalker")]
        [TestCase(CreatureConstants.Janni, "Janni")]
        [TestCase(CreatureConstants.Kobold, "Kobold")]
        [TestCase(CreatureConstants.Kolyarut, "Kolyarut")]
        [TestCase(CreatureConstants.Kraken, "Kraken")]
        [TestCase(CreatureConstants.Krenshar, "Krenshar")]
        [TestCase(CreatureConstants.KuoToa, "Kuo-toa")]
        [TestCase(CreatureConstants.Lamia, "Lamia")]
        [TestCase(CreatureConstants.Lammasu, "Lammasu")]
        [TestCase(CreatureConstants.LanternArchon, "Lantern archon")]
        [TestCase(CreatureConstants.Lemure, "Lemure")]
        [TestCase(CreatureConstants.Leonal, "Leonal")]
        [TestCase(CreatureConstants.Leopard, "Leopard")]
        [TestCase(CreatureConstants.Lillend, "Lillend")]
        [TestCase(CreatureConstants.Lion, "Lion")]
        [TestCase(CreatureConstants.Lion_Dire, "Dire lion")]
        [TestCase(CreatureConstants.Livestock, "Livestock")]
        [TestCase(CreatureConstants.Lizard, "Lizard")]
        [TestCase(CreatureConstants.Lizard_Monitor, "Monitor lizard")]
        [TestCase(CreatureConstants.Lizardfolk, "Lizardfolk")]
        [TestCase(CreatureConstants.Locathah, "Locathah")]
        [TestCase(CreatureConstants.Locust, "Locust")]
        [TestCase(CreatureConstants.Locust_Swarm, "Locust swarm")]
        [TestCase(CreatureConstants.Lycanthrope, "Lycanthrope")]
        [TestCase(CreatureConstants.Magmin, "Magmin")]
        [TestCase(CreatureConstants.MantaRay, "Manta ray")]
        [TestCase(CreatureConstants.Manticore, "Manticore")]
        [TestCase(CreatureConstants.Marilith, "Marilith")]
        [TestCase(CreatureConstants.Marut, "Marut")]
        [TestCase(CreatureConstants.Medusa, "Medusa")]
        [TestCase(CreatureConstants.Megaraptor, "Megaraptor")]
        [TestCase(CreatureConstants.Mephit, "Mephit")]
        [TestCase(CreatureConstants.Merfolk, "Merfolk")]
        [TestCase(CreatureConstants.Mimic, "Mimic")]
        [TestCase(CreatureConstants.MindFlayer, "Mind flayer")]
        [TestCase(CreatureConstants.Minotaur, "Minotaur")]
        [TestCase(CreatureConstants.Mohrg, "Mohrg")]
        [TestCase(CreatureConstants.Monkey, "Monkey")]
        [TestCase(CreatureConstants.Mule, "Mule")]
        [TestCase(CreatureConstants.Mummy, "Mummy")]
        [TestCase(CreatureConstants.Naga, "Naga")]
        [TestCase(CreatureConstants.Nalfeshnee, "Nalfeshnee")]
        [TestCase(CreatureConstants.NessianWarhound, "Nessian warhound")]
        [TestCase(CreatureConstants.Nightshade, "Nightshade")]
        [TestCase(CreatureConstants.Nightcrawler, "Nightcrawler")]
        [TestCase(CreatureConstants.NightHag, "Night hag")]
        [TestCase(CreatureConstants.Nightmare, "Nightmare")]
        [TestCase(CreatureConstants.Nightwalker, "Nightwalker")]
        [TestCase(CreatureConstants.Nightwing, "Nightwing")]
        [TestCase(CreatureConstants.Nixie, "Nixie")]
        [TestCase(CreatureConstants.Nymph, "Nymph")]
        [TestCase(CreatureConstants.Octopus, "Octopus")]
        [TestCase(CreatureConstants.Octopus_Giant, "Giant octopus")]
        [TestCase(CreatureConstants.Ogre, "Ogre")]
        [TestCase(CreatureConstants.OgreMage, "Ogre mage")]
        [TestCase(CreatureConstants.Ooze_Gray, "Gray ooze")]
        [TestCase(CreatureConstants.Ooze_OchreJelly, "Ochre jelly")]
        [TestCase(CreatureConstants.Orc, "Orc")]
        [TestCase(CreatureConstants.Orc_Half, "Half-Orc")]
        [TestCase(CreatureConstants.BoneDevil, "Bone Devil")]
        [TestCase(CreatureConstants.Otyugh, "Otyugh")]
        [TestCase(CreatureConstants.Owl, "Owl")]
        [TestCase(CreatureConstants.Owl_Giant, "Giant owl")]
        [TestCase(CreatureConstants.Owlbear, "Owlbear")]
        [TestCase(CreatureConstants.Pegasus, "Pegasus")]
        [TestCase(CreatureConstants.PhantomFungus, "Phantom fungus")]
        [TestCase(CreatureConstants.PhaseSpider, "Phase spider")]
        [TestCase(CreatureConstants.Phasm, "Phasm")]
        [TestCase(CreatureConstants.PitFiend, "Pit fiend")]
        [TestCase(CreatureConstants.Pixie, "Pixie")]
        [TestCase(CreatureConstants.Planetar, "Planetar")]
        [TestCase(CreatureConstants.Pony, "Pony")]
        [TestCase(CreatureConstants.Pony_War, "Warpony")]
        [TestCase(CreatureConstants.Porpoise, "Porpoise")]
        [TestCase(CreatureConstants.PrayingMantis_Giant, "Giant praying mantis")]
        [TestCase(CreatureConstants.Pseudodragon, "Pseudodragon")]
        [TestCase(CreatureConstants.PurpleWorm, "Purple worm")]
        [TestCase(CreatureConstants.Pyrohydra, "Pyrohydra")]
        [TestCase(CreatureConstants.Quasit, "Quasit")]
        [TestCase(CreatureConstants.Rakshasa, "Rakshasa")]
        [TestCase(CreatureConstants.Rast, "Rast")]
        [TestCase(CreatureConstants.Rat, "Rat")]
        [TestCase(CreatureConstants.Rat_Dire, "Dire rat")]
        [TestCase(CreatureConstants.Rat_Swarm, "Rat swarm")]
        [TestCase(CreatureConstants.Raven, "Raven")]
        [TestCase(CreatureConstants.Ravid, "Ravid")]
        [TestCase(CreatureConstants.RazorBoar, "Razor boar")]
        [TestCase(CreatureConstants.Remorhaz, "Remorhaz")]
        [TestCase(CreatureConstants.Retriever, "Retriever")]
        [TestCase(CreatureConstants.Rhinoceras, "Rhinoceras")]
        [TestCase(CreatureConstants.Roc, "Roc")]
        [TestCase(CreatureConstants.Roper, "Roper")]
        [TestCase(CreatureConstants.RustMonster, "Rust monster")]
        [TestCase(CreatureConstants.Sahuagin, "Sahuagin")]
        [TestCase(CreatureConstants.Salamander, "Salamander")]
        [TestCase(CreatureConstants.Satyr, "Satyr")]
        [TestCase(CreatureConstants.Scorpion_Monstrous, "Monstrous scorpion")]
        [TestCase(CreatureConstants.Scorpionfolk, "Scorpionfolk")]
        [TestCase(CreatureConstants.SeaCat, "Sea cat")]
        [TestCase(CreatureConstants.SeaHag, "Sea hag")]
        [TestCase(CreatureConstants.Shadow, "Shadow")]
        [TestCase(CreatureConstants.ShadowMastiff, "Shadow mastiff")]
        [TestCase(CreatureConstants.Shark, "Shark")]
        [TestCase(CreatureConstants.Shark_Dire, "Dire shark")]
        [TestCase(CreatureConstants.ShamblingMound, "Shambling mound")]
        [TestCase(CreatureConstants.ShieldGuardian, "Shield guardian")]
        [TestCase(CreatureConstants.ShockerLizard, "Shocker lizard")]
        [TestCase(CreatureConstants.Shrieker, "Shrieker")]
        [TestCase(CreatureConstants.Skum, "Skum")]
        [TestCase(CreatureConstants.Slaad, "Slaad")]
        [TestCase(CreatureConstants.Snake_Constrictor, "Constrictor snake")]
        [TestCase(CreatureConstants.Snake_Constrictor_Giant, "Giant constrictor snake")]
        [TestCase(CreatureConstants.Snake_Viper, "Viper snake")]
        [TestCase(CreatureConstants.Solar, "Solar")]
        [TestCase(CreatureConstants.Spectre, "Spectre")]
        [TestCase(CreatureConstants.Spider_Swarm, "Spider swarm")]
        [TestCase(CreatureConstants.SpiderEater, "Spider eater")]
        [TestCase(CreatureConstants.Sprite, "Sprite")]
        [TestCase(CreatureConstants.Squid, "Squid")]
        [TestCase(CreatureConstants.Squid_Giant, "Giant squid")]
        [TestCase(CreatureConstants.StagBeetle_Giant, "Giant stag beetle")]
        [TestCase(CreatureConstants.Stirge, "Stirge")]
        [TestCase(CreatureConstants.Succubus, "Succubus")]
        [TestCase(CreatureConstants.Svirfneblin, "Svirfneblin")]
        [TestCase(CreatureConstants.Tarrasque, "Tarrasque")]
        [TestCase(CreatureConstants.Tendriculos, "Tendriculos")]
        [TestCase(CreatureConstants.Thoqqua, "Thoqqua")]
        [TestCase(CreatureConstants.Tiefling, "Tiefling")]
        [TestCase(CreatureConstants.Tiger, "Tiger")]
        [TestCase(CreatureConstants.Tiger_Dire, "Dire tiger")]
        [TestCase(CreatureConstants.Titan, "Titan")]
        [TestCase(CreatureConstants.Toad, "Toad")]
        [TestCase(CreatureConstants.Tojanida, "Tojanida")]
        [TestCase(CreatureConstants.Treant, "Treant")]
        [TestCase(CreatureConstants.Triceratops, "Triceratops")]
        [TestCase(CreatureConstants.Triton, "Triton")]
        [TestCase(CreatureConstants.Troglodyte, "Troglodyte")]
        [TestCase(CreatureConstants.Troll, "Troll")]
        [TestCase(CreatureConstants.TrumpetArchon, "Trumpet archon")]
        [TestCase(CreatureConstants.Tyrannosaurus, "Tyrannosaurus")]
        [TestCase(CreatureConstants.UmberHulk, "Umber hulk")]
        [TestCase(CreatureConstants.Unicorn, "Unicorn")]
        [TestCase(CreatureConstants.VampireSpawn, "Vampire spawn")]
        [TestCase(CreatureConstants.Vargouille, "Vargouille")]
        [TestCase(CreatureConstants.VioletFungus, "Violet fungus")]
        [TestCase(CreatureConstants.Vrock, "Vrock")]
        [TestCase(CreatureConstants.Wasp_Giant, "Giant wasp")]
        [TestCase(CreatureConstants.Weasel, "Weasel")]
        [TestCase(CreatureConstants.Weasel_Dire, "Dire weasel")]
        [TestCase(CreatureConstants.Werebear, "Werebear")]
        [TestCase(CreatureConstants.Wereboar, "Wereboar")]
        [TestCase(CreatureConstants.Wereboar_HillGiantDire, "Hill giant dire wereboar")]
        [TestCase(CreatureConstants.Wererat, "Wererat")]
        [TestCase(CreatureConstants.Weretiger, "Weretiger")]
        [TestCase(CreatureConstants.Werewolf, "Werewolf")]
        [TestCase(CreatureConstants.Whale, "Whale")]
        [TestCase(CreatureConstants.Wight, "Wight")]
        [TestCase(CreatureConstants.WillOWisp, "Will-O'-Wisp")]
        [TestCase(CreatureConstants.WinterWolf, "Winter wolf")]
        [TestCase(CreatureConstants.Wolf, "Wolf")]
        [TestCase(CreatureConstants.Wolf_Dire, "Dire wolf")]
        [TestCase(CreatureConstants.Wolverine, "Wolverine")]
        [TestCase(CreatureConstants.Wolverine_Dire, "Dire wolverine")]
        [TestCase(CreatureConstants.Worg, "Worg")]
        [TestCase(CreatureConstants.Wraith, "Wraith")]
        [TestCase(CreatureConstants.Wyvern, "Wyvern")]
        [TestCase(CreatureConstants.Xill, "Xill")]
        [TestCase(CreatureConstants.Xorn, "Xorn")]
        [TestCase(CreatureConstants.YethHound, "Yeth hound")]
        [TestCase(CreatureConstants.Yrthak, "Yrthak")]
        [TestCase(CreatureConstants.YuanTi, "Yuan-ti")]
        [TestCase(CreatureConstants.Zelekhut, "Zelekhut")]
        [TestCase(CreatureConstants.Templates.Ghost, "Zombie")]
        [TestCase(CreatureConstants.Templates.HalfCelestial, "Half-Celestial")]
        [TestCase(CreatureConstants.Templates.HalfDragon, "Half-Dragon")]
        [TestCase(CreatureConstants.Templates.HalfFiend, "Half-Fiend")]
        [TestCase(CreatureConstants.Templates.Lich, "Lich")]
        [TestCase(CreatureConstants.Templates.Mummy, "Mummy")]
        [TestCase(CreatureConstants.Templates.None, "")]
        [TestCase(CreatureConstants.Templates.Skeleton, "Skeleton")]
        [TestCase(CreatureConstants.Templates.Vampire, "Vampire")]
        [TestCase(CreatureConstants.Templates.Werebear, "Werebear")]
        [TestCase(CreatureConstants.Templates.Wereboar, "Wereboar")]
        [TestCase(CreatureConstants.Templates.Wererat, "Wererat")]
        [TestCase(CreatureConstants.Templates.Weretiger, "Weretiger")]
        [TestCase(CreatureConstants.Templates.Werewolf, "Werewolf")]
        [TestCase(CreatureConstants.Templates.Zombie, "Zombie")]
        public void CreatureConstant(string constant, string value)
        {
            Assert.That(constant, Is.EqualTo(value));
        }

        [TestCase(CreatureConstants.Aboleth_Mage, CreatureConstants.Aboleth, "", "Mage")]
        [TestCase(CreatureConstants.AnimatedObject_Colossal, CreatureConstants.AnimatedObject, "", SizeConstants.Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan, CreatureConstants.AnimatedObject, "", SizeConstants.Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Huge, CreatureConstants.AnimatedObject, "", SizeConstants.Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Large, CreatureConstants.AnimatedObject, "", SizeConstants.Large)]
        [TestCase(CreatureConstants.AnimatedObject_Medium, CreatureConstants.AnimatedObject, "", SizeConstants.Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Small, CreatureConstants.AnimatedObject, "", SizeConstants.Small)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny, CreatureConstants.AnimatedObject, "", SizeConstants.Tiny)]
        [TestCase(CreatureConstants.Ant_Giant_Soldier, CreatureConstants.Ant_Giant, "", "Soldier")]
        [TestCase(CreatureConstants.Ant_Giant_Worker, CreatureConstants.Ant_Giant, "", "Worker")]
        [TestCase(CreatureConstants.Ant_Giant_Queen, CreatureConstants.Ant_Giant, "", "Queen")]
        [TestCase(CreatureConstants.Arrowhawk_Adult, CreatureConstants.Arrowhawk, "", "Adult")]
        [TestCase(CreatureConstants.Arrowhawk_Elder, CreatureConstants.Arrowhawk, "", "Elder")]
        [TestCase(CreatureConstants.Arrowhawk_Juvenile, CreatureConstants.Arrowhawk, "", "Juvenile")]
        [TestCase(CreatureConstants.Badger_Celestial, CreatureConstants.Badger, "", CreatureConstants.CelestialCreature)]
        [TestCase(CreatureConstants.BarbedDevil_Hamatula, CreatureConstants.BarbedDevil, "Hamatula", "")]
        [TestCase(CreatureConstants.BeardedDevil_Barbazu, CreatureConstants.BeardedDevil, "Barbazu", "")]
        [TestCase(CreatureConstants.Barghest_Greater, CreatureConstants.Barghest, "", "Greater")]
        [TestCase(CreatureConstants.BlackPudding_Elder, CreatureConstants.BlackPudding, "", "Elder")]
        [TestCase(CreatureConstants.Centipede_Monstrous_Colossal, CreatureConstants.Centipede_Monstrous, "", SizeConstants.Colossal)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Gargantuan, CreatureConstants.Centipede_Monstrous, "", SizeConstants.Gargantuan)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Huge, CreatureConstants.Centipede_Monstrous, "", SizeConstants.Huge)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Large, CreatureConstants.Centipede_Monstrous, "", SizeConstants.Large)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Medium, CreatureConstants.Centipede_Monstrous, "", SizeConstants.Medium)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Small, CreatureConstants.Centipede_Monstrous, "", SizeConstants.Small)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Tiny, CreatureConstants.Centipede_Monstrous, "", SizeConstants.Tiny)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Fiendish_Colossal, CreatureConstants.Centipede_Monstrous, "", SizeConstants.Colossal + " " + CreatureConstants.FiendishCreature)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Fiendish_Gargantuan, CreatureConstants.Centipede_Monstrous, "", SizeConstants.Gargantuan + " " + CreatureConstants.FiendishCreature)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Fiendish_Huge, CreatureConstants.Centipede_Monstrous, "", SizeConstants.Huge + " " + CreatureConstants.FiendishCreature)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Fiendish_Large, CreatureConstants.Centipede_Monstrous, "", SizeConstants.Large + " " + CreatureConstants.FiendishCreature)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Fiendish_Medium, CreatureConstants.Centipede_Monstrous, "", SizeConstants.Medium + " " + CreatureConstants.FiendishCreature)]
        [TestCase(CreatureConstants.ChainDevil_Kyton, CreatureConstants.ChainDevil, "Kyton", "")]
        [TestCase(CreatureConstants.HornedDevil_Cornugon, CreatureConstants.HornedDevil, "Cornugon", "")]
        [TestCase(CreatureConstants.Cryohydra_5Heads, CreatureConstants.Cryohydra, "", "5 heads")]
        [TestCase(CreatureConstants.Cryohydra_6Heads, CreatureConstants.Cryohydra, "", "6 heads")]
        [TestCase(CreatureConstants.Cryohydra_7Heads, CreatureConstants.Cryohydra, "", "7 heads")]
        [TestCase(CreatureConstants.Cryohydra_8Heads, CreatureConstants.Cryohydra, "", "8 heads")]
        [TestCase(CreatureConstants.Cryohydra_9Heads, CreatureConstants.Cryohydra, "", "9 heads")]
        [TestCase(CreatureConstants.Cryohydra_10Heads, CreatureConstants.Cryohydra, "", "10 heads")]
        [TestCase(CreatureConstants.Cryohydra_11Heads, CreatureConstants.Cryohydra, "", "11 heads")]
        [TestCase(CreatureConstants.Cryohydra_12Heads, CreatureConstants.Cryohydra, "", "12 heads")]
        [TestCase(CreatureConstants.DisplacerBeast_PackLord, CreatureConstants.DisplacerBeast, "", "Pack Lord")]
        [TestCase(CreatureConstants.Djinni_Noble, CreatureConstants.Djinni, "", "Noble")]
        [TestCase(CreatureConstants.Dog_Celestial, CreatureConstants.Dog, "", CreatureConstants.CelestialCreature)]
        [TestCase(CreatureConstants.Dog_Riding, CreatureConstants.Dog, "", "Riding")]
        [TestCase(CreatureConstants.Dragon_Black_Wyrmling, CreatureConstants.Dragon_Black, "", "Wyrmling")]
        [TestCase(CreatureConstants.Dragon_Black_VeryYoung, CreatureConstants.Dragon_Black, "", "Very young")]
        [TestCase(CreatureConstants.Dragon_Black_Young, CreatureConstants.Dragon_Black, "", "Young")]
        [TestCase(CreatureConstants.Dragon_Black_Juvenile, CreatureConstants.Dragon_Black, "", "Juvenile")]
        [TestCase(CreatureConstants.Dragon_Black_YoungAdult, CreatureConstants.Dragon_Black, "", "Young adult")]
        [TestCase(CreatureConstants.Dragon_Black_Adult, CreatureConstants.Dragon_Black, "", "Adult")]
        [TestCase(CreatureConstants.Dragon_Black_MatureAdult, CreatureConstants.Dragon_Black, "", "Mature adult")]
        [TestCase(CreatureConstants.Dragon_Black_Old, CreatureConstants.Dragon_Black, "", "Old")]
        [TestCase(CreatureConstants.Dragon_Black_VeryOld, CreatureConstants.Dragon_Black, "", "Very old")]
        [TestCase(CreatureConstants.Dragon_Black_Ancient, CreatureConstants.Dragon_Black, "", "Ancient")]
        [TestCase(CreatureConstants.Dragon_Black_Wyrm, CreatureConstants.Dragon_Black, "", "Wyrm")]
        [TestCase(CreatureConstants.Dragon_Black_GreatWyrm, CreatureConstants.Dragon_Black, "", "Great wyrm")]
        [TestCase(CreatureConstants.Dragon_Blue_Wyrmling, CreatureConstants.Dragon_Blue, "", "Wyrmling")]
        [TestCase(CreatureConstants.Dragon_Blue_VeryYoung, CreatureConstants.Dragon_Blue, "", "Very young")]
        [TestCase(CreatureConstants.Dragon_Blue_Young, CreatureConstants.Dragon_Blue, "", "Young")]
        [TestCase(CreatureConstants.Dragon_Blue_Juvenile, CreatureConstants.Dragon_Blue, "", "Juvenile")]
        [TestCase(CreatureConstants.Dragon_Blue_YoungAdult, CreatureConstants.Dragon_Blue, "", "Young adult")]
        [TestCase(CreatureConstants.Dragon_Blue_Adult, CreatureConstants.Dragon_Blue, "", "Adult")]
        [TestCase(CreatureConstants.Dragon_Blue_MatureAdult, CreatureConstants.Dragon_Blue, "", "Mature adult")]
        [TestCase(CreatureConstants.Dragon_Blue_Old, CreatureConstants.Dragon_Blue, "", "Old")]
        [TestCase(CreatureConstants.Dragon_Blue_VeryOld, CreatureConstants.Dragon_Blue, "", "Very old")]
        [TestCase(CreatureConstants.Dragon_Blue_Ancient, CreatureConstants.Dragon_Blue, "", "Ancient")]
        [TestCase(CreatureConstants.Dragon_Blue_Wyrm, CreatureConstants.Dragon_Blue, "", "Wyrm")]
        [TestCase(CreatureConstants.Dragon_Blue_GreatWyrm, CreatureConstants.Dragon_Blue, "", "Great wyrm")]
        [TestCase(CreatureConstants.Dragon_Brass_Wyrmling, CreatureConstants.Dragon_Brass, "", "Wyrmling")]
        [TestCase(CreatureConstants.Dragon_Brass_VeryYoung, CreatureConstants.Dragon_Brass, "", "Very young")]
        [TestCase(CreatureConstants.Dragon_Brass_Young, CreatureConstants.Dragon_Brass, "", "Young")]
        [TestCase(CreatureConstants.Dragon_Brass_Juvenile, CreatureConstants.Dragon_Brass, "", "Juvenile")]
        [TestCase(CreatureConstants.Dragon_Brass_YoungAdult, CreatureConstants.Dragon_Brass, "", "Young adult")]
        [TestCase(CreatureConstants.Dragon_Brass_Adult, CreatureConstants.Dragon_Brass, "", "Adult")]
        [TestCase(CreatureConstants.Dragon_Brass_MatureAdult, CreatureConstants.Dragon_Brass, "", "Mature adult")]
        [TestCase(CreatureConstants.Dragon_Brass_Old, CreatureConstants.Dragon_Brass, "", "Old")]
        [TestCase(CreatureConstants.Dragon_Brass_VeryOld, CreatureConstants.Dragon_Brass, "", "Very old")]
        [TestCase(CreatureConstants.Dragon_Brass_Ancient, CreatureConstants.Dragon_Brass, "", "Ancient")]
        [TestCase(CreatureConstants.Dragon_Brass_Wyrm, CreatureConstants.Dragon_Brass, "", "Wyrm")]
        [TestCase(CreatureConstants.Dragon_Brass_GreatWyrm, CreatureConstants.Dragon_Brass, "", "Great wyrm")]
        [TestCase(CreatureConstants.Dragon_Bronze_Wyrmling, CreatureConstants.Dragon_Bronze, "", "Wyrmling")]
        [TestCase(CreatureConstants.Dragon_Bronze_VeryYoung, CreatureConstants.Dragon_Bronze, "", "Very young")]
        [TestCase(CreatureConstants.Dragon_Bronze_Young, CreatureConstants.Dragon_Bronze, "", "Young")]
        [TestCase(CreatureConstants.Dragon_Bronze_Juvenile, CreatureConstants.Dragon_Bronze, "", "Juvenile")]
        [TestCase(CreatureConstants.Dragon_Bronze_YoungAdult, CreatureConstants.Dragon_Bronze, "", "Young adult")]
        [TestCase(CreatureConstants.Dragon_Bronze_Adult, CreatureConstants.Dragon_Bronze, "", "Adult")]
        [TestCase(CreatureConstants.Dragon_Bronze_MatureAdult, CreatureConstants.Dragon_Bronze, "", "Mature adult")]
        [TestCase(CreatureConstants.Dragon_Bronze_Old, CreatureConstants.Dragon_Bronze, "", "Old")]
        [TestCase(CreatureConstants.Dragon_Bronze_VeryOld, CreatureConstants.Dragon_Bronze, "", "Very old")]
        [TestCase(CreatureConstants.Dragon_Bronze_Ancient, CreatureConstants.Dragon_Bronze, "", "Ancient")]
        [TestCase(CreatureConstants.Dragon_Bronze_Wyrm, CreatureConstants.Dragon_Bronze, "", "Wyrm")]
        [TestCase(CreatureConstants.Dragon_Bronze_GreatWyrm, CreatureConstants.Dragon_Bronze, "", "Great wyrm")]
        [TestCase(CreatureConstants.Dragon_Copper_Wyrmling, CreatureConstants.Dragon_Copper, "", "Wyrmling")]
        [TestCase(CreatureConstants.Dragon_Copper_VeryYoung, CreatureConstants.Dragon_Copper, "", "Very young")]
        [TestCase(CreatureConstants.Dragon_Copper_Young, CreatureConstants.Dragon_Copper, "", "Young")]
        [TestCase(CreatureConstants.Dragon_Copper_Juvenile, CreatureConstants.Dragon_Copper, "", "Juvenile")]
        [TestCase(CreatureConstants.Dragon_Copper_YoungAdult, CreatureConstants.Dragon_Copper, "", "Young adult")]
        [TestCase(CreatureConstants.Dragon_Copper_Adult, CreatureConstants.Dragon_Copper, "", "Adult")]
        [TestCase(CreatureConstants.Dragon_Copper_MatureAdult, CreatureConstants.Dragon_Copper, "", "Mature adult")]
        [TestCase(CreatureConstants.Dragon_Copper_Old, CreatureConstants.Dragon_Copper, "", "Old")]
        [TestCase(CreatureConstants.Dragon_Copper_VeryOld, CreatureConstants.Dragon_Copper, "", "Very old")]
        [TestCase(CreatureConstants.Dragon_Copper_Ancient, CreatureConstants.Dragon_Copper, "", "Ancient")]
        [TestCase(CreatureConstants.Dragon_Copper_Wyrm, CreatureConstants.Dragon_Copper, "", "Wyrm")]
        [TestCase(CreatureConstants.Dragon_Copper_GreatWyrm, CreatureConstants.Dragon_Copper, "", "Great wyrm")]
        [TestCase(CreatureConstants.Dragon_Gold_Wyrmling, CreatureConstants.Dragon_Gold, "", "Wyrmling")]
        [TestCase(CreatureConstants.Dragon_Gold_VeryYoung, CreatureConstants.Dragon_Gold, "", "Very young")]
        [TestCase(CreatureConstants.Dragon_Gold_Young, CreatureConstants.Dragon_Gold, "", "Young")]
        [TestCase(CreatureConstants.Dragon_Gold_Juvenile, CreatureConstants.Dragon_Gold, "", "Juvenile")]
        [TestCase(CreatureConstants.Dragon_Gold_YoungAdult, CreatureConstants.Dragon_Gold, "", "Young adult")]
        [TestCase(CreatureConstants.Dragon_Gold_Adult, CreatureConstants.Dragon_Gold, "", "Adult")]
        [TestCase(CreatureConstants.Dragon_Gold_MatureAdult, CreatureConstants.Dragon_Gold, "", "Mature adult")]
        [TestCase(CreatureConstants.Dragon_Gold_Old, CreatureConstants.Dragon_Gold, "", "Old")]
        [TestCase(CreatureConstants.Dragon_Gold_VeryOld, CreatureConstants.Dragon_Gold, "", "Very old")]
        [TestCase(CreatureConstants.Dragon_Gold_Ancient, CreatureConstants.Dragon_Gold, "", "Ancient")]
        [TestCase(CreatureConstants.Dragon_Gold_Wyrm, CreatureConstants.Dragon_Gold, "", "Wyrm")]
        [TestCase(CreatureConstants.Dragon_Gold_GreatWyrm, CreatureConstants.Dragon_Gold, "", "Great wyrm")]
        [TestCase(CreatureConstants.Dragon_Green_Wyrmling, CreatureConstants.Dragon_Green, "", "Wyrmling")]
        [TestCase(CreatureConstants.Dragon_Green_VeryYoung, CreatureConstants.Dragon_Green, "", "Very young")]
        [TestCase(CreatureConstants.Dragon_Green_Young, CreatureConstants.Dragon_Green, "", "Young")]
        [TestCase(CreatureConstants.Dragon_Green_Juvenile, CreatureConstants.Dragon_Green, "", "Juvenile")]
        [TestCase(CreatureConstants.Dragon_Green_YoungAdult, CreatureConstants.Dragon_Green, "", "Young adult")]
        [TestCase(CreatureConstants.Dragon_Green_Adult, CreatureConstants.Dragon_Green, "", "Adult")]
        [TestCase(CreatureConstants.Dragon_Green_MatureAdult, CreatureConstants.Dragon_Green, "", "Mature adult")]
        [TestCase(CreatureConstants.Dragon_Green_Old, CreatureConstants.Dragon_Green, "", "Old")]
        [TestCase(CreatureConstants.Dragon_Green_VeryOld, CreatureConstants.Dragon_Green, "", "Very old")]
        [TestCase(CreatureConstants.Dragon_Green_Ancient, CreatureConstants.Dragon_Green, "", "Ancient")]
        [TestCase(CreatureConstants.Dragon_Green_Wyrm, CreatureConstants.Dragon_Green, "", "Wyrm")]
        [TestCase(CreatureConstants.Dragon_Green_GreatWyrm, CreatureConstants.Dragon_Green, "", "Great wyrm")]
        [TestCase(CreatureConstants.Dragon_Red_Wyrmling, CreatureConstants.Dragon_Red, "", "Wyrmling")]
        [TestCase(CreatureConstants.Dragon_Red_VeryYoung, CreatureConstants.Dragon_Red, "", "Very young")]
        [TestCase(CreatureConstants.Dragon_Red_Young, CreatureConstants.Dragon_Red, "", "Young")]
        [TestCase(CreatureConstants.Dragon_Red_Juvenile, CreatureConstants.Dragon_Red, "", "Juvenile")]
        [TestCase(CreatureConstants.Dragon_Red_YoungAdult, CreatureConstants.Dragon_Red, "", "Young adult")]
        [TestCase(CreatureConstants.Dragon_Red_Adult, CreatureConstants.Dragon_Red, "", "Adult")]
        [TestCase(CreatureConstants.Dragon_Red_MatureAdult, CreatureConstants.Dragon_Red, "", "Mature adult")]
        [TestCase(CreatureConstants.Dragon_Red_Old, CreatureConstants.Dragon_Red, "", "Old")]
        [TestCase(CreatureConstants.Dragon_Red_VeryOld, CreatureConstants.Dragon_Red, "", "Very old")]
        [TestCase(CreatureConstants.Dragon_Red_Ancient, CreatureConstants.Dragon_Red, "", "Ancient")]
        [TestCase(CreatureConstants.Dragon_Red_Wyrm, CreatureConstants.Dragon_Red, "", "Wyrm")]
        [TestCase(CreatureConstants.Dragon_Red_GreatWyrm, CreatureConstants.Dragon_Red, "", "Great wyrm")]
        [TestCase(CreatureConstants.Dragon_Silver_Wyrmling, CreatureConstants.Dragon_Silver, "", "Wyrmling")]
        [TestCase(CreatureConstants.Dragon_Silver_VeryYoung, CreatureConstants.Dragon_Silver, "", "Very young")]
        [TestCase(CreatureConstants.Dragon_Silver_Young, CreatureConstants.Dragon_Silver, "", "Young")]
        [TestCase(CreatureConstants.Dragon_Silver_Juvenile, CreatureConstants.Dragon_Silver, "", "Juvenile")]
        [TestCase(CreatureConstants.Dragon_Silver_YoungAdult, CreatureConstants.Dragon_Silver, "", "Young adult")]
        [TestCase(CreatureConstants.Dragon_Silver_Adult, CreatureConstants.Dragon_Silver, "", "Adult")]
        [TestCase(CreatureConstants.Dragon_Silver_MatureAdult, CreatureConstants.Dragon_Silver, "", "Mature adult")]
        [TestCase(CreatureConstants.Dragon_Silver_Old, CreatureConstants.Dragon_Silver, "", "Old")]
        [TestCase(CreatureConstants.Dragon_Silver_VeryOld, CreatureConstants.Dragon_Silver, "", "Very old")]
        [TestCase(CreatureConstants.Dragon_Silver_Ancient, CreatureConstants.Dragon_Silver, "", "Ancient")]
        [TestCase(CreatureConstants.Dragon_Silver_Wyrm, CreatureConstants.Dragon_Silver, "", "Wyrm")]
        [TestCase(CreatureConstants.Dragon_Silver_GreatWyrm, CreatureConstants.Dragon_Silver, "", "Great wyrm")]
        [TestCase(CreatureConstants.Dragon_White_Wyrmling, CreatureConstants.Dragon_White, "", "Wyrmling")]
        [TestCase(CreatureConstants.Dragon_White_VeryYoung, CreatureConstants.Dragon_White, "", "Very young")]
        [TestCase(CreatureConstants.Dragon_White_Young, CreatureConstants.Dragon_White, "", "Young")]
        [TestCase(CreatureConstants.Dragon_White_Juvenile, CreatureConstants.Dragon_White, "", "Juvenile")]
        [TestCase(CreatureConstants.Dragon_White_YoungAdult, CreatureConstants.Dragon_White, "", "Young adult")]
        [TestCase(CreatureConstants.Dragon_White_Adult, CreatureConstants.Dragon_White, "", "Adult")]
        [TestCase(CreatureConstants.Dragon_White_MatureAdult, CreatureConstants.Dragon_White, "", "Mature adult")]
        [TestCase(CreatureConstants.Dragon_White_Old, CreatureConstants.Dragon_White, "", "Old")]
        [TestCase(CreatureConstants.Dragon_White_VeryOld, CreatureConstants.Dragon_White, "", "Very old")]
        [TestCase(CreatureConstants.Dragon_White_Ancient, CreatureConstants.Dragon_White, "", "Ancient")]
        [TestCase(CreatureConstants.Dragon_White_Wyrm, CreatureConstants.Dragon_White, "", "Wyrm")]
        [TestCase(CreatureConstants.Dragon_White_GreatWyrm, CreatureConstants.Dragon_White, "", "Great wyrm")]
        [TestCase(CreatureConstants.Elemental_Air, CreatureConstants.Elemental, "Air", "")]
        [TestCase(CreatureConstants.Elemental_Air_Elder, CreatureConstants.Elemental, "Air", "Elder")]
        [TestCase(CreatureConstants.Elemental_Air_Greater, CreatureConstants.Elemental, "Air", "Greater")]
        [TestCase(CreatureConstants.Elemental_Air_Huge, CreatureConstants.Elemental, "Air", "Huge")]
        [TestCase(CreatureConstants.Elemental_Air_Large, CreatureConstants.Elemental, "Air", "Large")]
        [TestCase(CreatureConstants.Elemental_Air_Medium, CreatureConstants.Elemental, "Air", "Medium")]
        [TestCase(CreatureConstants.Elemental_Air_Small, CreatureConstants.Elemental, "Air", "Small")]
        [TestCase(CreatureConstants.Elemental_Earth, CreatureConstants.Elemental, "Earth", "")]
        [TestCase(CreatureConstants.Elemental_Earth_Elder, CreatureConstants.Elemental, "Earth", "Elder")]
        [TestCase(CreatureConstants.Elemental_Earth_Greater, CreatureConstants.Elemental, "Earth", "Greater")]
        [TestCase(CreatureConstants.Elemental_Earth_Huge, CreatureConstants.Elemental, "Earth", "Huge")]
        [TestCase(CreatureConstants.Elemental_Earth_Large, CreatureConstants.Elemental, "Earth", "Large")]
        [TestCase(CreatureConstants.Elemental_Earth_Medium, CreatureConstants.Elemental, "Earth", "Medium")]
        [TestCase(CreatureConstants.Elemental_Earth_Small, CreatureConstants.Elemental, "Earth", "Small")]
        [TestCase(CreatureConstants.Elemental_Fire, CreatureConstants.Elemental, "Fire", "")]
        [TestCase(CreatureConstants.Elemental_Fire_Elder, CreatureConstants.Elemental, "Fire", "Elder")]
        [TestCase(CreatureConstants.Elemental_Fire_Greater, CreatureConstants.Elemental, "Fire", "Greater")]
        [TestCase(CreatureConstants.Elemental_Fire_Huge, CreatureConstants.Elemental, "Fire", "Huge")]
        [TestCase(CreatureConstants.Elemental_Fire_Large, CreatureConstants.Elemental, "Fire", "Large")]
        [TestCase(CreatureConstants.Elemental_Fire_Medium, CreatureConstants.Elemental, "Fire", "Medium")]
        [TestCase(CreatureConstants.Elemental_Fire_Small, CreatureConstants.Elemental, "Fire", "Small")]
        [TestCase(CreatureConstants.Elemental_Water, CreatureConstants.Elemental, "Water", "")]
        [TestCase(CreatureConstants.Elemental_Water_Elder, CreatureConstants.Elemental, "Water", "Elder")]
        [TestCase(CreatureConstants.Elemental_Water_Greater, CreatureConstants.Elemental, "Water", "Greater")]
        [TestCase(CreatureConstants.Elemental_Water_Huge, CreatureConstants.Elemental, "Water", "Huge")]
        [TestCase(CreatureConstants.Elemental_Water_Large, CreatureConstants.Elemental, "Water", "Large")]
        [TestCase(CreatureConstants.Elemental_Water_Medium, CreatureConstants.Elemental, "Water", "Medium")]
        [TestCase(CreatureConstants.Elemental_Water_Small, CreatureConstants.Elemental, "Water", "Small")]
        [TestCase(CreatureConstants.FireBeetle_Giant_Celestial, CreatureConstants.FireBeetle_Giant, "", CreatureConstants.CelestialCreature)]
        [TestCase(CreatureConstants.FormianMyrmarch, CreatureConstants.Formian, "", "Myrmarch")]
        [TestCase(CreatureConstants.FormianQueen, CreatureConstants.Formian, "", "Queen")]
        [TestCase(CreatureConstants.FormianTaskmaster, CreatureConstants.Formian, "", "Taskmaster")]
        [TestCase(CreatureConstants.FormianWarrior, CreatureConstants.Formian, "", "Warrior")]
        [TestCase(CreatureConstants.FormianWorker, CreatureConstants.Formian, "", "Worker")]
        [TestCase(CreatureConstants.IceDevil_Gelugon, CreatureConstants.IceDevil, "Gelugon", "")]
        [TestCase(CreatureConstants.Gargoyle_Kapoacinth, CreatureConstants.Gargoyle, "", "Kapoacinth")]
        [TestCase(CreatureConstants.Ghoul_Ghast, CreatureConstants.Ghoul, "", "Ghast")]
        [TestCase(CreatureConstants.Ghoul_Lacedon, CreatureConstants.Ghoul, "", "Lacedon")]
        [TestCase(CreatureConstants.Giant_Stone_Elder, CreatureConstants.Giant_Stone, "", "Elder")]
        [TestCase(CreatureConstants.Golem_Clay, CreatureConstants.Golem, "", "Clay")]
        [TestCase(CreatureConstants.Golem_Flesh, CreatureConstants.Golem, "", "Flesh")]
        [TestCase(CreatureConstants.Golem_Iron, CreatureConstants.Golem, "", "Iron")]
        [TestCase(CreatureConstants.Golem_Stone, CreatureConstants.Golem, "", "Stone")]
        [TestCase(CreatureConstants.Golem_Stone_Greater, CreatureConstants.Golem, "", "Greater Stone")]
        [TestCase(CreatureConstants.Hellcat_Bezekira, CreatureConstants.Hellcat, "Bezekira", "")]
        [TestCase(CreatureConstants.Hydra_5Heads, CreatureConstants.Hydra, "", "5 heads")]
        [TestCase(CreatureConstants.Hydra_6Heads, CreatureConstants.Hydra, "", "6 heads")]
        [TestCase(CreatureConstants.Hydra_7Heads, CreatureConstants.Hydra, "", "7 heads")]
        [TestCase(CreatureConstants.Hydra_8Heads, CreatureConstants.Hydra, "", "8 heads")]
        [TestCase(CreatureConstants.Hydra_9Heads, CreatureConstants.Hydra, "", "9 heads")]
        [TestCase(CreatureConstants.Hydra_10Heads, CreatureConstants.Hydra, "", "10 heads")]
        [TestCase(CreatureConstants.Hydra_11Heads, CreatureConstants.Hydra, "", "11 heads")]
        [TestCase(CreatureConstants.Hydra_12Heads, CreatureConstants.Hydra, "", "12 heads")]
        [TestCase(CreatureConstants.Lammasu_GoldenProtector, CreatureConstants.Lammasu, "", "Golden Protector")]
        [TestCase(CreatureConstants.Mephit_Air, CreatureConstants.Mephit, "Air", "")]
        [TestCase(CreatureConstants.Mephit_Dust, CreatureConstants.Mephit, "Dust", "")]
        [TestCase(CreatureConstants.Mephit_Earth, CreatureConstants.Mephit, "Earth", "")]
        [TestCase(CreatureConstants.Mephit_Fire, CreatureConstants.Mephit, "Fire", "")]
        [TestCase(CreatureConstants.Mephit_Ice, CreatureConstants.Mephit, "Ice", "")]
        [TestCase(CreatureConstants.Mephit_Magma, CreatureConstants.Mephit, "Magma", "")]
        [TestCase(CreatureConstants.Mephit_Ooze, CreatureConstants.Mephit, "Ooze", "")]
        [TestCase(CreatureConstants.Mephit_Salt, CreatureConstants.Mephit, "Salt", "")]
        [TestCase(CreatureConstants.Mephit_Steam, CreatureConstants.Mephit, "Steam", "")]
        [TestCase(CreatureConstants.Mephit_Water, CreatureConstants.Mephit, "Water", "")]
        [TestCase(CreatureConstants.Monkey_Celestial, CreatureConstants.Monkey, "", CreatureConstants.CelestialCreature)]
        [TestCase(CreatureConstants.Naga_Dark, CreatureConstants.Naga, "", "Dark")]
        [TestCase(CreatureConstants.Naga_Guardian, CreatureConstants.Naga, "", "Guardian")]
        [TestCase(CreatureConstants.Naga_Spirit, CreatureConstants.Naga, "", "Spirit")]
        [TestCase(CreatureConstants.Naga_Water, CreatureConstants.Naga, "", "Water")]
        [TestCase(CreatureConstants.Nightmare_Cauchemar, CreatureConstants.Nightmare, "", "Cauchemar")]
        [TestCase(CreatureConstants.Ogre_Merrow, CreatureConstants.Ogre, "", "Merrow")]
        [TestCase(CreatureConstants.BoneDevil_Osyluth, CreatureConstants.BoneDevil, "Osyluth", "")]
        [TestCase(CreatureConstants.Owl_Celestial, CreatureConstants.Owl, "", CreatureConstants.CelestialCreature)]
        [TestCase(CreatureConstants.Pixie_WithIrresistableDance, CreatureConstants.Pixie, "", "with Irresistable Dance")]
        [TestCase(CreatureConstants.Porpoise_Celestial, CreatureConstants.Porpoise, "", CreatureConstants.CelestialCreature)]
        [TestCase(CreatureConstants.Pyrohydra_5Heads, CreatureConstants.Pyrohydra, "", "5 heads")]
        [TestCase(CreatureConstants.Pyrohydra_6Heads, CreatureConstants.Pyrohydra, "", "6 heads")]
        [TestCase(CreatureConstants.Pyrohydra_7Heads, CreatureConstants.Pyrohydra, "", "7 heads")]
        [TestCase(CreatureConstants.Pyrohydra_8Heads, CreatureConstants.Pyrohydra, "", "8 heads")]
        [TestCase(CreatureConstants.Pyrohydra_9Heads, CreatureConstants.Pyrohydra, "", "9 heads")]
        [TestCase(CreatureConstants.Pyrohydra_10Heads, CreatureConstants.Pyrohydra, "", "10 heads")]
        [TestCase(CreatureConstants.Pyrohydra_11Heads, CreatureConstants.Pyrohydra, "", "11 heads")]
        [TestCase(CreatureConstants.Pyrohydra_12Heads, CreatureConstants.Pyrohydra, "", "12 heads")]
        [TestCase(CreatureConstants.Rat_Dire_Fiendish, CreatureConstants.Rat_Dire, "", CreatureConstants.FiendishCreature)]
        [TestCase(CreatureConstants.Raven_Fiendish, CreatureConstants.Raven, "", CreatureConstants.FiendishCreature)]
        [TestCase(CreatureConstants.Salamander_Average, CreatureConstants.Salamander, "", "Average")]
        [TestCase(CreatureConstants.Salamander_Flamebrother, CreatureConstants.Salamander, "", "Flamebrother")]
        [TestCase(CreatureConstants.Salamander_Noble, CreatureConstants.Salamander, "", "Noble")]
        [TestCase(CreatureConstants.Satyr_WithPipes, CreatureConstants.Satyr, "", "with pipes")]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Colossal, CreatureConstants.Scorpion_Monstrous, "", SizeConstants.Colossal)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Gargantuan, CreatureConstants.Scorpion_Monstrous, "", SizeConstants.Gargantuan)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Huge, CreatureConstants.Scorpion_Monstrous, "", SizeConstants.Huge)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Large, CreatureConstants.Scorpion_Monstrous, "", SizeConstants.Large)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Medium, CreatureConstants.Scorpion_Monstrous, "", SizeConstants.Medium)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Small, CreatureConstants.Scorpion_Monstrous, "", SizeConstants.Small)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Tiny, CreatureConstants.Scorpion_Monstrous, "", SizeConstants.Tiny)]
        [TestCase(CreatureConstants.Shadow_Greater, CreatureConstants.Shadow, "", "Greater")]
        [TestCase(CreatureConstants.Shark_Medium, CreatureConstants.Shark, "", SizeConstants.Medium)]
        [TestCase(CreatureConstants.Shark_Large, CreatureConstants.Shark, "", SizeConstants.Large)]
        [TestCase(CreatureConstants.Shark_Huge, CreatureConstants.Shark, "", SizeConstants.Huge)]
        [TestCase(CreatureConstants.Slaad_Blue, CreatureConstants.Slaad, "", "Blue")]
        [TestCase(CreatureConstants.Slaad_Death, CreatureConstants.Slaad, "", "Death")]
        [TestCase(CreatureConstants.Slaad_Gray, CreatureConstants.Slaad, "", "Gray")]
        [TestCase(CreatureConstants.Slaad_Green, CreatureConstants.Slaad, "", "Green")]
        [TestCase(CreatureConstants.Slaad_Red, CreatureConstants.Slaad, "", "Red")]
        [TestCase(CreatureConstants.Spider_Monstrous_Colossal, CreatureConstants.Spider_Monstrous, "", SizeConstants.Colossal)]
        [TestCase(CreatureConstants.Spider_Monstrous_Gargantuan, CreatureConstants.Spider_Monstrous, "", SizeConstants.Gargantuan)]
        [TestCase(CreatureConstants.Spider_Monstrous_Huge, CreatureConstants.Spider_Monstrous, "", SizeConstants.Huge)]
        [TestCase(CreatureConstants.Spider_Monstrous_Large, CreatureConstants.Spider_Monstrous, "", SizeConstants.Large)]
        [TestCase(CreatureConstants.Spider_Monstrous_Medium, CreatureConstants.Spider_Monstrous, "", SizeConstants.Medium)]
        [TestCase(CreatureConstants.Spider_Monstrous_Small, CreatureConstants.Spider_Monstrous, "", SizeConstants.Small)]
        [TestCase(CreatureConstants.Spider_Monstrous_Tiny, CreatureConstants.Spider_Monstrous, "", SizeConstants.Tiny)]
        [TestCase(CreatureConstants.Tojanida_Adult, CreatureConstants.Tojanida, "", "Adult")]
        [TestCase(CreatureConstants.Tojanida_Elder, CreatureConstants.Tojanida, "", "Elder")]
        [TestCase(CreatureConstants.Tojanida_Juvenile, CreatureConstants.Tojanida, "", "Juvenile")]
        [TestCase(CreatureConstants.Troll_Scrag, CreatureConstants.Troll, "", "Scrag")]
        [TestCase(CreatureConstants.UmberHulk_TrulyHorrid, CreatureConstants.UmberHulk, "", "Truly horrid")]
        [TestCase(CreatureConstants.Unicorn_CelestialCharger, CreatureConstants.Unicorn, "", "Celestial Charger")]
        [TestCase(CreatureConstants.Whale_Baleen, CreatureConstants.Whale, "", "Baleen")]
        [TestCase(CreatureConstants.Whale_Cachalot, CreatureConstants.Whale, "", "Cachalot")]
        [TestCase(CreatureConstants.Whale_Orca, CreatureConstants.Whale, "", "Orca")]
        [TestCase(CreatureConstants.Wraith_Dread, CreatureConstants.Wraith, "", "Dread")]
        [TestCase(CreatureConstants.Xorn_Average, CreatureConstants.Xorn, "", "Average")]
        [TestCase(CreatureConstants.Xorn_Elder, CreatureConstants.Xorn, "", "Elder")]
        [TestCase(CreatureConstants.Xorn_Minor, CreatureConstants.Xorn, "", "Minor")]
        [TestCase(CreatureConstants.YuanTi_Abomination, CreatureConstants.YuanTi, "", "Abomination")]
        [TestCase(CreatureConstants.YuanTi_Halfblood, CreatureConstants.YuanTi, "", "Halfblood")]
        [TestCase(CreatureConstants.YuanTi_Pureblood, CreatureConstants.YuanTi, "", "Pureblood")]
        public void CreatureConstantForSubtype(string constant, string name, string description, string subtype)
        {
            Assert.That(constant, Is.EqualTo(name));
        }

        [TestCase(CreatureConstants.Types.Aberration, "Aberration")]
        [TestCase(CreatureConstants.Types.Animal, "Animal")]
        [TestCase(CreatureConstants.Types.Construct, "Construct")]
        [TestCase(CreatureConstants.Types.Dragon, "Dragon")]
        [TestCase(CreatureConstants.Types.Elemental, "Elemental")]
        [TestCase(CreatureConstants.Types.Fey, "Fey")]
        [TestCase(CreatureConstants.Types.Giant, "Giant")]
        [TestCase(CreatureConstants.Types.Humanoid, "Humanoid")]
        [TestCase(CreatureConstants.Types.MagicalBeast, "Magical Beast")]
        [TestCase(CreatureConstants.Types.MonstrousHumanoid, "Monstrous Humanoid")]
        [TestCase(CreatureConstants.Types.Ooze, "Ooze")]
        [TestCase(CreatureConstants.Types.Outsider, "Outsider")]
        [TestCase(CreatureConstants.Types.Plant, "Plant")]
        [TestCase(CreatureConstants.Types.Undead, "Undead")]
        [TestCase(CreatureConstants.Types.Vermin, "Vermin")]
        public void CreatureTypeConstant(string constant, string value)
        {
            Assert.That(constant, Is.EqualTo(value));
        }

        [Test]
        public void AllCreatureConstants()
        {
            var creatures = CreatureConstants.All();
            Assert.Fail("need to flesh out Creature assertions");
        }

        [Test]
        public void AllTemplates()
        {
            var templates = CreatureConstants.Templates.All();
            Assert.Fail("need to flesh out template assertions");
        }
    }
}
