using CreatureGen.Creatures;
using NUnit.Framework;
using TreasureGen.Items;

namespace CreatureGen.Tests.Unit.Generators.Races
{
    [TestFixture]
    public class RaceConstantsTests
    {
        [TestCase(SizeConstants.BaseRaces.Aasimar, "Aasimar")]
        [TestCase(SizeConstants.BaseRaces.AquaticElf, "Aquatic Elf")]
        [TestCase(SizeConstants.BaseRaces.Azer, "Azer")]
        [TestCase(SizeConstants.BaseRaces.BlueSlaad, "Blue Slaad")]
        [TestCase(SizeConstants.BaseRaces.Bugbear, "Bugbear")]
        [TestCase(SizeConstants.BaseRaces.Centaur, "Centaur")]
        [TestCase(SizeConstants.BaseRaces.CloudGiant, "Cloud Giant")]
        [TestCase(SizeConstants.BaseRaces.DeathSlaad, "Death Slaad")]
        [TestCase(SizeConstants.BaseRaces.DeepDwarf, "Deep Dwarf")]
        [TestCase(SizeConstants.BaseRaces.DeepHalfling, "Deep Halfling")]
        [TestCase(SizeConstants.BaseRaces.Derro, "Derro")]
        [TestCase(SizeConstants.BaseRaces.Doppelganger, "Doppelganger")]
        [TestCase(SizeConstants.BaseRaces.Drow, "Drow")]
        [TestCase(SizeConstants.BaseRaces.DuergarDwarf, "Duergar Dwarf")]
        [TestCase(SizeConstants.BaseRaces.FireGiant, "Fire Giant")]
        [TestCase(SizeConstants.BaseRaces.ForestGnome, "Forest Gnome")]
        [TestCase(SizeConstants.BaseRaces.FrostGiant, "Frost Giant")]
        [TestCase(SizeConstants.BaseRaces.Gargoyle, "Gargoyle")]
        [TestCase(SizeConstants.BaseRaces.Githyanki, "Githyanki")]
        [TestCase(SizeConstants.BaseRaces.Githzerai, "Githzerai")]
        [TestCase(SizeConstants.BaseRaces.Gnoll, "Gnoll")]
        [TestCase(SizeConstants.BaseRaces.Goblin, "Goblin")]
        [TestCase(SizeConstants.BaseRaces.GrayElf, "Gray Elf")]
        [TestCase(SizeConstants.BaseRaces.GraySlaad, "Gray Slaad")]
        [TestCase(SizeConstants.BaseRaces.GreenSlaad, "Green Slaad")]
        [TestCase(SizeConstants.BaseRaces.Grimlock, "Grimlock")]
        [TestCase(SizeConstants.BaseRaces.HalfElf, "Half-Elf")]
        [TestCase(SizeConstants.BaseRaces.HalfOrc, "Half-Orc")]
        [TestCase(SizeConstants.BaseRaces.Harpy, "Harpy")]
        [TestCase(SizeConstants.BaseRaces.HighElf, "High Elf")]
        [TestCase(SizeConstants.BaseRaces.HillDwarf, "Hill Dwarf")]
        [TestCase(SizeConstants.BaseRaces.HillGiant, "Hill Giant")]
        [TestCase(SizeConstants.BaseRaces.Hobgoblin, "Hobgoblin")]
        [TestCase(SizeConstants.BaseRaces.HoundArchon, "Hound Archon")]
        [TestCase(SizeConstants.BaseRaces.Human, "Human")]
        [TestCase(SizeConstants.BaseRaces.Janni, "Janni")]
        [TestCase(SizeConstants.BaseRaces.Kapoacinth, "Kapoacinth")]
        [TestCase(SizeConstants.BaseRaces.Kobold, "Kobold")]
        [TestCase(SizeConstants.BaseRaces.KuoToa, "Kuo-toa")]
        [TestCase(SizeConstants.BaseRaces.LightfootHalfling, "Lightfoot Halfling")]
        [TestCase(SizeConstants.BaseRaces.Lizardfolk, "Lizardfolk")]
        [TestCase(SizeConstants.BaseRaces.Locathah, "Locathah")]
        [TestCase(SizeConstants.BaseRaces.Merfolk, "Merfolk")]
        [TestCase(SizeConstants.BaseRaces.Merrow, "Merrow")]
        [TestCase(SizeConstants.BaseRaces.MindFlayer, "Mind Flayer")]
        [TestCase(SizeConstants.BaseRaces.Minotaur, "Minotaur")]
        [TestCase(SizeConstants.BaseRaces.MountainDwarf, "Mountain Dwarf")]
        [TestCase(SizeConstants.BaseRaces.Ogre, "Ogre")]
        [TestCase(SizeConstants.BaseRaces.OgreMage, "Ogre Mage")]
        [TestCase(SizeConstants.BaseRaces.Orc, "Orc")]
        [TestCase(SizeConstants.BaseRaces.Pixie, "Pixie")]
        [TestCase(SizeConstants.BaseRaces.Rakshasa, "Rakshasa")]
        [TestCase(SizeConstants.BaseRaces.RedSlaad, "Red Slaad")]
        [TestCase(SizeConstants.BaseRaces.RockGnome, "Rock Gnome")]
        [TestCase(SizeConstants.BaseRaces.Sahuagin, "Sahuagin")]
        [TestCase(SizeConstants.BaseRaces.Satyr, "Satyr")]
        [TestCase(SizeConstants.BaseRaces.Scorpionfolk, "Scorpionfolk")]
        [TestCase(SizeConstants.BaseRaces.Scrag, "Scrag")]
        [TestCase(SizeConstants.BaseRaces.StoneGiant, "Stone Giant")]
        [TestCase(SizeConstants.BaseRaces.StormGiant, "Storm Giant")]
        [TestCase(SizeConstants.BaseRaces.Svirfneblin, "Svirfneblin")]
        [TestCase(SizeConstants.BaseRaces.TallfellowHalfling, "Tallfellow Halfling")]
        [TestCase(SizeConstants.BaseRaces.Tiefling, "Tiefling")]
        [TestCase(SizeConstants.BaseRaces.Troglodyte, "Troglodyte")]
        [TestCase(SizeConstants.BaseRaces.Troll, "Troll")]
        [TestCase(SizeConstants.BaseRaces.WildElf, "Wild Elf")]
        [TestCase(SizeConstants.BaseRaces.WoodElf, "Wood Elf")]
        [TestCase(SizeConstants.BaseRaces.YuanTiPureblood, "Yuan-ti Pureblood")]
        [TestCase(SizeConstants.BaseRaces.YuanTiHalfblood, "Yuan-ti Halfblood")]
        [TestCase(SizeConstants.BaseRaces.YuanTiAbomination, "Yuan-ti Abomination")]
        [TestCase(SizeConstants.BaseRaces.Animals.Badger, "Badger")]
        [TestCase(SizeConstants.BaseRaces.Animals.Camel, "Camel")]
        [TestCase(SizeConstants.BaseRaces.Animals.DireRat, "Dire Rat")]
        [TestCase(SizeConstants.BaseRaces.Animals.Dog, "Dog")]
        [TestCase(SizeConstants.BaseRaces.Animals.RidingDog, "Riding Dog")]
        [TestCase(SizeConstants.BaseRaces.Animals.Eagle, "Eagle")]
        [TestCase(SizeConstants.BaseRaces.Animals.Hawk, "Hawk")]
        [TestCase(SizeConstants.BaseRaces.Animals.LightHorse, "Light Horse")]
        [TestCase(SizeConstants.BaseRaces.Animals.HeavyHorse, "Heavy Horse")]
        [TestCase(SizeConstants.BaseRaces.Animals.Owl, "Owl")]
        [TestCase(SizeConstants.BaseRaces.Animals.Pony, "Pony")]
        [TestCase(SizeConstants.BaseRaces.Animals.SmallViperSnake, "Small Viper Snake")]
        [TestCase(SizeConstants.BaseRaces.Animals.MediumViperSnake, "Medium Viper Snake")]
        [TestCase(SizeConstants.BaseRaces.Animals.Wolf, "Wolf")]
        [TestCase(SizeConstants.BaseRaces.Animals.Ape, "Ape")]
        [TestCase(SizeConstants.BaseRaces.Animals.BlackBear, "Black Bear")]
        [TestCase(SizeConstants.BaseRaces.Animals.Bison, "Bison")]
        [TestCase(SizeConstants.BaseRaces.Animals.Boar, "Boar")]
        [TestCase(SizeConstants.BaseRaces.Animals.Cheetah, "Cheetah")]
        [TestCase(SizeConstants.BaseRaces.Animals.DireBadger, "Dire Badger")]
        [TestCase(SizeConstants.BaseRaces.Animals.DireBat, "Dire Bat")]
        [TestCase(SizeConstants.BaseRaces.Animals.DireWeasel, "Dire Weasel")]
        [TestCase(SizeConstants.BaseRaces.Animals.Leopard, "Leopard")]
        [TestCase(SizeConstants.BaseRaces.Animals.MonitorLizard, "Monitor Lizard")]
        [TestCase(SizeConstants.BaseRaces.Animals.ConstrictorSnake, "Constrictor Snake")]
        [TestCase(SizeConstants.BaseRaces.Animals.LargeViperSnake, "Large Viper Snake")]
        [TestCase(SizeConstants.BaseRaces.Animals.Wolverine, "Wolverine")]
        [TestCase(SizeConstants.BaseRaces.Animals.BrownBear, "Brown Bear")]
        [TestCase(SizeConstants.BaseRaces.Animals.DireWolverine, "Dire Wolverine")]
        [TestCase(SizeConstants.BaseRaces.Animals.Deinonychus, "Deinonychus")]
        [TestCase(SizeConstants.BaseRaces.Animals.DireApe, "Dire Ape")]
        [TestCase(SizeConstants.BaseRaces.Animals.DireBoar, "Dire Boar")]
        [TestCase(SizeConstants.BaseRaces.Animals.DireWolf, "Dire Wolf")]
        [TestCase(SizeConstants.BaseRaces.Animals.Lion, "Lion")]
        [TestCase(SizeConstants.BaseRaces.Animals.Rhinoceras, "Rhinoceras")]
        [TestCase(SizeConstants.BaseRaces.Animals.HugeViperSnake, "Huge Viper Snake")]
        [TestCase(SizeConstants.BaseRaces.Animals.Tiger, "Tiger")]
        [TestCase(SizeConstants.BaseRaces.Animals.PolarBear, "Polar Bear")]
        [TestCase(SizeConstants.BaseRaces.Animals.DireLion, "Dire Lion")]
        [TestCase(SizeConstants.BaseRaces.Animals.Megaraptor, "Megaraptor")]
        [TestCase(SizeConstants.BaseRaces.Animals.GiantConstrictorSnake, "Giant Constrictor Snake")]
        [TestCase(SizeConstants.BaseRaces.Animals.DireBear, "Dire Bear")]
        [TestCase(SizeConstants.BaseRaces.Animals.Elephant, "Elephant")]
        [TestCase(SizeConstants.BaseRaces.Animals.DireTiger, "Dire Tiger")]
        [TestCase(SizeConstants.BaseRaces.Animals.Triceratops, "Triceratops")]
        [TestCase(SizeConstants.BaseRaces.Animals.Tyrannosaurus, "Tyrannosaurus")]
        [TestCase(SizeConstants.BaseRaces.Animals.HeavyWarhorse, "Heavy Warhorse")]
        [TestCase(SizeConstants.BaseRaces.Animals.Warpony, "Warpony")]
        [TestCase(SizeConstants.BaseRaces.Animals.Bat, "Bat")]
        [TestCase(SizeConstants.BaseRaces.Animals.Cat, "Cat")]
        [TestCase(SizeConstants.BaseRaces.Animals.Lizard, "Lizard")]
        [TestCase(SizeConstants.BaseRaces.Animals.Rat, "Rat")]
        [TestCase(SizeConstants.BaseRaces.Animals.Raven, "Raven")]
        [TestCase(SizeConstants.BaseRaces.Animals.TinyViperSnake, "Tiny Viper Snake")]
        [TestCase(SizeConstants.BaseRaces.Animals.Toad, "Toad")]
        [TestCase(SizeConstants.BaseRaces.Animals.Weasel, "Weasel")]
        [TestCase(SizeConstants.BaseRaces.Animals.ShockerLizard, "Shocker Lizard")]
        [TestCase(SizeConstants.BaseRaces.Animals.Stirge, "Stirge")]
        [TestCase(SizeConstants.BaseRaces.Animals.FormianWorker, "Formian Worker")]
        [TestCase(SizeConstants.BaseRaces.Animals.Imp, "Imp")]
        [TestCase(SizeConstants.BaseRaces.Animals.Pseudodragon, "Pseudodragon")]
        [TestCase(SizeConstants.BaseRaces.Animals.Quasit, "Quasit")]
        [TestCase(SizeConstants.BaseRaces.Animals.CelestialBat, "Celestial Bat")]
        [TestCase(SizeConstants.BaseRaces.Animals.CelestialCat, "Celestial Cat")]
        [TestCase(SizeConstants.BaseRaces.Animals.CelestialHawk, "Celestial Hawk")]
        [TestCase(SizeConstants.BaseRaces.Animals.CelestialLizard, "Celestial Lizard")]
        [TestCase(SizeConstants.BaseRaces.Animals.CelestialOwl, "Celestial Owl")]
        [TestCase(SizeConstants.BaseRaces.Animals.CelestialRat, "Celestial Rat")]
        [TestCase(SizeConstants.BaseRaces.Animals.CelestialRaven, "Celestial Raven")]
        [TestCase(SizeConstants.BaseRaces.Animals.CelestialTinyViperSnake, "Celestial Tiny Viper Snake")]
        [TestCase(SizeConstants.BaseRaces.Animals.CelestialToad, "Celestial Toad")]
        [TestCase(SizeConstants.BaseRaces.Animals.CelestialWeasel, "Celestial Weasel")]
        [TestCase(SizeConstants.BaseRaces.Animals.FiendishBat, "Fiendish Bat")]
        [TestCase(SizeConstants.BaseRaces.Animals.FiendishCat, "Fiendish Cat")]
        [TestCase(SizeConstants.BaseRaces.Animals.FiendishHawk, "Fiendish Hawk")]
        [TestCase(SizeConstants.BaseRaces.Animals.FiendishLizard, "Fiendish Lizard")]
        [TestCase(SizeConstants.BaseRaces.Animals.FiendishOwl, "Fiendish Owl")]
        [TestCase(SizeConstants.BaseRaces.Animals.FiendishRat, "Fiendish Rat")]
        [TestCase(SizeConstants.BaseRaces.Animals.FiendishRaven, "Fiendish Raven")]
        [TestCase(SizeConstants.BaseRaces.Animals.FiendishTinyViperSnake, "Fiendish Tiny Viper Snake")]
        [TestCase(SizeConstants.BaseRaces.Animals.FiendishToad, "Fiendish Toad")]
        [TestCase(SizeConstants.BaseRaces.Animals.FiendishWeasel, "Fiendish Weasel")]
        [TestCase(SizeConstants.BaseRaces.Animals.SmallAirElemental, "Small Air Elemental")]
        [TestCase(SizeConstants.BaseRaces.Animals.SmallEarthElemental, "Small Earth Elemental")]
        [TestCase(SizeConstants.BaseRaces.Animals.SmallFireElemental, "Small Fire Elemental")]
        [TestCase(SizeConstants.BaseRaces.Animals.SmallWaterElemental, "Small Water Elemental")]
        [TestCase(SizeConstants.BaseRaces.Animals.Homonculus, "Homonculus")]
        [TestCase(SizeConstants.BaseRaces.Animals.AirMephit, "Air Mephit")]
        [TestCase(SizeConstants.BaseRaces.Animals.DustMephit, "Dust Mephit")]
        [TestCase(SizeConstants.BaseRaces.Animals.EarthMephit, "Earth Mephit")]
        [TestCase(SizeConstants.BaseRaces.Animals.FireMephit, "Fire Mephit")]
        [TestCase(SizeConstants.BaseRaces.Animals.IceMephit, "Ice Mephit")]
        [TestCase(SizeConstants.BaseRaces.Animals.MagmaMephit, "Magma Mephit")]
        [TestCase(SizeConstants.BaseRaces.Animals.OozeMephit, "Ooze Mephit")]
        [TestCase(SizeConstants.BaseRaces.Animals.SaltMephit, "Salt Mephit")]
        [TestCase(SizeConstants.BaseRaces.Animals.SteamMephit, "Steam Mephit")]
        [TestCase(SizeConstants.BaseRaces.Animals.WaterMephit, "Water Mephit")]
        [TestCase(SizeConstants.Metaraces.Ghost, "Ghost")]
        [TestCase(SizeConstants.Metaraces.HalfCelestial, "Half-Celestial")]
        [TestCase(SizeConstants.Metaraces.HalfDragon, "Half-Dragon")]
        [TestCase(SizeConstants.Metaraces.HalfFiend, "Half-Fiend")]
        [TestCase(SizeConstants.Metaraces.Lich, "Lich")]
        [TestCase(SizeConstants.Metaraces.Mummy, "Mummy")]
        [TestCase(SizeConstants.Metaraces.None, "")]
        [TestCase(SizeConstants.Metaraces.Vampire, "Vampire")]
        [TestCase(SizeConstants.Metaraces.Werebear, "Werebear")]
        [TestCase(SizeConstants.Metaraces.Wereboar, "Wereboar")]
        [TestCase(SizeConstants.Metaraces.Wererat, "Wererat")]
        [TestCase(SizeConstants.Metaraces.Weretiger, "Weretiger")]
        [TestCase(SizeConstants.Metaraces.Werewolf, "Werewolf")]
        [TestCase(SizeConstants.Metaraces.Species.Bronze, "Bronze")]
        [TestCase(SizeConstants.Metaraces.Species.Black, "Black")]
        [TestCase(SizeConstants.Metaraces.Species.Blue, "Blue")]
        [TestCase(SizeConstants.Metaraces.Species.Brass, "Brass")]
        [TestCase(SizeConstants.Metaraces.Species.Copper, "Copper")]
        [TestCase(SizeConstants.Metaraces.Species.Gold, "Gold")]
        [TestCase(SizeConstants.Metaraces.Species.Green, "Green")]
        [TestCase(SizeConstants.Metaraces.Species.Red, "Red")]
        [TestCase(SizeConstants.Metaraces.Species.Silver, "Silver")]
        [TestCase(SizeConstants.Metaraces.Species.White, "White")]
        [TestCase(SizeConstants.Sizes.Colossal, "Colossal")]
        [TestCase(SizeConstants.Sizes.Gargantuan, "Gargantuan")]
        [TestCase(SizeConstants.Sizes.Huge, "Huge")]
        [TestCase(SizeConstants.Sizes.Large, "Large")]
        [TestCase(SizeConstants.Sizes.Medium, "Medium")]
        [TestCase(SizeConstants.Sizes.Small, "Small")]
        [TestCase(SizeConstants.Sizes.Tiny, "Tiny")]
        [TestCase(SizeConstants.Ages.Adulthood, "Adulthood")]
        [TestCase(SizeConstants.Ages.MiddleAge, "Middle Age")]
        [TestCase(SizeConstants.Ages.Old, "Old")]
        [TestCase(SizeConstants.Ages.Venerable, "Venerable")]
        public void Constant(string constant, string value)
        {
            Assert.That(constant, Is.EqualTo(value));
        }

        [TestCase(SizeConstants.Sizes.Colossal, TraitConstants.Sizes.Colossal)]
        [TestCase(SizeConstants.Sizes.Gargantuan, TraitConstants.Sizes.Gargantuan)]
        [TestCase(SizeConstants.Sizes.Huge, TraitConstants.Sizes.Huge)]
        [TestCase(SizeConstants.Sizes.Large, TraitConstants.Sizes.Large)]
        [TestCase(SizeConstants.Sizes.Medium, TraitConstants.Sizes.Medium)]
        [TestCase(SizeConstants.Sizes.Small, TraitConstants.Sizes.Small)]
        [TestCase(SizeConstants.Sizes.Tiny, TraitConstants.Sizes.Tiny)]
        public void SizeConstantsMatchTreasureSizes(string characterSize, string treasureSize)
        {
            Assert.That(characterSize, Is.EqualTo(treasureSize));
        }

        [Test]
        public void AgelessConstant()
        {
            Assert.That(SizeConstants.Ages.Ageless, Is.EqualTo(-1));
        }
    }
}