using CreatureGen.Creatures;
using NUnit.Framework;
using TreasureGen.Items;

namespace CreatureGen.Tests.Unit.Generators.Races
{
    [TestFixture]
    public class RaceConstantsTests
    {
        [TestCase(CreatureConstants.Aasimar, "Aasimar")]
        [TestCase(CreatureConstants.Elf_Aquatic, "Aquatic Elf")]
        [TestCase(CreatureConstants.Azer, "Azer")]
        [TestCase(CreatureConstants.Slaad_Blue, "Blue Slaad")]
        [TestCase(CreatureConstants.Bugbear, "Bugbear")]
        [TestCase(CreatureConstants.Centaur, "Centaur")]
        [TestCase(CreatureConstants.Giant_Cloud, "Cloud Giant")]
        [TestCase(CreatureConstants.Slaad_Death, "Death Slaad")]
        [TestCase(CreatureConstants.Dwarf_Deep, "Deep Dwarf")]
        [TestCase(CreatureConstants.Halfling_Deep, "Deep Halfling")]
        [TestCase(CreatureConstants.Derro, "Derro")]
        [TestCase(CreatureConstants.Doppelganger, "Doppelganger")]
        [TestCase(CreatureConstants.Drow, "Drow")]
        [TestCase(CreatureConstants.Duergar, "Duergar Dwarf")]
        [TestCase(CreatureConstants.Giant_Fire, "Fire Giant")]
        [TestCase(CreatureConstants.Gnome_Forest, "Forest Gnome")]
        [TestCase(CreatureConstants.Giant_Frost, "Frost Giant")]
        [TestCase(CreatureConstants.Gargoyle, "Gargoyle")]
        [TestCase(CreatureConstants.Githyanki, "Githyanki")]
        [TestCase(CreatureConstants.Githzerai, "Githzerai")]
        [TestCase(CreatureConstants.Gnoll, "Gnoll")]
        [TestCase(CreatureConstants.Goblin, "Goblin")]
        [TestCase(CreatureConstants.Elf_Gray, "Gray Elf")]
        [TestCase(CreatureConstants.Slaad_Gray, "Gray Slaad")]
        [TestCase(CreatureConstants.Slaad_Green, "Green Slaad")]
        [TestCase(CreatureConstants.Grimlock, "Grimlock")]
        [TestCase(CreatureConstants.Elf_Half, "Half-Elf")]
        [TestCase(CreatureConstants.Orc_Half, "Half-Orc")]
        [TestCase(CreatureConstants.Harpy, "Harpy")]
        [TestCase(CreatureConstants.Elf_High, "High Elf")]
        [TestCase(CreatureConstants.Dwarf_Hill, "Hill Dwarf")]
        [TestCase(CreatureConstants.Giant_Hill, "Hill Giant")]
        [TestCase(CreatureConstants.Hobgoblin, "Hobgoblin")]
        [TestCase(CreatureConstants.HoundArchon, "Hound Archon")]
        [TestCase(CreatureConstants.Human, "Human")]
        [TestCase(CreatureConstants.Janni, "Janni")]
        [TestCase(CreatureConstants.Gargoyle_Kapoacinth, "Kapoacinth")]
        [TestCase(CreatureConstants.Kobold, "Kobold")]
        [TestCase(CreatureConstants.KuoToa, "Kuo-toa")]
        [TestCase(CreatureConstants.Halfling_Lightfoot, "Lightfoot Halfling")]
        [TestCase(CreatureConstants.Lizardfolk, "Lizardfolk")]
        [TestCase(CreatureConstants.Locathah, "Locathah")]
        [TestCase(CreatureConstants.Merfolk, "Merfolk")]
        [TestCase(CreatureConstants.Ogre_Merrow, "Merrow")]
        [TestCase(CreatureConstants.MindFlayer, "Mind Flayer")]
        [TestCase(CreatureConstants.Minotaur, "Minotaur")]
        [TestCase(CreatureConstants.Dwarf_Mountain, "Mountain Dwarf")]
        [TestCase(CreatureConstants.Ogre, "Ogre")]
        [TestCase(CreatureConstants.OgreMage, "Ogre Mage")]
        [TestCase(CreatureConstants.Orc, "Orc")]
        [TestCase(CreatureConstants.Pixie, "Pixie")]
        [TestCase(CreatureConstants.Rakshasa, "Rakshasa")]
        [TestCase(CreatureConstants.Slaad_Red, "Red Slaad")]
        [TestCase(CreatureConstants.Gnome_Rock, "Rock Gnome")]
        [TestCase(CreatureConstants.Sahuagin, "Sahuagin")]
        [TestCase(CreatureConstants.Satyr, "Satyr")]
        [TestCase(CreatureConstants.Scorpionfolk, "Scorpionfolk")]
        [TestCase(CreatureConstants.Troll_Scrag, "Scrag")]
        [TestCase(CreatureConstants.Giant_Stone, "Stone Giant")]
        [TestCase(CreatureConstants.Giant_Storm, "Storm Giant")]
        [TestCase(CreatureConstants.Svirfneblin, "Svirfneblin")]
        [TestCase(CreatureConstants.Halfling_Tallfellow, "Tallfellow Halfling")]
        [TestCase(CreatureConstants.Tiefling, "Tiefling")]
        [TestCase(CreatureConstants.Troglodyte, "Troglodyte")]
        [TestCase(CreatureConstants.Troll, "Troll")]
        [TestCase(CreatureConstants.Elf_Wild, "Wild Elf")]
        [TestCase(CreatureConstants.Elf_Wood, "Wood Elf")]
        [TestCase(CreatureConstants.YuanTi_Pureblood, "Yuan-ti Pureblood")]
        [TestCase(CreatureConstants.YuanTi_Halfblood, "Yuan-ti Halfblood")]
        [TestCase(CreatureConstants.YuanTi_Abomination, "Yuan-ti Abomination")]
        [TestCase(CreatureConstants.Animals.Badger, "Badger")]
        [TestCase(CreatureConstants.Animals.Camel, "Camel")]
        [TestCase(CreatureConstants.Animals.DireRat, "Dire Rat")]
        [TestCase(CreatureConstants.Animals.Dog, "Dog")]
        [TestCase(CreatureConstants.Animals.RidingDog, "Riding Dog")]
        [TestCase(CreatureConstants.Animals.Eagle, "Eagle")]
        [TestCase(CreatureConstants.Animals.Hawk, "Hawk")]
        [TestCase(CreatureConstants.Animals.LightHorse, "Light Horse")]
        [TestCase(CreatureConstants.Animals.HeavyHorse, "Heavy Horse")]
        [TestCase(CreatureConstants.Animals.Owl, "Owl")]
        [TestCase(CreatureConstants.Animals.Pony, "Pony")]
        [TestCase(CreatureConstants.Animals.SmallViperSnake, "Small Viper Snake")]
        [TestCase(CreatureConstants.Animals.MediumViperSnake, "Medium Viper Snake")]
        [TestCase(CreatureConstants.Animals.Wolf, "Wolf")]
        [TestCase(CreatureConstants.Animals.Ape, "Ape")]
        [TestCase(CreatureConstants.Animals.BlackBear, "Black Bear")]
        [TestCase(CreatureConstants.Animals.Bison, "Bison")]
        [TestCase(CreatureConstants.Animals.Boar, "Boar")]
        [TestCase(CreatureConstants.Animals.Cheetah, "Cheetah")]
        [TestCase(CreatureConstants.Animals.DireBadger, "Dire Badger")]
        [TestCase(CreatureConstants.Animals.DireBat, "Dire Bat")]
        [TestCase(CreatureConstants.Animals.DireWeasel, "Dire Weasel")]
        [TestCase(CreatureConstants.Animals.Leopard, "Leopard")]
        [TestCase(CreatureConstants.Animals.MonitorLizard, "Monitor Lizard")]
        [TestCase(CreatureConstants.Animals.ConstrictorSnake, "Constrictor Snake")]
        [TestCase(CreatureConstants.Animals.LargeViperSnake, "Large Viper Snake")]
        [TestCase(CreatureConstants.Animals.Wolverine, "Wolverine")]
        [TestCase(CreatureConstants.Animals.BrownBear, "Brown Bear")]
        [TestCase(CreatureConstants.Animals.DireWolverine, "Dire Wolverine")]
        [TestCase(CreatureConstants.Animals.Deinonychus, "Deinonychus")]
        [TestCase(CreatureConstants.Animals.DireApe, "Dire Ape")]
        [TestCase(CreatureConstants.Animals.DireBoar, "Dire Boar")]
        [TestCase(CreatureConstants.Animals.DireWolf, "Dire Wolf")]
        [TestCase(CreatureConstants.Animals.Lion, "Lion")]
        [TestCase(CreatureConstants.Animals.Rhinoceras, "Rhinoceras")]
        [TestCase(CreatureConstants.Animals.HugeViperSnake, "Huge Viper Snake")]
        [TestCase(CreatureConstants.Animals.Tiger, "Tiger")]
        [TestCase(CreatureConstants.Animals.PolarBear, "Polar Bear")]
        [TestCase(CreatureConstants.Animals.DireLion, "Dire Lion")]
        [TestCase(CreatureConstants.Animals.Megaraptor, "Megaraptor")]
        [TestCase(CreatureConstants.Animals.GiantConstrictorSnake, "Giant Constrictor Snake")]
        [TestCase(CreatureConstants.Animals.DireBear, "Dire Bear")]
        [TestCase(CreatureConstants.Animals.Elephant, "Elephant")]
        [TestCase(CreatureConstants.Animals.DireTiger, "Dire Tiger")]
        [TestCase(CreatureConstants.Animals.Triceratops, "Triceratops")]
        [TestCase(CreatureConstants.Animals.Tyrannosaurus, "Tyrannosaurus")]
        [TestCase(CreatureConstants.Animals.HeavyWarhorse, "Heavy Warhorse")]
        [TestCase(CreatureConstants.Animals.Warpony, "Warpony")]
        [TestCase(CreatureConstants.Animals.Bat, "Bat")]
        [TestCase(CreatureConstants.Animals.Cat, "Cat")]
        [TestCase(CreatureConstants.Animals.Lizard, "Lizard")]
        [TestCase(CreatureConstants.Animals.Rat, "Rat")]
        [TestCase(CreatureConstants.Animals.Raven, "Raven")]
        [TestCase(CreatureConstants.Animals.TinyViperSnake, "Tiny Viper Snake")]
        [TestCase(CreatureConstants.Animals.Toad, "Toad")]
        [TestCase(CreatureConstants.Animals.Weasel, "Weasel")]
        [TestCase(CreatureConstants.Animals.ShockerLizard, "Shocker Lizard")]
        [TestCase(CreatureConstants.Animals.Stirge, "Stirge")]
        [TestCase(CreatureConstants.Animals.FormianWorker, "Formian Worker")]
        [TestCase(CreatureConstants.Animals.Imp, "Imp")]
        [TestCase(CreatureConstants.Animals.Pseudodragon, "Pseudodragon")]
        [TestCase(CreatureConstants.Animals.Quasit, "Quasit")]
        [TestCase(CreatureConstants.Animals.CelestialBat, "Celestial Bat")]
        [TestCase(CreatureConstants.Animals.CelestialCat, "Celestial Cat")]
        [TestCase(CreatureConstants.Animals.CelestialHawk, "Celestial Hawk")]
        [TestCase(CreatureConstants.Animals.CelestialLizard, "Celestial Lizard")]
        [TestCase(CreatureConstants.Animals.CelestialOwl, "Celestial Owl")]
        [TestCase(CreatureConstants.Animals.CelestialRat, "Celestial Rat")]
        [TestCase(CreatureConstants.Animals.CelestialRaven, "Celestial Raven")]
        [TestCase(CreatureConstants.Animals.CelestialTinyViperSnake, "Celestial Tiny Viper Snake")]
        [TestCase(CreatureConstants.Animals.CelestialToad, "Celestial Toad")]
        [TestCase(CreatureConstants.Animals.CelestialWeasel, "Celestial Weasel")]
        [TestCase(CreatureConstants.Animals.FiendishBat, "Fiendish Bat")]
        [TestCase(CreatureConstants.Animals.FiendishCat, "Fiendish Cat")]
        [TestCase(CreatureConstants.Animals.FiendishHawk, "Fiendish Hawk")]
        [TestCase(CreatureConstants.Animals.FiendishLizard, "Fiendish Lizard")]
        [TestCase(CreatureConstants.Animals.FiendishOwl, "Fiendish Owl")]
        [TestCase(CreatureConstants.Animals.FiendishRat, "Fiendish Rat")]
        [TestCase(CreatureConstants.Animals.FiendishRaven, "Fiendish Raven")]
        [TestCase(CreatureConstants.Animals.FiendishTinyViperSnake, "Fiendish Tiny Viper Snake")]
        [TestCase(CreatureConstants.Animals.FiendishToad, "Fiendish Toad")]
        [TestCase(CreatureConstants.Animals.FiendishWeasel, "Fiendish Weasel")]
        [TestCase(CreatureConstants.Animals.SmallAirElemental, "Small Air Elemental")]
        [TestCase(CreatureConstants.Animals.SmallEarthElemental, "Small Earth Elemental")]
        [TestCase(CreatureConstants.Animals.SmallFireElemental, "Small Fire Elemental")]
        [TestCase(CreatureConstants.Animals.SmallWaterElemental, "Small Water Elemental")]
        [TestCase(CreatureConstants.Animals.Homonculus, "Homonculus")]
        [TestCase(CreatureConstants.Animals.AirMephit, "Air Mephit")]
        [TestCase(CreatureConstants.Animals.DustMephit, "Dust Mephit")]
        [TestCase(CreatureConstants.Animals.EarthMephit, "Earth Mephit")]
        [TestCase(CreatureConstants.Animals.FireMephit, "Fire Mephit")]
        [TestCase(CreatureConstants.Animals.IceMephit, "Ice Mephit")]
        [TestCase(CreatureConstants.Animals.MagmaMephit, "Magma Mephit")]
        [TestCase(CreatureConstants.Animals.OozeMephit, "Ooze Mephit")]
        [TestCase(CreatureConstants.Animals.SaltMephit, "Salt Mephit")]
        [TestCase(CreatureConstants.Animals.SteamMephit, "Steam Mephit")]
        [TestCase(CreatureConstants.Animals.WaterMephit, "Water Mephit")]
        [TestCase(CreatureConstants.Templates.Ghost, "Ghost")]
        [TestCase(CreatureConstants.Templates.HalfCelestial, "Half-Celestial")]
        [TestCase(CreatureConstants.Templates.HalfDragon, "Half-Dragon")]
        [TestCase(CreatureConstants.Templates.HalfFiend, "Half-Fiend")]
        [TestCase(CreatureConstants.Templates.Lich, "Lich")]
        [TestCase(CreatureConstants.Templates.Mummy, "Mummy")]
        [TestCase(CreatureConstants.Templates.None, "")]
        [TestCase(CreatureConstants.Templates.Vampire, "Vampire")]
        [TestCase(CreatureConstants.Templates.Werebear, "Werebear")]
        [TestCase(CreatureConstants.Templates.Wereboar, "Wereboar")]
        [TestCase(CreatureConstants.Templates.Wererat, "Wererat")]
        [TestCase(CreatureConstants.Templates.Weretiger, "Weretiger")]
        [TestCase(CreatureConstants.Templates.Werewolf, "Werewolf")]
        [TestCase(CreatureConstants.Templates.Species.Bronze, "Bronze")]
        [TestCase(CreatureConstants.Templates.Species.Black, "Black")]
        [TestCase(CreatureConstants.Templates.Species.Blue, "Blue")]
        [TestCase(CreatureConstants.Templates.Species.Brass, "Brass")]
        [TestCase(CreatureConstants.Templates.Species.Copper, "Copper")]
        [TestCase(CreatureConstants.Templates.Species.Gold, "Gold")]
        [TestCase(CreatureConstants.Templates.Species.Green, "Green")]
        [TestCase(CreatureConstants.Templates.Species.Red, "Red")]
        [TestCase(CreatureConstants.Templates.Species.Silver, "Silver")]
        [TestCase(CreatureConstants.Templates.Species.White, "White")]
        [TestCase(SizeConstants.Sizes.Colossal, "Colossal")]
        [TestCase(SizeConstants.Sizes.Gargantuan, "Gargantuan")]
        [TestCase(SizeConstants.Sizes.Huge, "Huge")]
        [TestCase(SizeConstants.Sizes.Large, "Large")]
        [TestCase(SizeConstants.Sizes.Medium, "Medium")]
        [TestCase(SizeConstants.Sizes.Small, "Small")]
        [TestCase(SizeConstants.Sizes.Tiny, "Tiny")]
        [TestCase(SizeConstants.Ages.Adulthood, "Adulthood")]
        [TestCase(SizeConstants.Ages.MiddleAge, "Middle Age")]
        [TestCase(SizeConstants.Ages.Old, "Old")]
        [TestCase(SizeConstants.Ages.Venerable, "Venerable")]
        public void Constant(string constant, string value)
        {
            Assert.That(constant, Is.EqualTo(value));
        }

        [TestCase(SizeConstants.Sizes.Colossal, TraitConstants.Sizes.Colossal)]
        [TestCase(SizeConstants.Sizes.Gargantuan, TraitConstants.Sizes.Gargantuan)]
        [TestCase(SizeConstants.Sizes.Huge, TraitConstants.Sizes.Huge)]
        [TestCase(SizeConstants.Sizes.Large, TraitConstants.Sizes.Large)]
        [TestCase(SizeConstants.Sizes.Medium, TraitConstants.Sizes.Medium)]
        [TestCase(SizeConstants.Sizes.Small, TraitConstants.Sizes.Small)]
        [TestCase(SizeConstants.Sizes.Tiny, TraitConstants.Sizes.Tiny)]
        public void SizeConstantsMatchTreasureSizes(string characterSize, string treasureSize)
        {
            Assert.That(characterSize, Is.EqualTo(treasureSize));
        }

        [Test]
        public void AgelessConstant()
        {
            Assert.That(SizeConstants.Ages.Ageless, Is.EqualTo(-1));
        }
    }
}