using CreatureGen.Creatures;
using CreatureGen.Defenses;
using CreatureGen.Feats;
using CreatureGen.Selectors.Selections;
using CreatureGen.Tables;
using NUnit.Framework;
using System.Collections.Generic;
using System.Linq;

namespace CreatureGen.Tests.Integration.Tables.Defenses
{
    [TestFixture]
    public class ArmorClassBonusesTests : TypesAndAmountsTests
    {
        protected override string tableName => TableNameConstants.TypeAndAmount.ArmorClassBonuses;

        [Test]
        public void ArmorClassBonusesNames()
        {
            var creatures = CreatureConstants.All();
            var creatureTypes = CreatureConstants.Types.All();
            var creatureSubtypes = CreatureConstants.Types.Subtypes.All();

            var names = creatures.Union(creatureTypes).Union(creatureSubtypes);
            AssertCollectionNames(names);
        }

        [TestCase(CreatureConstants.Aasimar)]
        [TestCase(CreatureConstants.Aboleth)]
        [TestCase(CreatureConstants.Achaierai)]
        [TestCase(CreatureConstants.Allip)]
        [TestCase(CreatureConstants.Androsphinx)]
        [TestCase(CreatureConstants.AnimatedObject_Anvil_Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Anvil_Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Anvil_Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Anvil_Large)]
        [TestCase(CreatureConstants.AnimatedObject_Anvil_Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Anvil_Small)]
        [TestCase(CreatureConstants.AnimatedObject_Anvil_Tiny)]
        [TestCase(CreatureConstants.AnimatedObject_Block_Stone_Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Block_Stone_Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Block_Stone_Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Block_Stone_Large)]
        [TestCase(CreatureConstants.AnimatedObject_Block_Stone_Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Block_Stone_Small)]
        [TestCase(CreatureConstants.AnimatedObject_Block_Stone_Tiny)]
        [TestCase(CreatureConstants.AnimatedObject_Block_Wood_Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Block_Wood_Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Block_Wood_Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Block_Wood_Large)]
        [TestCase(CreatureConstants.AnimatedObject_Block_Wood_Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Block_Wood_Small)]
        [TestCase(CreatureConstants.AnimatedObject_Block_Wood_Tiny)]
        [TestCase(CreatureConstants.AnimatedObject_Box_Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Box_Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Box_Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Box_Large)]
        [TestCase(CreatureConstants.AnimatedObject_Box_Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Box_Small)]
        [TestCase(CreatureConstants.AnimatedObject_Box_Tiny)]
        [TestCase(CreatureConstants.AnimatedObject_Carpet_Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Carpet_Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Carpet_Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Carpet_Large)]
        [TestCase(CreatureConstants.AnimatedObject_Carpet_Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Carpet_Small)]
        [TestCase(CreatureConstants.AnimatedObject_Carpet_Tiny)]
        [TestCase(CreatureConstants.AnimatedObject_Carriage_Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Carriage_Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Carriage_Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Carriage_Large)]
        [TestCase(CreatureConstants.AnimatedObject_Carriage_Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Carriage_Small)]
        [TestCase(CreatureConstants.AnimatedObject_Carriage_Tiny)]
        [TestCase(CreatureConstants.AnimatedObject_Chain_Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Chain_Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Chain_Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Chain_Large)]
        [TestCase(CreatureConstants.AnimatedObject_Chain_Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Chain_Small)]
        [TestCase(CreatureConstants.AnimatedObject_Chain_Tiny)]
        [TestCase(CreatureConstants.AnimatedObject_Chair_Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Chair_Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Chair_Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Chair_Large)]
        [TestCase(CreatureConstants.AnimatedObject_Chair_Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Chair_Small)]
        [TestCase(CreatureConstants.AnimatedObject_Chair_Tiny)]
        [TestCase(CreatureConstants.AnimatedObject_Clothes_Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Clothes_Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Clothes_Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Clothes_Large)]
        [TestCase(CreatureConstants.AnimatedObject_Clothes_Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Clothes_Small)]
        [TestCase(CreatureConstants.AnimatedObject_Clothes_Tiny)]
        [TestCase(CreatureConstants.AnimatedObject_Ladder_Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Ladder_Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Ladder_Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Ladder_Large)]
        [TestCase(CreatureConstants.AnimatedObject_Ladder_Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Ladder_Small)]
        [TestCase(CreatureConstants.AnimatedObject_Ladder_Tiny)]
        [TestCase(CreatureConstants.AnimatedObject_Rope_Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Rope_Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Rope_Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Rope_Large)]
        [TestCase(CreatureConstants.AnimatedObject_Rope_Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Rope_Small)]
        [TestCase(CreatureConstants.AnimatedObject_Rope_Tiny)]
        [TestCase(CreatureConstants.AnimatedObject_Rug_Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Rug_Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Rug_Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Rug_Large)]
        [TestCase(CreatureConstants.AnimatedObject_Rug_Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Rug_Small)]
        [TestCase(CreatureConstants.AnimatedObject_Rug_Tiny)]
        [TestCase(CreatureConstants.AnimatedObject_Sled_Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Sled_Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Sled_Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Sled_Large)]
        [TestCase(CreatureConstants.AnimatedObject_Sled_Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Sled_Small)]
        [TestCase(CreatureConstants.AnimatedObject_Sled_Tiny)]
        [TestCase(CreatureConstants.AnimatedObject_Statue_Animal_Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Statue_Animal_Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Statue_Animal_Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Statue_Animal_Large)]
        [TestCase(CreatureConstants.AnimatedObject_Statue_Animal_Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Statue_Animal_Small)]
        [TestCase(CreatureConstants.AnimatedObject_Statue_Animal_Tiny)]
        [TestCase(CreatureConstants.AnimatedObject_Statue_Humanoid_Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Statue_Humanoid_Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Statue_Humanoid_Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Statue_Humanoid_Large)]
        [TestCase(CreatureConstants.AnimatedObject_Statue_Humanoid_Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Statue_Humanoid_Small)]
        [TestCase(CreatureConstants.AnimatedObject_Statue_Humanoid_Tiny)]
        [TestCase(CreatureConstants.AnimatedObject_Stool_Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Stool_Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Stool_Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Stool_Large)]
        [TestCase(CreatureConstants.AnimatedObject_Stool_Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Stool_Small)]
        [TestCase(CreatureConstants.AnimatedObject_Stool_Tiny)]
        [TestCase(CreatureConstants.AnimatedObject_Table_Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Table_Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Table_Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Table_Large)]
        [TestCase(CreatureConstants.AnimatedObject_Table_Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Table_Small)]
        [TestCase(CreatureConstants.AnimatedObject_Table_Tiny)]
        [TestCase(CreatureConstants.AnimatedObject_Tapestry_Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Tapestry_Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Tapestry_Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Tapestry_Large)]
        [TestCase(CreatureConstants.AnimatedObject_Tapestry_Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Tapestry_Small)]
        [TestCase(CreatureConstants.AnimatedObject_Tapestry_Tiny)]
        [TestCase(CreatureConstants.AnimatedObject_Wagon_Colossal)]
        [TestCase(CreatureConstants.AnimatedObject_Wagon_Gargantuan)]
        [TestCase(CreatureConstants.AnimatedObject_Wagon_Huge)]
        [TestCase(CreatureConstants.AnimatedObject_Wagon_Large)]
        [TestCase(CreatureConstants.AnimatedObject_Wagon_Medium)]
        [TestCase(CreatureConstants.AnimatedObject_Wagon_Small)]
        [TestCase(CreatureConstants.AnimatedObject_Wagon_Tiny)]
        [TestCase(CreatureConstants.Ankheg)]
        [TestCase(CreatureConstants.Annis)]
        [TestCase(CreatureConstants.Ant_Giant_Queen)]
        [TestCase(CreatureConstants.Ant_Giant_Soldier)]
        [TestCase(CreatureConstants.Ant_Giant_Worker)]
        [TestCase(CreatureConstants.Ape)]
        [TestCase(CreatureConstants.Ape_Dire)]
        [TestCase(CreatureConstants.Aranea)]
        [TestCase(CreatureConstants.Arrowhawk_Adult)]
        [TestCase(CreatureConstants.Arrowhawk_Elder)]
        [TestCase(CreatureConstants.Arrowhawk_Juvenile)]
        [TestCase(CreatureConstants.AssassinVine)]
        [TestCase(CreatureConstants.Angel_AstralDeva, ArmorClassConstants.Deflection, 4, FeatConstants.SpecialQualities.ProtectiveAura)]
        [TestCase(CreatureConstants.Angel_Planetar, ArmorClassConstants.Deflection, 4, FeatConstants.SpecialQualities.ProtectiveAura)]
        [TestCase(CreatureConstants.Angel_Solar, ArmorClassConstants.Deflection, 4, FeatConstants.SpecialQualities.ProtectiveAura)]
        [TestCase(CreatureConstants.Athach)]
        [TestCase(CreatureConstants.Avoral)]
        [TestCase(CreatureConstants.Azer)]
        [TestCase(CreatureConstants.Babau)]
        [TestCase(CreatureConstants.Baboon)]
        [TestCase(CreatureConstants.Badger)]
        [TestCase(CreatureConstants.Badger_Dire)]
        [TestCase(CreatureConstants.Balor)]
        [TestCase(CreatureConstants.BarbedDevil_Hamatula)]
        [TestCase(CreatureConstants.Barghest)]
        [TestCase(CreatureConstants.Barghest_Greater)]
        [TestCase(CreatureConstants.Basilisk)]
        [TestCase(CreatureConstants.Basilisk_AbyssalGreater)]
        [TestCase(CreatureConstants.Bat)]
        [TestCase(CreatureConstants.Bat_Dire)]
        [TestCase(CreatureConstants.Bat_Swarm)]
        [TestCase(CreatureConstants.Bear_Black)]
        [TestCase(CreatureConstants.Bear_Brown)]
        [TestCase(CreatureConstants.Bear_Dire)]
        [TestCase(CreatureConstants.Bear_Polar)]
        [TestCase(CreatureConstants.BeardedDevil_Barbazu)]
        [TestCase(CreatureConstants.Bebilith)]
        [TestCase(CreatureConstants.Bee_Giant)]
        [TestCase(CreatureConstants.Behir)]
        [TestCase(CreatureConstants.Beholder)]
        [TestCase(CreatureConstants.Beholder_Gauth)]
        [TestCase(CreatureConstants.Belker)]
        [TestCase(CreatureConstants.Bison)]
        [TestCase(CreatureConstants.BlackPudding)]
        [TestCase(CreatureConstants.BlackPudding_Elder)]
        [TestCase(CreatureConstants.BlinkDog)]
        [TestCase(CreatureConstants.Boar)]
        [TestCase(CreatureConstants.Boar_Dire)]
        [TestCase(CreatureConstants.Bodak)]
        [TestCase(CreatureConstants.BombardierBeetle_Giant)]
        [TestCase(CreatureConstants.Bralani)]
        [TestCase(CreatureConstants.Bugbear)]
        [TestCase(CreatureConstants.Bulette)]
        [TestCase(CreatureConstants.Camel_Bactrian)]
        [TestCase(CreatureConstants.Camel_Dromedary)]
        [TestCase(CreatureConstants.CarrionCrawler)]
        [TestCase(CreatureConstants.Cat)]
        [TestCase(CreatureConstants.Centaur)]
        [TestCase(CreatureConstants.Centipede_Swarm)]
        [TestCase(CreatureConstants.ChainDevil_Kyton)]
        [TestCase(CreatureConstants.Criosphinx)]
        [TestCase(CreatureConstants.Dretch)]
        [TestCase(CreatureConstants.Erinyes)]
        [TestCase(CreatureConstants.GelatinousCube)]
        [TestCase(CreatureConstants.Glabrezu)]
        [TestCase(CreatureConstants.GrayOoze)]
        [TestCase(CreatureConstants.GreenHag)]
        [TestCase(CreatureConstants.Gynosphinx)]
        [TestCase(CreatureConstants.Hellcat_Bezekira)]
        [TestCase(CreatureConstants.Hellwasp_Swarm)]
        [TestCase(CreatureConstants.Hezrou)]
        [TestCase(CreatureConstants.Hieracosphinx)]
        [TestCase(CreatureConstants.HornedDevil_Cornugon)]
        [TestCase(CreatureConstants.IceDevil_Gelugon)]
        [TestCase(CreatureConstants.Imp)]
        [TestCase(CreatureConstants.Lemure)]
        [TestCase(CreatureConstants.Locust_Swarm)]
        [TestCase(CreatureConstants.Marilith)]
        [TestCase(CreatureConstants.Nalfeshnee)]
        [TestCase(CreatureConstants.OchreJelly)]
        [TestCase(CreatureConstants.Quasit)]
        [TestCase(CreatureConstants.PitFiend)]
        [TestCase(CreatureConstants.Rat_Swarm)]
        [TestCase(CreatureConstants.Retriever)]
        [TestCase(CreatureConstants.SeaHag)]
        [TestCase(CreatureConstants.Spider_Swarm)]
        [TestCase(CreatureConstants.Succubus)]
        [TestCase(CreatureConstants.Tiefling)]
        [TestCase(CreatureConstants.Vrock)]
        public void ArmorClassBonus(string name, string target = null, int bonus = 0, string condition = null)
        {
            var typesAndAmounts = new Dictionary<string, int>();

            if (!string.IsNullOrEmpty(target))
            {
                var type = target;
                if (!string.IsNullOrEmpty(condition))
                    type += $"{BonusSelection.Divider}{condition}";

                typesAndAmounts[type] = bonus;
            }

            AssertTypesAndAmounts(name, typesAndAmounts);
        }
    }
}
