using CreatureGen.Creatures;
using CreatureGen.Tables;
using CreatureGen.Tests.Integration.Tables.TestData;
using NUnit.Framework;
using System.Linq;

namespace CreatureGen.Tests.Integration.Tables.Defenses
{
    [TestFixture]
    public class HitDiceTests : AdjustmentsTests
    {
        protected override string tableName
        {
            get { return TableNameConstants.Set.Adjustments.HitDice; }
        }

        [Test]
        public void CollectionNames()
        {
            var creatures = CreatureConstants.All();
            var types = CreatureConstants.Types.All();

            var names = creatures.Union(types);

            AssertCollectionNames(names);
        }

        [TestCase(CreatureConstants.Aasimar, 1)]
        [TestCase(CreatureConstants.Aboleth, 8)]
        [TestCase(CreatureConstants.Achaierai, 6)]
        [TestCase(CreatureConstants.Allip, 4)]
        [TestCase(CreatureConstants.Angel_AstralDeva, 12)]
        [TestCase(CreatureConstants.Angel_Planetar, 14)]
        [TestCase(CreatureConstants.Angel_Solar, 22)]
        [TestCase(CreatureConstants.Ankheg, 3)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal, 32)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan, 16)]
        [TestCase(CreatureConstants.AnimatedObject_Huge, 8)]
        [TestCase(CreatureConstants.AnimatedObject_Large, 4)]
        [TestCase(CreatureConstants.AnimatedObject_Medium, 2)]
        [TestCase(CreatureConstants.AnimatedObject_Small, 1)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny, .5)]
        [TestCase(CreatureConstants.Annis, 7)]
        [TestCase(CreatureConstants.Ape, 4)]
        [TestCase(CreatureConstants.Ape_Dire, 5)]
        [TestCase(CreatureConstants.Arrowhawk_Adult, 7)]
        [TestCase(CreatureConstants.Arrowhawk_Elder, 15)]
        [TestCase(CreatureConstants.Arrowhawk_Juvenile, 3)]
        [TestCase(CreatureConstants.Androsphinx, 12)]
        [TestCase(CreatureConstants.Ant_Giant_Queen, 4)]
        [TestCase(CreatureConstants.Ant_Giant_Soldier, 2)]
        [TestCase(CreatureConstants.Ant_Giant_Worker, 2)]
        [TestCase(CreatureConstants.Aranea, 3)]
        [TestCase(CreatureConstants.AssassinVine, 4)]
        [TestCase(CreatureConstants.Athach, 14)]
        [TestCase(CreatureConstants.Avoral, 7)]
        [TestCase(CreatureConstants.Azer, 2)]
        [TestCase(CreatureConstants.Babau, 7)]
        [TestCase(CreatureConstants.Baboon, 1)]
        [TestCase(CreatureConstants.Badger, 1)]
        [TestCase(CreatureConstants.Badger_Dire, 3)]
        [TestCase(CreatureConstants.Balor, 20)]
        [TestCase(CreatureConstants.BarbedDevil_Hamatula, 12)]
        [TestCase(CreatureConstants.Barghest, 6)]
        [TestCase(CreatureConstants.Barghest_Greater, 9)]
        [TestCase(CreatureConstants.Basilisk, 6)]
        [TestCase(CreatureConstants.Basilisk_AbyssalGreater, 18)]
        [TestCase(CreatureConstants.Bat, .25)]
        [TestCase(CreatureConstants.Bat_Dire, 4)]
        [TestCase(CreatureConstants.Bat_Swarm, 3)]
        [TestCase(CreatureConstants.Bear_Black, 3)]
        [TestCase(CreatureConstants.Bear_Brown, 6)]
        [TestCase(CreatureConstants.Bear_Dire, 12)]
        [TestCase(CreatureConstants.Bear_Polar, 8)]
        [TestCase(CreatureConstants.BeardedDevil_Barbazu, 6)]
        [TestCase(CreatureConstants.Bebilith, 12)]
        [TestCase(CreatureConstants.Bee_Giant, 3)]
        [TestCase(CreatureConstants.Behir, 9)]
        [TestCase(CreatureConstants.Beholder, 11)]
        [TestCase(CreatureConstants.Beholder_Gauth, 6)]
        [TestCase(CreatureConstants.Belker, 7)]
        [TestCase(CreatureConstants.Bison, 5)]
        [TestCase(CreatureConstants.BlackPudding, 10)]
        [TestCase(CreatureConstants.BlackPudding_Elder, 20)]
        [TestCase(CreatureConstants.BlinkDog, 4)]
        [TestCase(CreatureConstants.Boar, 3)]
        [TestCase(CreatureConstants.Boar_Dire, 7)]
        [TestCase(CreatureConstants.Bodak, 9)]
        [TestCase(CreatureConstants.BombardierBeetle_Giant, 2)]
        [TestCase(CreatureConstants.BoneDevil_Osyluth, 10)]
        [TestCase(CreatureConstants.Bralani, 6)]
        [TestCase(CreatureConstants.Bugbear, 3)]
        [TestCase(CreatureConstants.Bulette, 9)]
        [TestCase(CreatureConstants.Camel_Bactrian, 3)]
        [TestCase(CreatureConstants.Camel_Dromedary, 3)]
        [TestCase(CreatureConstants.CarrionCrawler, 3)]
        [TestCase(CreatureConstants.Cat, .5)]
        [TestCase(CreatureConstants.Centaur, 4)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Colossal, 24)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Gargantuan, 12)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Huge, 6)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Large, 3)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Medium, 1)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Small, .5)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Tiny, .25)]
        [TestCase(CreatureConstants.Centipede_Swarm, 9)]
        [TestCase(CreatureConstants.ChainDevil_Kyton, 8)]
        [TestCase(CreatureConstants.ChaosBeast, 8)]
        [TestCase(CreatureConstants.Cheetah, 3)]
        [TestCase(CreatureConstants.Chimera, 9)]
        [TestCase(CreatureConstants.Cockatrice, 5)]
        [TestCase(CreatureConstants.Couatl, 9)]
        [TestCase(CreatureConstants.Criosphinx, 10)]
        [TestCase(CreatureConstants.Crocodile, 3)]
        [TestCase(CreatureConstants.Dragon_Black_Wyrmling, 4)]
        [TestCase(CreatureConstants.Dragon_Black_VeryYoung, 7)]
        [TestCase(CreatureConstants.Dragon_Black_Young, 10)]
        [TestCase(CreatureConstants.Dragon_Black_Juvenile, 13)]
        [TestCase(CreatureConstants.Dragon_Black_YoungAdult, 16)]
        [TestCase(CreatureConstants.Dragon_Black_Adult, 19)]
        [TestCase(CreatureConstants.Dragon_Black_MatureAdult, 22)]
        [TestCase(CreatureConstants.Dragon_Black_Old, 25)]
        [TestCase(CreatureConstants.Dragon_Black_VeryOld, 28)]
        [TestCase(CreatureConstants.Dragon_Black_Ancient, 31)]
        [TestCase(CreatureConstants.Dragon_Black_Wyrm, 34)]
        [TestCase(CreatureConstants.Dragon_Black_GreatWyrm, 37)]
        [TestCase(CreatureConstants.Dragon_Blue_Wyrmling, 6)]
        [TestCase(CreatureConstants.Dragon_Blue_VeryYoung, 9)]
        [TestCase(CreatureConstants.Dragon_Blue_Young, 12)]
        [TestCase(CreatureConstants.Dragon_Blue_Juvenile, 15)]
        [TestCase(CreatureConstants.Dragon_Blue_YoungAdult, 18)]
        [TestCase(CreatureConstants.Dragon_Blue_Adult, 21)]
        [TestCase(CreatureConstants.Dragon_Blue_MatureAdult, 24)]
        [TestCase(CreatureConstants.Dragon_Blue_Old, 27)]
        [TestCase(CreatureConstants.Dragon_Blue_VeryOld, 30)]
        [TestCase(CreatureConstants.Dragon_Blue_Ancient, 33)]
        [TestCase(CreatureConstants.Dragon_Blue_Wyrm, 36)]
        [TestCase(CreatureConstants.Dragon_Blue_GreatWyrm, 39)]
        [TestCase(CreatureConstants.Dragon_Green_Wyrmling, 5)]
        [TestCase(CreatureConstants.Dragon_Green_VeryYoung, 8)]
        [TestCase(CreatureConstants.Dragon_Green_Young, 11)]
        [TestCase(CreatureConstants.Dragon_Green_Juvenile, 14)]
        [TestCase(CreatureConstants.Dragon_Green_YoungAdult, 17)]
        [TestCase(CreatureConstants.Dragon_Green_Adult, 20)]
        [TestCase(CreatureConstants.Dragon_Green_MatureAdult, 23)]
        [TestCase(CreatureConstants.Dragon_Green_Old, 26)]
        [TestCase(CreatureConstants.Dragon_Green_VeryOld, 29)]
        [TestCase(CreatureConstants.Dragon_Green_Ancient, 32)]
        [TestCase(CreatureConstants.Dragon_Green_Wyrm, 35)]
        [TestCase(CreatureConstants.Dragon_Green_GreatWyrm, 38)]
        [TestCase(CreatureConstants.Dragon_Red_Wyrmling, 7)]
        [TestCase(CreatureConstants.Dragon_Red_VeryYoung, 10)]
        [TestCase(CreatureConstants.Dragon_Red_Young, 13)]
        [TestCase(CreatureConstants.Dragon_Red_Juvenile, 16)]
        [TestCase(CreatureConstants.Dragon_Red_YoungAdult, 19)]
        [TestCase(CreatureConstants.Dragon_Red_Adult, 22)]
        [TestCase(CreatureConstants.Dragon_Red_MatureAdult, 25)]
        [TestCase(CreatureConstants.Dragon_Red_Old, 28)]
        [TestCase(CreatureConstants.Dragon_Red_VeryOld, 31)]
        [TestCase(CreatureConstants.Dragon_Red_Ancient, 34)]
        [TestCase(CreatureConstants.Dragon_Red_Wyrm, 37)]
        [TestCase(CreatureConstants.Dragon_Red_GreatWyrm, 40)]
        [TestCase(CreatureConstants.Dragon_White_Wyrmling, 3)]
        [TestCase(CreatureConstants.Dragon_White_VeryYoung, 6)]
        [TestCase(CreatureConstants.Dragon_White_Young, 9)]
        [TestCase(CreatureConstants.Dragon_White_Juvenile, 12)]
        [TestCase(CreatureConstants.Dragon_White_YoungAdult, 15)]
        [TestCase(CreatureConstants.Dragon_White_Adult, 18)]
        [TestCase(CreatureConstants.Dragon_White_MatureAdult, 21)]
        [TestCase(CreatureConstants.Dragon_White_Old, 24)]
        [TestCase(CreatureConstants.Dragon_White_VeryOld, 27)]
        [TestCase(CreatureConstants.Dragon_White_Ancient, 30)]
        [TestCase(CreatureConstants.Dragon_White_Wyrm, 33)]
        [TestCase(CreatureConstants.Dragon_White_GreatWyrm, 36)]
        [TestCase(CreatureConstants.Dragon_Brass_Wyrmling, 4)]
        [TestCase(CreatureConstants.Dragon_Brass_VeryYoung, 7)]
        [TestCase(CreatureConstants.Dragon_Brass_Young, 10)]
        [TestCase(CreatureConstants.Dragon_Brass_Juvenile, 13)]
        [TestCase(CreatureConstants.Dragon_Brass_YoungAdult, 16)]
        [TestCase(CreatureConstants.Dragon_Brass_Adult, 19)]
        [TestCase(CreatureConstants.Dragon_Brass_MatureAdult, 22)]
        [TestCase(CreatureConstants.Dragon_Brass_Old, 25)]
        [TestCase(CreatureConstants.Dragon_Brass_VeryOld, 28)]
        [TestCase(CreatureConstants.Dragon_Brass_Ancient, 31)]
        [TestCase(CreatureConstants.Dragon_Brass_Wyrm, 34)]
        [TestCase(CreatureConstants.Dragon_Brass_GreatWyrm, 37)]
        [TestCase(CreatureConstants.Dragon_Bronze_Wyrmling, 6)]
        [TestCase(CreatureConstants.Dragon_Bronze_VeryYoung, 9)]
        [TestCase(CreatureConstants.Dragon_Bronze_Young, 12)]
        [TestCase(CreatureConstants.Dragon_Bronze_Juvenile, 15)]
        [TestCase(CreatureConstants.Dragon_Bronze_YoungAdult, 18)]
        [TestCase(CreatureConstants.Dragon_Bronze_Adult, 21)]
        [TestCase(CreatureConstants.Dragon_Bronze_MatureAdult, 24)]
        [TestCase(CreatureConstants.Dragon_Bronze_Old, 27)]
        [TestCase(CreatureConstants.Dragon_Bronze_VeryOld, 30)]
        [TestCase(CreatureConstants.Dragon_Bronze_Ancient, 33)]
        [TestCase(CreatureConstants.Dragon_Bronze_Wyrm, 36)]
        [TestCase(CreatureConstants.Dragon_Bronze_GreatWyrm, 39)]
        [TestCase(CreatureConstants.Dragon_Copper_Wyrmling, 5)]
        [TestCase(CreatureConstants.Dragon_Copper_VeryYoung, 8)]
        [TestCase(CreatureConstants.Dragon_Copper_Young, 11)]
        [TestCase(CreatureConstants.Dragon_Copper_Juvenile, 14)]
        [TestCase(CreatureConstants.Dragon_Copper_YoungAdult, 17)]
        [TestCase(CreatureConstants.Dragon_Copper_Adult, 20)]
        [TestCase(CreatureConstants.Dragon_Copper_MatureAdult, 23)]
        [TestCase(CreatureConstants.Dragon_Copper_Old, 26)]
        [TestCase(CreatureConstants.Dragon_Copper_VeryOld, 29)]
        [TestCase(CreatureConstants.Dragon_Copper_Ancient, 32)]
        [TestCase(CreatureConstants.Dragon_Copper_Wyrm, 35)]
        [TestCase(CreatureConstants.Dragon_Copper_GreatWyrm, 38)]
        [TestCase(CreatureConstants.Dragon_Gold_Wyrmling, 8)]
        [TestCase(CreatureConstants.Dragon_Gold_VeryYoung, 11)]
        [TestCase(CreatureConstants.Dragon_Gold_Young, 14)]
        [TestCase(CreatureConstants.Dragon_Gold_Juvenile, 17)]
        [TestCase(CreatureConstants.Dragon_Gold_YoungAdult, 20)]
        [TestCase(CreatureConstants.Dragon_Gold_Adult, 23)]
        [TestCase(CreatureConstants.Dragon_Gold_MatureAdult, 26)]
        [TestCase(CreatureConstants.Dragon_Gold_Old, 29)]
        [TestCase(CreatureConstants.Dragon_Gold_VeryOld, 32)]
        [TestCase(CreatureConstants.Dragon_Gold_Ancient, 35)]
        [TestCase(CreatureConstants.Dragon_Gold_Wyrm, 38)]
        [TestCase(CreatureConstants.Dragon_Gold_GreatWyrm, 41)]
        [TestCase(CreatureConstants.Dragon_Silver_Wyrmling, 7)]
        [TestCase(CreatureConstants.Dragon_Silver_VeryYoung, 10)]
        [TestCase(CreatureConstants.Dragon_Silver_Young, 13)]
        [TestCase(CreatureConstants.Dragon_Silver_Juvenile, 16)]
        [TestCase(CreatureConstants.Dragon_Silver_YoungAdult, 19)]
        [TestCase(CreatureConstants.Dragon_Silver_Adult, 22)]
        [TestCase(CreatureConstants.Dragon_Silver_MatureAdult, 25)]
        [TestCase(CreatureConstants.Dragon_Silver_Old, 28)]
        [TestCase(CreatureConstants.Dragon_Silver_VeryOld, 31)]
        [TestCase(CreatureConstants.Dragon_Silver_Ancient, 34)]
        [TestCase(CreatureConstants.Dragon_Silver_Wyrm, 37)]
        [TestCase(CreatureConstants.Dragon_Silver_GreatWyrm, 40)]
        [TestCase(CreatureConstants.Dretch, 2)]
        [TestCase(CreatureConstants.Dwarf_Deep, 1)]
        [TestCase(CreatureConstants.Dwarf_Duergar, 1)]
        [TestCase(CreatureConstants.Dwarf_Hill, 1)]
        [TestCase(CreatureConstants.Dwarf_Mountain, 1)]
        [TestCase(CreatureConstants.Elemental_Air_Elder, 24)]
        [TestCase(CreatureConstants.Elemental_Air_Greater, 21)]
        [TestCase(CreatureConstants.Elemental_Air_Huge, 16)]
        [TestCase(CreatureConstants.Elemental_Air_Large, 8)]
        [TestCase(CreatureConstants.Elemental_Air_Medium, 4)]
        [TestCase(CreatureConstants.Elemental_Air_Small, 2)]
        [TestCase(CreatureConstants.Elemental_Earth_Elder, 24)]
        [TestCase(CreatureConstants.Elemental_Earth_Greater, 21)]
        [TestCase(CreatureConstants.Elemental_Earth_Huge, 16)]
        [TestCase(CreatureConstants.Elemental_Earth_Large, 8)]
        [TestCase(CreatureConstants.Elemental_Earth_Medium, 4)]
        [TestCase(CreatureConstants.Elemental_Earth_Small, 2)]
        [TestCase(CreatureConstants.Elemental_Fire_Elder, 24)]
        [TestCase(CreatureConstants.Elemental_Fire_Greater, 21)]
        [TestCase(CreatureConstants.Elemental_Fire_Huge, 16)]
        [TestCase(CreatureConstants.Elemental_Fire_Large, 8)]
        [TestCase(CreatureConstants.Elemental_Fire_Medium, 4)]
        [TestCase(CreatureConstants.Elemental_Fire_Small, 2)]
        [TestCase(CreatureConstants.Elemental_Water_Elder, 24)]
        [TestCase(CreatureConstants.Elemental_Water_Greater, 21)]
        [TestCase(CreatureConstants.Elemental_Water_Huge, 16)]
        [TestCase(CreatureConstants.Elemental_Water_Large, 8)]
        [TestCase(CreatureConstants.Elemental_Water_Medium, 4)]
        [TestCase(CreatureConstants.Elemental_Water_Small, 2)]
        [TestCase(CreatureConstants.Elf_Aquatic, 1)]
        [TestCase(CreatureConstants.Elf_Drow, 1)]
        [TestCase(CreatureConstants.Elf_Gray, 1)]
        [TestCase(CreatureConstants.Elf_Half, 1)]
        [TestCase(CreatureConstants.Elf_High, 1)]
        [TestCase(CreatureConstants.Elf_Wild, 1)]
        [TestCase(CreatureConstants.Elf_Wood, 1)]
        [TestCase(CreatureConstants.Erinyes, 9)]
        [TestCase(CreatureConstants.GelatinousCube, 4)]
        [TestCase(CreatureConstants.Glabrezu, 12)]
        [TestCase(CreatureConstants.Gnome_Forest, 1)]
        [TestCase(CreatureConstants.Gnome_Rock, 1)]
        [TestCase(CreatureConstants.Gnome_Svirfneblin, 1)]
        [TestCase(CreatureConstants.Goblin, 1)]
        [TestCase(CreatureConstants.GrayOoze, 3)]
        [TestCase(CreatureConstants.GreenHag, 9)]
        [TestCase(CreatureConstants.Gynosphinx, 8)]
        [TestCase(CreatureConstants.Halfling_Deep, 1)]
        [TestCase(CreatureConstants.Halfling_Lightfoot, 1)]
        [TestCase(CreatureConstants.Halfling_Tallfellow, 1)]
        [TestCase(CreatureConstants.Hellcat_Bezekira, 8)]
        [TestCase(CreatureConstants.Hellwasp_Swarm, 12)]
        [TestCase(CreatureConstants.Hezrou, 10)]
        [TestCase(CreatureConstants.Hieracosphinx, 9)]
        [TestCase(CreatureConstants.HornedDevil_Cornugon, 15)]
        [TestCase(CreatureConstants.Human, 1)]
        [TestCase(CreatureConstants.IceDevil_Gelugon, 14)]
        [TestCase(CreatureConstants.Imp, 3)]
        [TestCase(CreatureConstants.Lemure, 2)]
        [TestCase(CreatureConstants.Locust_Swarm, 6)]
        [TestCase(CreatureConstants.Marilith, 16)]
        [TestCase(CreatureConstants.Mephit_Air, 3)]
        [TestCase(CreatureConstants.Mephit_Dust, 3)]
        [TestCase(CreatureConstants.Mephit_Earth, 3)]
        [TestCase(CreatureConstants.Mephit_Fire, 3)]
        [TestCase(CreatureConstants.Mephit_Ice, 3)]
        [TestCase(CreatureConstants.Mephit_Magma, 3)]
        [TestCase(CreatureConstants.Mephit_Ooze, 3)]
        [TestCase(CreatureConstants.Mephit_Salt, 3)]
        [TestCase(CreatureConstants.Mephit_Steam, 3)]
        [TestCase(CreatureConstants.Mephit_Water, 3)]
        [TestCase(CreatureConstants.Nalfeshnee, 14)]
        [TestCase(CreatureConstants.OchreJelly, 6)]
        [TestCase(CreatureConstants.Orc, 1)]
        [TestCase(CreatureConstants.Orc_Half, 1)]
        [TestCase(CreatureConstants.PitFiend, 18)]
        [TestCase(CreatureConstants.Quasit, 3)]
        [TestCase(CreatureConstants.Rat_Swarm, 4)]
        [TestCase(CreatureConstants.Retriever, 10)]
        [TestCase(CreatureConstants.Salamander_Average, 9)]
        [TestCase(CreatureConstants.Salamander_Flamebrother, 4)]
        [TestCase(CreatureConstants.Salamander_Noble, 15)]
        [TestCase(CreatureConstants.SeaHag, 3)]
        [TestCase(CreatureConstants.Slaad_Blue, 8)]
        [TestCase(CreatureConstants.Slaad_Death, 15)]
        [TestCase(CreatureConstants.Slaad_Gray, 10)]
        [TestCase(CreatureConstants.Slaad_Green, 9)]
        [TestCase(CreatureConstants.Slaad_Red, 7)]
        [TestCase(CreatureConstants.Spider_Swarm, 2)]
        [TestCase(CreatureConstants.Succubus, 6)]
        [TestCase(CreatureConstants.Tiefling, 1)]
        [TestCase(CreatureConstants.Tojanida_Adult, 7)]
        [TestCase(CreatureConstants.Tojanida_Elder, 15)]
        [TestCase(CreatureConstants.Tojanida_Juvenile, 3)]
        [TestCase(CreatureConstants.Vrock, 10)]
        [TestCase(CreatureConstants.Whale_Baleen, 12)]
        [TestCase(CreatureConstants.Whale_Cachalot, 12)]
        [TestCase(CreatureConstants.Whale_Orca, 9)]
        [TestCase(CreatureConstants.Xorn_Average, 7)]
        [TestCase(CreatureConstants.Xorn_Elder, 15)]
        [TestCase(CreatureConstants.Xorn_Minor, 3)]
        public void HitDiceQuantity(string creature, double quantity)
        {
            AssertAdjustment(creature, quantity);
        }

        [TestCase(CreatureConstants.Types.Aberration, 8)]
        [TestCase(CreatureConstants.Types.Animal, 8)]
        [TestCase(CreatureConstants.Types.Construct, 10)]
        [TestCase(CreatureConstants.Types.Dragon, 12)]
        [TestCase(CreatureConstants.Types.Elemental, 8)]
        [TestCase(CreatureConstants.Types.Fey, 6)]
        [TestCase(CreatureConstants.Types.Giant, 8)]
        [TestCase(CreatureConstants.Types.Humanoid, 8)]
        [TestCase(CreatureConstants.Types.MagicalBeast, 10)]
        [TestCase(CreatureConstants.Types.MonstrousHumanoid, 8)]
        [TestCase(CreatureConstants.Types.Ooze, 10)]
        [TestCase(CreatureConstants.Types.Outsider, 8)]
        [TestCase(CreatureConstants.Types.Plant, 8)]
        [TestCase(CreatureConstants.Types.Undead, 12)]
        [TestCase(CreatureConstants.Types.Vermin, 8)]
        public void HitDie(string creatureType, int quantity)
        {
            AssertAdjustment(creatureType, quantity);
        }

        [TestCaseSource(typeof(CreatureTestData), "All")]
        public void PositiveHitDiceQuantity(string creature)
        {
            var hitDiceQuantity = GetAdjustment(creature);
            Assert.That(hitDiceQuantity, Is.Positive);
        }

        [TestCase(CreatureConstants.Types.Aberration)]
        [TestCase(CreatureConstants.Types.Animal)]
        [TestCase(CreatureConstants.Types.Construct)]
        [TestCase(CreatureConstants.Types.Dragon)]
        [TestCase(CreatureConstants.Types.Elemental)]
        [TestCase(CreatureConstants.Types.Fey)]
        [TestCase(CreatureConstants.Types.Giant)]
        [TestCase(CreatureConstants.Types.Humanoid)]
        [TestCase(CreatureConstants.Types.MagicalBeast)]
        [TestCase(CreatureConstants.Types.MonstrousHumanoid)]
        [TestCase(CreatureConstants.Types.Ooze)]
        [TestCase(CreatureConstants.Types.Outsider)]
        [TestCase(CreatureConstants.Types.Plant)]
        [TestCase(CreatureConstants.Types.Undead)]
        [TestCase(CreatureConstants.Types.Vermin)]
        public void CreatureTypeHasValidHitDie(string creatureType)
        {
            var validDie = new[] { 2, 3, 4, 6, 8, 10, 12, 20, 100 };

            var hitDie = GetAdjustment(creatureType);
            Assert.That(hitDie, Is.Positive);
            Assert.That(validDie, Contains.Item(hitDie));
        }
    }
}
