using DnDGen.CreatureGen.Creatures;
using DnDGen.CreatureGen.Verifiers;
using NUnit.Framework;
using System;
using System.Diagnostics;

namespace DnDGen.CreatureGen.Tests.Integration.Verifiers
{
    [TestFixture]
    public class CreatureVerifierTests : IntegrationTests
    {
        private ICreatureVerifier creatureVerifier;
        private Stopwatch stopwatch;
        private TimeSpan timeLimit;

        [SetUp]
        public void Setup()
        {
            stopwatch = new Stopwatch();
            stopwatch.Reset();

            creatureVerifier = GetNewInstanceOf<ICreatureVerifier>();

            timeLimit = TimeSpan.FromSeconds(1);
        }

        [TestCase(CreatureConstants.Ape, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Ape, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Ape_Dire, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Ape_Dire, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Arrowhawk_Adult, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Arrowhawk_Adult, CreatureConstants.Templates.HalfDragon_Black, false)]
        [TestCase(CreatureConstants.Arrowhawk_Adult, CreatureConstants.Templates.HalfDragon_Blue, false)]
        [TestCase(CreatureConstants.Arrowhawk_Adult, CreatureConstants.Templates.HalfDragon_Brass, false)]
        [TestCase(CreatureConstants.Arrowhawk_Adult, CreatureConstants.Templates.HalfDragon_Bronze, false)]
        [TestCase(CreatureConstants.Arrowhawk_Adult, CreatureConstants.Templates.HalfDragon_Copper, false)]
        [TestCase(CreatureConstants.Arrowhawk_Adult, CreatureConstants.Templates.HalfDragon_Gold, false)]
        [TestCase(CreatureConstants.Arrowhawk_Adult, CreatureConstants.Templates.HalfDragon_Green, false)]
        [TestCase(CreatureConstants.Arrowhawk_Adult, CreatureConstants.Templates.HalfDragon_Red, false)]
        [TestCase(CreatureConstants.Arrowhawk_Adult, CreatureConstants.Templates.HalfDragon_Silver, false)]
        [TestCase(CreatureConstants.Arrowhawk_Adult, CreatureConstants.Templates.HalfDragon_White, false)]
        [TestCase(CreatureConstants.Arrowhawk_Juvenile, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Arrowhawk_Juvenile, CreatureConstants.Templates.HalfDragon_Black, false)]
        [TestCase(CreatureConstants.Arrowhawk_Juvenile, CreatureConstants.Templates.HalfDragon_Blue, false)]
        [TestCase(CreatureConstants.Arrowhawk_Juvenile, CreatureConstants.Templates.HalfDragon_Brass, false)]
        [TestCase(CreatureConstants.Arrowhawk_Juvenile, CreatureConstants.Templates.HalfDragon_Bronze, false)]
        [TestCase(CreatureConstants.Arrowhawk_Juvenile, CreatureConstants.Templates.HalfDragon_Copper, false)]
        [TestCase(CreatureConstants.Arrowhawk_Juvenile, CreatureConstants.Templates.HalfDragon_Gold, false)]
        [TestCase(CreatureConstants.Arrowhawk_Juvenile, CreatureConstants.Templates.HalfDragon_Green, false)]
        [TestCase(CreatureConstants.Arrowhawk_Juvenile, CreatureConstants.Templates.HalfDragon_Red, false)]
        [TestCase(CreatureConstants.Arrowhawk_Juvenile, CreatureConstants.Templates.HalfDragon_Silver, false)]
        [TestCase(CreatureConstants.Arrowhawk_Juvenile, CreatureConstants.Templates.HalfDragon_White, false)]
        [TestCase(CreatureConstants.Arrowhawk_Elder, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Arrowhawk_Elder, CreatureConstants.Templates.HalfDragon_Black, false)]
        [TestCase(CreatureConstants.Arrowhawk_Elder, CreatureConstants.Templates.HalfDragon_Blue, false)]
        [TestCase(CreatureConstants.Arrowhawk_Elder, CreatureConstants.Templates.HalfDragon_Brass, false)]
        [TestCase(CreatureConstants.Arrowhawk_Elder, CreatureConstants.Templates.HalfDragon_Bronze, false)]
        [TestCase(CreatureConstants.Arrowhawk_Elder, CreatureConstants.Templates.HalfDragon_Copper, false)]
        [TestCase(CreatureConstants.Arrowhawk_Elder, CreatureConstants.Templates.HalfDragon_Gold, false)]
        [TestCase(CreatureConstants.Arrowhawk_Elder, CreatureConstants.Templates.HalfDragon_Green, false)]
        [TestCase(CreatureConstants.Arrowhawk_Elder, CreatureConstants.Templates.HalfDragon_Red, false)]
        [TestCase(CreatureConstants.Arrowhawk_Elder, CreatureConstants.Templates.HalfDragon_Silver, false)]
        [TestCase(CreatureConstants.Arrowhawk_Elder, CreatureConstants.Templates.HalfDragon_White, false)]
        [TestCase(CreatureConstants.Badger, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Badger, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Badger_Dire, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Badger_Dire, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Bat, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Bat, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Bat, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Bat_Dire, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Bat_Dire, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Bat_Dire, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Bat_Swarm, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Bat_Swarm, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Bat_Swarm, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Bear_Black, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Bear_Black, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Bear_Brown, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Bear_Brown, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Bear_Polar, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Bear_Polar, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Bear_Dire, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Bear_Dire, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Bee_Giant, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Bee_Giant, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Bison, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Bison, CreatureConstants.Templates.Ghost, false)] //INFO: Charisma too low
        [TestCase(CreatureConstants.Bison, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Boar, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Boar, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Boar_Dire, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Boar_Dire, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.BombardierBeetle_Giant, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.BombardierBeetle_Giant, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Bugbear, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Bugbear, CreatureConstants.Templates.Zombie, true)]
        [TestCase(CreatureConstants.Cat, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Cat, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Cat, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Tiny, CreatureConstants.Templates.Lycanthrope_Rat_Dire_Afflicted, false)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Tiny, CreatureConstants.Templates.Lycanthrope_Rat_Dire_Natural, false)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Tiny, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Tiny, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Small, CreatureConstants.Templates.Lycanthrope_Rat_Dire_Afflicted, false)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Small, CreatureConstants.Templates.Lycanthrope_Rat_Dire_Natural, false)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Small, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Small, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Medium, CreatureConstants.Templates.Lycanthrope_Rat_Dire_Afflicted, false)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Medium, CreatureConstants.Templates.Lycanthrope_Rat_Dire_Natural, false)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Medium, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Medium, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Large, CreatureConstants.Templates.Lycanthrope_Rat_Dire_Afflicted, false)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Large, CreatureConstants.Templates.Lycanthrope_Rat_Dire_Natural, false)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Large, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Large, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Huge, CreatureConstants.Templates.Lycanthrope_Rat_Dire_Afflicted, false)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Huge, CreatureConstants.Templates.Lycanthrope_Rat_Dire_Natural, false)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Huge, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Huge, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Gargantuan, CreatureConstants.Templates.Lycanthrope_Rat_Dire_Afflicted, false)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Gargantuan, CreatureConstants.Templates.Lycanthrope_Rat_Dire_Natural, false)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Gargantuan, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Gargantuan, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Colossal, CreatureConstants.Templates.Lycanthrope_Rat_Dire_Afflicted, false)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Colossal, CreatureConstants.Templates.Lycanthrope_Rat_Dire_Natural, false)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Colossal, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Colossal, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Chimera_Black, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Chimera_Black, CreatureConstants.Templates.Skeleton, true)]
        [TestCase(CreatureConstants.Chimera_Blue, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Chimera_Blue, CreatureConstants.Templates.Skeleton, true)]
        [TestCase(CreatureConstants.Chimera_Green, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Chimera_Green, CreatureConstants.Templates.Skeleton, true)]
        [TestCase(CreatureConstants.Chimera_Red, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Chimera_Red, CreatureConstants.Templates.Skeleton, true)]
        [TestCase(CreatureConstants.Chimera_White, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Chimera_White, CreatureConstants.Templates.Skeleton, true)]
        [TestCase(CreatureConstants.Crocodile, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Crocodile, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Crocodile_Giant, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Crocodile_Giant, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Deinonychus, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Deinonychus, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Djinni, CreatureConstants.Templates.Ghost, false)]
        [TestCase(CreatureConstants.Djinni, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Djinni_Noble, CreatureConstants.Templates.Ghost, false)]
        [TestCase(CreatureConstants.Djinni_Noble, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Dog, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Dog, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Dog_Riding, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Dog_Riding, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Dragon_Red_Wyrmling, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Dragon_Red_Wyrmling, CreatureConstants.Templates.Skeleton, true)]
        [TestCase(CreatureConstants.Dragon_Red_VeryYoung, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Dragon_Red_VeryYoung, CreatureConstants.Templates.Skeleton, true)]
        [TestCase(CreatureConstants.Dragon_Red_Young, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Dragon_Red_Young, CreatureConstants.Templates.Skeleton, true)]
        [TestCase(CreatureConstants.Dragon_Red_Juvenile, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Dragon_Red_Juvenile, CreatureConstants.Templates.Skeleton, true)]
        [TestCase(CreatureConstants.Dragon_Red_YoungAdult, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Dragon_Red_YoungAdult, CreatureConstants.Templates.Skeleton, true)]
        [TestCase(CreatureConstants.Dragon_Red_Adult, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Dragon_Red_Adult, CreatureConstants.Templates.Skeleton, false)]
        [TestCase(CreatureConstants.Dragon_Red_MatureAdult, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Dragon_Red_MatureAdult, CreatureConstants.Templates.Skeleton, false)]
        [TestCase(CreatureConstants.Dragon_Red_Old, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Dragon_Red_Old, CreatureConstants.Templates.Skeleton, false)]
        [TestCase(CreatureConstants.Dragon_Red_VeryOld, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Dragon_Red_VeryOld, CreatureConstants.Templates.Skeleton, false)]
        [TestCase(CreatureConstants.Dragon_Red_Ancient, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Dragon_Red_Ancient, CreatureConstants.Templates.Skeleton, false)]
        [TestCase(CreatureConstants.Dragon_Red_Wyrm, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Dragon_Red_Wyrm, CreatureConstants.Templates.Skeleton, false)]
        [TestCase(CreatureConstants.Dragon_Red_GreatWyrm, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Dragon_Red_GreatWyrm, CreatureConstants.Templates.Skeleton, false)]
        [TestCase(CreatureConstants.Eagle, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Eagle, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Eagle_Giant, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Eagle_Giant, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Efreeti, CreatureConstants.Templates.Ghost, false)]
        [TestCase(CreatureConstants.Efreeti, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Elasmosaurus, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Elasmosaurus, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Elf_Drow, CreatureConstants.Templates.CelestialCreature, false)]
        [TestCase(CreatureConstants.Elf_Drow, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Elf_Drow, CreatureConstants.Templates.HalfCelestial, false)]
        [TestCase(CreatureConstants.Elf_Drow, CreatureConstants.Templates.HalfFiend, true)]
        [TestCase(CreatureConstants.Elf_Drow, CreatureConstants.Templates.Lich, true)]
        [TestCase(CreatureConstants.Elf_Drow, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Elf_Half, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Elf_Half, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Elf_Half, CreatureConstants.Templates.HalfCelestial, true)]
        [TestCase(CreatureConstants.Elf_Half, CreatureConstants.Templates.HalfFiend, true)]
        [TestCase(CreatureConstants.Elf_Half, CreatureConstants.Templates.Lich, true)]
        [TestCase(CreatureConstants.Elf_Half, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Elf_Half, CreatureConstants.Templates.Vampire, true)]
        [TestCase(CreatureConstants.Elf_High, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Elf_High, CreatureConstants.Templates.FiendishCreature, false)]
        [TestCase(CreatureConstants.Elf_High, CreatureConstants.Templates.HalfCelestial, true)]
        [TestCase(CreatureConstants.Elf_High, CreatureConstants.Templates.HalfFiend, false)]
        [TestCase(CreatureConstants.Elf_High, CreatureConstants.Templates.Lich, true)]
        [TestCase(CreatureConstants.Elf_High, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Ettin, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Ettin, CreatureConstants.Templates.Skeleton, true)]
        [TestCase(CreatureConstants.FireBeetle_Giant, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.FireBeetle_Giant, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Giant_Cloud, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Giant_Cloud, CreatureConstants.Templates.Skeleton, true)]
        [TestCase(CreatureConstants.Giant_Fire, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Giant_Fire, CreatureConstants.Templates.Vampire, false)]
        [TestCase(CreatureConstants.Giant_Hill, CreatureConstants.Templates.Lycanthrope_Boar_Dire_Afflicted, true)]
        [TestCase(CreatureConstants.Giant_Hill, CreatureConstants.Templates.Lycanthrope_Boar_Dire_Natural, true)]
        [TestCase(CreatureConstants.Giant_Hill, CreatureConstants.Templates.Lycanthrope_Rat_Dire_Afflicted, false)]
        [TestCase(CreatureConstants.Giant_Hill, CreatureConstants.Templates.Lycanthrope_Rat_Dire_Natural, false)]
        [TestCase(CreatureConstants.Giant_Hill, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Girallon, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Girallon, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.GrayRender, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.GrayRender, CreatureConstants.Templates.Zombie, true)]
        [TestCase(CreatureConstants.Griffon, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Griffon, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Grig, CreatureConstants.Templates.HalfCelestial, true)]
        [TestCase(CreatureConstants.Grig, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Grig_WithFiddle, CreatureConstants.Templates.HalfCelestial, true)]
        [TestCase(CreatureConstants.Grig_WithFiddle, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Hawk, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Hawk, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Hawk, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Hippogriff, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Hippogriff, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Horse_Heavy, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Horse_Heavy, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Horse_Heavy_War, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Horse_Heavy_War, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Horse_Light, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Horse_Light, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Horse_Light_War, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Horse_Light_War, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.Ghost, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.HalfCelestial, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.HalfDragon_Black, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.HalfFiend, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.Lich, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.Lycanthrope_Bear_Brown_Afflicted, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.Lycanthrope_Bear_Brown_Natural, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.Lycanthrope_Boar_Afflicted, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.Lycanthrope_Boar_Natural, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.Lycanthrope_Rat_Dire_Afflicted, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.Lycanthrope_Rat_Dire_Natural, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.Lycanthrope_Tiger_Afflicted, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.Lycanthrope_Tiger_Natural, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.Lycanthrope_Wolf_Afflicted, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.Lycanthrope_Wolf_Natural, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.Lycanthrope_Wolf_Dire_Afflicted, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.Lycanthrope_Wolf_Dire_Natural, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.Skeleton, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.Vampire, true)]
        [TestCase(CreatureConstants.Human, CreatureConstants.Templates.Zombie, true)]
        [TestCase(CreatureConstants.Kobold, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Kobold, CreatureConstants.Templates.Zombie, true)]
        [TestCase(CreatureConstants.Janni, CreatureConstants.Templates.Ghost, false)]
        [TestCase(CreatureConstants.Janni, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Lammasu, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Lammasu, CreatureConstants.Templates.HalfDragon_Gold, true)]
        [TestCase(CreatureConstants.Lammasu, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Lion, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Lion, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Lion_Dire, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Lion_Dire, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Lizard, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Lizard, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Lizard, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Megaraptor, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Megaraptor, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Megaraptor, CreatureConstants.Templates.Skeleton, true)]
        [TestCase(CreatureConstants.Mephit_Fire, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Mephit_Fire, CreatureConstants.Templates.HalfDragon_Black, false)]
        [TestCase(CreatureConstants.Mephit_Fire, CreatureConstants.Templates.HalfDragon_Blue, false)]
        [TestCase(CreatureConstants.Mephit_Fire, CreatureConstants.Templates.HalfDragon_Brass, false)]
        [TestCase(CreatureConstants.Mephit_Fire, CreatureConstants.Templates.HalfDragon_Bronze, false)]
        [TestCase(CreatureConstants.Mephit_Fire, CreatureConstants.Templates.HalfDragon_Copper, false)]
        [TestCase(CreatureConstants.Mephit_Fire, CreatureConstants.Templates.HalfDragon_Gold, false)]
        [TestCase(CreatureConstants.Mephit_Fire, CreatureConstants.Templates.HalfDragon_Green, false)]
        [TestCase(CreatureConstants.Mephit_Fire, CreatureConstants.Templates.HalfDragon_Red, false)]
        [TestCase(CreatureConstants.Mephit_Fire, CreatureConstants.Templates.HalfDragon_Silver, false)]
        [TestCase(CreatureConstants.Mephit_Fire, CreatureConstants.Templates.HalfDragon_White, false)]
        [TestCase(CreatureConstants.Mephit_Ice, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Mephit_Ice, CreatureConstants.Templates.HalfDragon_Black, false)]
        [TestCase(CreatureConstants.Mephit_Ice, CreatureConstants.Templates.HalfDragon_Blue, false)]
        [TestCase(CreatureConstants.Mephit_Ice, CreatureConstants.Templates.HalfDragon_Brass, false)]
        [TestCase(CreatureConstants.Mephit_Ice, CreatureConstants.Templates.HalfDragon_Bronze, false)]
        [TestCase(CreatureConstants.Mephit_Ice, CreatureConstants.Templates.HalfDragon_Copper, false)]
        [TestCase(CreatureConstants.Mephit_Ice, CreatureConstants.Templates.HalfDragon_Gold, false)]
        [TestCase(CreatureConstants.Mephit_Ice, CreatureConstants.Templates.HalfDragon_Green, false)]
        [TestCase(CreatureConstants.Mephit_Ice, CreatureConstants.Templates.HalfDragon_Red, false)]
        [TestCase(CreatureConstants.Mephit_Ice, CreatureConstants.Templates.HalfDragon_Silver, false)]
        [TestCase(CreatureConstants.Mephit_Ice, CreatureConstants.Templates.HalfDragon_White, false)]
        [TestCase(CreatureConstants.Mephit_Magma, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Mephit_Magma, CreatureConstants.Templates.HalfDragon_Black, false)]
        [TestCase(CreatureConstants.Mephit_Magma, CreatureConstants.Templates.HalfDragon_Blue, false)]
        [TestCase(CreatureConstants.Mephit_Magma, CreatureConstants.Templates.HalfDragon_Brass, false)]
        [TestCase(CreatureConstants.Mephit_Magma, CreatureConstants.Templates.HalfDragon_Bronze, false)]
        [TestCase(CreatureConstants.Mephit_Magma, CreatureConstants.Templates.HalfDragon_Copper, false)]
        [TestCase(CreatureConstants.Mephit_Magma, CreatureConstants.Templates.HalfDragon_Gold, false)]
        [TestCase(CreatureConstants.Mephit_Magma, CreatureConstants.Templates.HalfDragon_Green, false)]
        [TestCase(CreatureConstants.Mephit_Magma, CreatureConstants.Templates.HalfDragon_Red, false)]
        [TestCase(CreatureConstants.Mephit_Magma, CreatureConstants.Templates.HalfDragon_Silver, false)]
        [TestCase(CreatureConstants.Mephit_Magma, CreatureConstants.Templates.HalfDragon_White, false)]
        [TestCase(CreatureConstants.Mephit_Steam, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Mephit_Steam, CreatureConstants.Templates.HalfDragon_Black, false)]
        [TestCase(CreatureConstants.Mephit_Steam, CreatureConstants.Templates.HalfDragon_Blue, false)]
        [TestCase(CreatureConstants.Mephit_Steam, CreatureConstants.Templates.HalfDragon_Brass, false)]
        [TestCase(CreatureConstants.Mephit_Steam, CreatureConstants.Templates.HalfDragon_Bronze, false)]
        [TestCase(CreatureConstants.Mephit_Steam, CreatureConstants.Templates.HalfDragon_Copper, false)]
        [TestCase(CreatureConstants.Mephit_Steam, CreatureConstants.Templates.HalfDragon_Gold, false)]
        [TestCase(CreatureConstants.Mephit_Steam, CreatureConstants.Templates.HalfDragon_Green, false)]
        [TestCase(CreatureConstants.Mephit_Steam, CreatureConstants.Templates.HalfDragon_Red, false)]
        [TestCase(CreatureConstants.Mephit_Steam, CreatureConstants.Templates.HalfDragon_Silver, false)]
        [TestCase(CreatureConstants.Mephit_Steam, CreatureConstants.Templates.HalfDragon_White, false)]
        [TestCase(CreatureConstants.MindFlayer, CreatureConstants.Templates.Lich, false)]
        [TestCase(CreatureConstants.MindFlayer, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.MindFlayer, CreatureConstants.Templates.Vampire, false)]
        [TestCase(CreatureConstants.Minotaur, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Minotaur, CreatureConstants.Templates.Zombie, true)]
        [TestCase(CreatureConstants.Monkey, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Monkey, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Octopus, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Octopus, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Octopus_Giant, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Octopus_Giant, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Ogre, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Ogre, CreatureConstants.Templates.Zombie, true)]
        [TestCase(CreatureConstants.Orc, CreatureConstants.Templates.CelestialCreature, false)]
        [TestCase(CreatureConstants.Orc, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Orc, CreatureConstants.Templates.HalfCelestial, false)]
        [TestCase(CreatureConstants.Orc, CreatureConstants.Templates.HalfFiend, true)]
        [TestCase(CreatureConstants.Orc, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Orc_Half, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Orc_Half, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Orc_Half, CreatureConstants.Templates.HalfCelestial, true)]
        [TestCase(CreatureConstants.Orc_Half, CreatureConstants.Templates.HalfFiend, true)]
        [TestCase(CreatureConstants.Orc_Half, CreatureConstants.Templates.Lich, true)]
        [TestCase(CreatureConstants.Orc_Half, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Owl, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Owl, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Owl, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Owl_Giant, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Owl_Giant, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Owlbear, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Owlbear, CreatureConstants.Templates.Skeleton, true)]
        [TestCase(CreatureConstants.Pony, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Pony, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Pony_War, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Pony_War, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Porpoise, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Porpoise, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.PrayingMantis_Giant, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.PrayingMantis_Giant, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Rat, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Rat, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Rat, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Rat_Dire, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Rat_Dire, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Raven, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Raven, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Raven, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Rhinoceras, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Rhinoceras, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Roc, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Roc, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Small, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Small, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Medium, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Medium, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Large, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Large, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Huge, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Huge, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Gargantuan, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Gargantuan, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.SeaCat, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.SeaCat, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Shark_Dire, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Shark_Dire, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Shark_Huge, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Shark_Huge, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Shark_Large, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Shark_Large, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Shark_Large, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Shark_Medium, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Shark_Medium, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Snake_Constrictor, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Snake_Constrictor, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Snake_Constrictor, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Snake_Constrictor_Giant, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Snake_Constrictor_Giant, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Snake_Constrictor_Giant, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Snake_Viper_Tiny, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Snake_Viper_Tiny, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Snake_Viper_Tiny, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Snake_Viper_Small, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Snake_Viper_Small, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Snake_Viper_Small, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Snake_Viper_Medium, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Snake_Viper_Medium, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Snake_Viper_Medium, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Snake_Viper_Large, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Snake_Viper_Large, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Snake_Viper_Large, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Snake_Viper_Huge, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Snake_Viper_Huge, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Snake_Viper_Huge, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Small, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Small, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Small, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Small, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Medium, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Medium, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Medium, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Medium, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Large, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Large, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Large, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Large, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Huge, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Huge, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Huge, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Huge, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Gargantuan, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Gargantuan, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Gargantuan, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Gargantuan, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Colossal, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Colossal, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Colossal, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Colossal, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Squid, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Squid, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Squid_Giant, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Squid_Giant, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Squid_Giant, CreatureConstants.Templates.HalfDragon_Blue, true)]
        [TestCase(CreatureConstants.Squid_Giant, CreatureConstants.Templates.HalfDragon_Green, true)]
        [TestCase(CreatureConstants.StagBeetle_Giant, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.StagBeetle_Giant, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Tiger, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Tiger, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Tiger_Dire, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Tiger_Dire, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Toad, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Toad, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Toad, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Triceratops, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Triceratops, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Troglodyte, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Troglodyte, CreatureConstants.Templates.Zombie, true)]
        [TestCase(CreatureConstants.Troll, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Troll, CreatureConstants.Templates.Skeleton, true)]
        [TestCase(CreatureConstants.Tyrannosaurus, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Tyrannosaurus, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Unicorn, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Unicorn, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Wasp_Giant, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Wasp_Giant, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Weasel, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Weasel, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Weasel, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Weasel_Dire, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Weasel_Dire, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Whale_Baleen, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Whale_Baleen, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Whale_Cachalot, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Whale_Cachalot, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Whale_Orca, CreatureConstants.Templates.CelestialCreature, true)]
        [TestCase(CreatureConstants.Whale_Orca, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Wolf, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Wolf, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Wolf, CreatureConstants.Templates.Skeleton, true)]
        [TestCase(CreatureConstants.Wolf_Dire, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Wolf_Dire, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Wolverine, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Wolverine, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Wolverine_Dire, CreatureConstants.Templates.FiendishCreature, true)]
        [TestCase(CreatureConstants.Wolverine_Dire, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Wyvern, CreatureConstants.Templates.None, true)]
        [TestCase(CreatureConstants.Wyvern, CreatureConstants.Templates.Zombie, true)]
        public void CreatureVerificationIsFast(string creatureName, string templateName, bool isValid)
        {
            stopwatch.Restart();
            var verified = creatureVerifier.VerifyCompatibility(creatureName, templateName);
            stopwatch.Stop();

            Assert.That(verified, Is.EqualTo(isValid));
            Assert.That(stopwatch.Elapsed, Is.LessThan(timeLimit));
        }

        [TestCase(CreatureConstants.Aasimar, true)]
        [TestCase(CreatureConstants.Ape, false)]
        [TestCase(CreatureConstants.Ape_Dire, false)]
        [TestCase(CreatureConstants.Azer, true)]
        [TestCase(CreatureConstants.Badger, false)]
        [TestCase(CreatureConstants.Badger_Dire, false)]
        [TestCase(CreatureConstants.Bat, false)]
        [TestCase(CreatureConstants.Bat_Dire, false)]
        [TestCase(CreatureConstants.Bat_Swarm, false)]
        [TestCase(CreatureConstants.Bear_Black, false)]
        [TestCase(CreatureConstants.Bear_Brown, false)]
        [TestCase(CreatureConstants.Bear_Dire, false)]
        [TestCase(CreatureConstants.Bear_Polar, false)]
        [TestCase(CreatureConstants.Bison, false)]
        [TestCase(CreatureConstants.Boar, false)]
        [TestCase(CreatureConstants.Boar_Dire, false)]
        [TestCase(CreatureConstants.Bugbear, true)]
        [TestCase(CreatureConstants.Camel_Bactrian, false)]
        [TestCase(CreatureConstants.Camel_Dromedary, false)]
        [TestCase(CreatureConstants.Cat, false)]
        [TestCase(CreatureConstants.Centaur, true)]
        [TestCase(CreatureConstants.Cheetah, false)]
        [TestCase(CreatureConstants.Deinonychus, false)]
        [TestCase(CreatureConstants.Derro, true)]
        [TestCase(CreatureConstants.Derro_Sane, true)]
        [TestCase(CreatureConstants.Dog, false)]
        [TestCase(CreatureConstants.Dog_Riding, false)]
        [TestCase(CreatureConstants.Doppelganger, true)]
        [TestCase(CreatureConstants.Dwarf_Deep, true)]
        [TestCase(CreatureConstants.Dwarf_Duergar, true)]
        [TestCase(CreatureConstants.Dwarf_Hill, true)]
        [TestCase(CreatureConstants.Dwarf_Mountain, true)]
        [TestCase(CreatureConstants.Eagle, false)]
        [TestCase(CreatureConstants.Eagle_Giant, false)]
        [TestCase(CreatureConstants.Elemental_Air_Elder, false)]
        [TestCase(CreatureConstants.Elemental_Air_Greater, false)]
        [TestCase(CreatureConstants.Elemental_Air_Huge, false)]
        [TestCase(CreatureConstants.Elemental_Air_Large, false)]
        [TestCase(CreatureConstants.Elemental_Air_Medium, false)]
        [TestCase(CreatureConstants.Elemental_Air_Small, false)]
        [TestCase(CreatureConstants.Elemental_Earth_Elder, false)]
        [TestCase(CreatureConstants.Elemental_Earth_Greater, false)]
        [TestCase(CreatureConstants.Elemental_Earth_Huge, false)]
        [TestCase(CreatureConstants.Elemental_Earth_Large, false)]
        [TestCase(CreatureConstants.Elemental_Earth_Medium, false)]
        [TestCase(CreatureConstants.Elemental_Earth_Small, false)]
        [TestCase(CreatureConstants.Elemental_Fire_Elder, false)]
        [TestCase(CreatureConstants.Elemental_Fire_Greater, false)]
        [TestCase(CreatureConstants.Elemental_Fire_Huge, false)]
        [TestCase(CreatureConstants.Elemental_Fire_Large, false)]
        [TestCase(CreatureConstants.Elemental_Fire_Medium, false)]
        [TestCase(CreatureConstants.Elemental_Fire_Small, false)]
        [TestCase(CreatureConstants.Elemental_Water_Elder, false)]
        [TestCase(CreatureConstants.Elemental_Water_Greater, false)]
        [TestCase(CreatureConstants.Elemental_Water_Huge, false)]
        [TestCase(CreatureConstants.Elemental_Water_Large, false)]
        [TestCase(CreatureConstants.Elemental_Water_Medium, false)]
        [TestCase(CreatureConstants.Elemental_Water_Small, false)]
        [TestCase(CreatureConstants.Elephant, false)]
        [TestCase(CreatureConstants.Elf_Aquatic, true)]
        [TestCase(CreatureConstants.Elf_Drow, true)]
        [TestCase(CreatureConstants.Elf_Gray, true)]
        [TestCase(CreatureConstants.Elf_Half, true)]
        [TestCase(CreatureConstants.Elf_High, true)]
        [TestCase(CreatureConstants.Elf_Wild, true)]
        [TestCase(CreatureConstants.Elf_Wood, true)]
        [TestCase(CreatureConstants.FormianWorker, false)]
        [TestCase(CreatureConstants.Gargoyle, true)]
        [TestCase(CreatureConstants.Gargoyle_Kapoacinth, true)]
        [TestCase(CreatureConstants.Giant_Cloud, true)]
        [TestCase(CreatureConstants.Giant_Fire, true)]
        [TestCase(CreatureConstants.Giant_Frost, true)]
        [TestCase(CreatureConstants.Giant_Hill, true)]
        [TestCase(CreatureConstants.Giant_Stone, true)]
        [TestCase(CreatureConstants.Giant_Stone_Elder, true)]
        [TestCase(CreatureConstants.Giant_Storm, true)]
        [TestCase(CreatureConstants.Githyanki, true)]
        [TestCase(CreatureConstants.Githzerai, true)]
        [TestCase(CreatureConstants.Gnoll, true)]
        [TestCase(CreatureConstants.Gnome_Forest, true)]
        [TestCase(CreatureConstants.Gnome_Rock, true)]
        [TestCase(CreatureConstants.Gnome_Svirfneblin, true)]
        [TestCase(CreatureConstants.Goblin, true)]
        [TestCase(CreatureConstants.Grimlock, true)]
        [TestCase(CreatureConstants.Halfling_Deep, true)]
        [TestCase(CreatureConstants.Halfling_Lightfoot, true)]
        [TestCase(CreatureConstants.Halfling_Tallfellow, true)]
        [TestCase(CreatureConstants.Harpy, true)]
        [TestCase(CreatureConstants.Hawk, false)]
        [TestCase(CreatureConstants.Hobgoblin, true)]
        [TestCase(CreatureConstants.Homunculus, false)]
        [TestCase(CreatureConstants.Horse_Heavy, false)]
        [TestCase(CreatureConstants.Horse_Heavy_War, false)]
        [TestCase(CreatureConstants.Horse_Light, false)]
        [TestCase(CreatureConstants.Horse_Light_War, false)]
        [TestCase(CreatureConstants.HoundArchon, true)]
        [TestCase(CreatureConstants.Human, true)]
        [TestCase(CreatureConstants.Imp, false)]
        [TestCase(CreatureConstants.Janni, true)]
        [TestCase(CreatureConstants.Kobold, true)]
        [TestCase(CreatureConstants.KuoToa, true)]
        [TestCase(CreatureConstants.Leopard, false)]
        [TestCase(CreatureConstants.Lion, false)]
        [TestCase(CreatureConstants.Lion_Dire, false)]
        [TestCase(CreatureConstants.Lizardfolk, true)]
        [TestCase(CreatureConstants.Lizard, false)]
        [TestCase(CreatureConstants.Lizard_Monitor, false)]
        [TestCase(CreatureConstants.Locathah, true)]
        [TestCase(CreatureConstants.Megaraptor, false)]
        [TestCase(CreatureConstants.Mephit_Air, false)]
        [TestCase(CreatureConstants.Mephit_Dust, false)]
        [TestCase(CreatureConstants.Mephit_Earth, false)]
        [TestCase(CreatureConstants.Mephit_Fire, false)]
        [TestCase(CreatureConstants.Mephit_Ice, false)]
        [TestCase(CreatureConstants.Mephit_Magma, false)]
        [TestCase(CreatureConstants.Mephit_Ooze, false)]
        [TestCase(CreatureConstants.Mephit_Salt, false)]
        [TestCase(CreatureConstants.Mephit_Steam, false)]
        [TestCase(CreatureConstants.Mephit_Water, false)]
        [TestCase(CreatureConstants.Merfolk, true)]
        [TestCase(CreatureConstants.MindFlayer, true)]
        [TestCase(CreatureConstants.Minotaur, true)]
        [TestCase(CreatureConstants.Mummy, true)]
        [TestCase(CreatureConstants.Ogre, true)]
        [TestCase(CreatureConstants.OgreMage, true)]
        [TestCase(CreatureConstants.Ogre_Merrow, true)]
        [TestCase(CreatureConstants.Orc, true)]
        [TestCase(CreatureConstants.Orc_Half, true)]
        [TestCase(CreatureConstants.Owl, false)]
        [TestCase(CreatureConstants.Owlbear, false)]
        [TestCase(CreatureConstants.Owl_Giant, false)]
        [TestCase(CreatureConstants.Pixie, true)]
        [TestCase(CreatureConstants.Pixie_WithIrresistibleDance, true)]
        [TestCase(CreatureConstants.Pony, false)]
        [TestCase(CreatureConstants.Pony_War, false)]
        [TestCase(CreatureConstants.Pseudodragon, false)]
        [TestCase(CreatureConstants.Quasit, false)]
        [TestCase(CreatureConstants.Rakshasa, true)]
        [TestCase(CreatureConstants.Rat, false)]
        [TestCase(CreatureConstants.Rat_Dire, false)]
        [TestCase(CreatureConstants.Rat_Swarm, false)]
        [TestCase(CreatureConstants.Raven, false)]
        [TestCase(CreatureConstants.Rhinoceras, false)]
        [TestCase(CreatureConstants.Sahuagin, true)]
        [TestCase(CreatureConstants.Sahuagin_Malenti, true)]
        [TestCase(CreatureConstants.Sahuagin_Mutant, true)]
        [TestCase(CreatureConstants.Satyr, true)]
        [TestCase(CreatureConstants.Satyr_WithPipes, true)]
        [TestCase(CreatureConstants.ShockerLizard, false)]
        [TestCase(CreatureConstants.Slaad_Blue, true)]
        [TestCase(CreatureConstants.Slaad_Death, true)]
        [TestCase(CreatureConstants.Slaad_Gray, true)]
        [TestCase(CreatureConstants.Slaad_Green, true)]
        [TestCase(CreatureConstants.Slaad_Red, true)]
        [TestCase(CreatureConstants.Snake_Constrictor, false)]
        [TestCase(CreatureConstants.Snake_Constrictor_Giant, false)]
        [TestCase(CreatureConstants.Snake_Viper_Huge, false)]
        [TestCase(CreatureConstants.Snake_Viper_Large, false)]
        [TestCase(CreatureConstants.Snake_Viper_Medium, false)]
        [TestCase(CreatureConstants.Snake_Viper_Small, false)]
        [TestCase(CreatureConstants.Snake_Viper_Tiny, false)]
        [TestCase(CreatureConstants.Stirge, false)]
        [TestCase(CreatureConstants.Tiefling, true)]
        [TestCase(CreatureConstants.Tiger, false)]
        [TestCase(CreatureConstants.Tiger_Dire, false)]
        [TestCase(CreatureConstants.Toad, false)]
        [TestCase(CreatureConstants.Triceratops, false)]
        [TestCase(CreatureConstants.Troglodyte, true)]
        [TestCase(CreatureConstants.Troll, true)]
        [TestCase(CreatureConstants.Troll_Scrag, true)]
        [TestCase(CreatureConstants.Tyrannosaurus, false)]
        [TestCase(CreatureConstants.Unicorn, true)]
        [TestCase(CreatureConstants.Weasel, false)]
        [TestCase(CreatureConstants.Weasel_Dire, false)]
        [TestCase(CreatureConstants.Wolf, false)]
        [TestCase(CreatureConstants.Wolf_Dire, false)]
        [TestCase(CreatureConstants.Wolverine, false)]
        [TestCase(CreatureConstants.Wolverine_Dire, false)]
        [TestCase(CreatureConstants.YuanTi_Abomination, true)]
        [TestCase(CreatureConstants.YuanTi_Halfblood_SnakeArms, true)]
        [TestCase(CreatureConstants.YuanTi_Halfblood_SnakeHead, true)]
        [TestCase(CreatureConstants.YuanTi_Halfblood_SnakeTail, true)]
        [TestCase(CreatureConstants.YuanTi_Halfblood_SnakeTailAndHumanLegs, true)]
        [TestCase(CreatureConstants.YuanTi_Pureblood, true)]
        public void CreatureCanBeCharacter(string creature, bool canBeCharacter)
        {
            var isCharacter = creatureVerifier.CanBeCharacter(creature);
            Assert.That(isCharacter, Is.EqualTo(canBeCharacter));

            var characterCreatures = creatureVerifier.CanBeCharacter();
            if (canBeCharacter)
                Assert.That(characterCreatures, Contains.Item(creature));
            else
                Assert.That(characterCreatures, Does.Not.Contain(creature));
        }
    }
}
