using DnDGen.CreatureGen.Creatures;
using DnDGen.CreatureGen.Selectors.Collections;
using DnDGen.CreatureGen.Tests.Integration.TestData;
using DnDGen.Infrastructure.Selectors.Collections;
using NUnit.Framework;
using System.Linq;

namespace DnDGen.CreatureGen.Tests.Integration.Tables.Creatures.CreatureGroups
{
    [TestFixture]
    public class CreatureChallengeRatingGroupsTests : CreatureGroupsTableTests
    {
        private ICreatureDataSelector creatureDataSelector;
        private ICollectionSelector collectionSelector;

        [SetUp]
        public void Setup()
        {
            creatureDataSelector = GetNewInstanceOf<ICreatureDataSelector>();
            collectionSelector = GetNewInstanceOf<ICollectionSelector>();
        }

        [Test]
        public void CreatureGroupNames()
        {
            AssertCreatureGroupNamesAreComplete();
        }

        [TestCase(ChallengeRatingConstants.CR0)]
        [TestCase(ChallengeRatingConstants.CR1_10th,
            CreatureConstants.Bat)]
        [TestCase(ChallengeRatingConstants.CR1_8th)]
        [TestCase(ChallengeRatingConstants.CR1_6th)]
        [TestCase(ChallengeRatingConstants.CR1_4th,
            CreatureConstants.Cat)]
        [TestCase(ChallengeRatingConstants.CR1_3rd,
            CreatureConstants.Rat_Dire)]
        [TestCase(ChallengeRatingConstants.CR1_2nd,
            CreatureConstants.Groups.Planetouched,
            CreatureConstants.AnimatedObject_Anvil_Tiny,
            CreatureConstants.AnimatedObject_Block_Stone_Tiny,
            CreatureConstants.AnimatedObject_Block_Wood_Tiny,
            CreatureConstants.AnimatedObject_Box_Tiny,
            CreatureConstants.AnimatedObject_Carpet_Tiny,
            CreatureConstants.AnimatedObject_Carriage_Tiny,
            CreatureConstants.AnimatedObject_Chain_Tiny,
            CreatureConstants.AnimatedObject_Chair_Tiny,
            CreatureConstants.AnimatedObject_Clothes_Tiny,
            CreatureConstants.AnimatedObject_Ladder_Tiny,
            CreatureConstants.AnimatedObject_Rope_Tiny,
            CreatureConstants.AnimatedObject_Rug_Tiny,
            CreatureConstants.AnimatedObject_Sled_Tiny,
            CreatureConstants.AnimatedObject_Statue_Animal_Tiny,
            CreatureConstants.AnimatedObject_Statue_Humanoid_Tiny,
            CreatureConstants.AnimatedObject_Stool_Tiny,
            CreatureConstants.AnimatedObject_Table_Tiny,
            CreatureConstants.AnimatedObject_Tapestry_Tiny,
            CreatureConstants.AnimatedObject_Wagon_Tiny,
            CreatureConstants.Groups.Elf,
            CreatureConstants.Baboon,
            CreatureConstants.Badger,
            CreatureConstants.Groups.Dwarf,
            CreatureConstants.Groups.Halfling)]
        [TestCase(ChallengeRatingConstants.CR1,
            CreatureConstants.Elemental_Air_Small,
            CreatureConstants.Elemental_Earth_Small,
            CreatureConstants.Elemental_Fire_Small,
            CreatureConstants.Elemental_Water_Small,
            CreatureConstants.AnimatedObject_Anvil_Small,
            CreatureConstants.AnimatedObject_Block_Stone_Small,
            CreatureConstants.AnimatedObject_Block_Wood_Small,
            CreatureConstants.AnimatedObject_Box_Small,
            CreatureConstants.AnimatedObject_Carpet_Small,
            CreatureConstants.AnimatedObject_Carriage_Small,
            CreatureConstants.AnimatedObject_Chain_Small,
            CreatureConstants.AnimatedObject_Chair_Small,
            CreatureConstants.AnimatedObject_Clothes_Small,
            CreatureConstants.AnimatedObject_Ladder_Small,
            CreatureConstants.AnimatedObject_Rope_Small,
            CreatureConstants.AnimatedObject_Rug_Small,
            CreatureConstants.AnimatedObject_Sled_Small,
            CreatureConstants.AnimatedObject_Statue_Animal_Small,
            CreatureConstants.AnimatedObject_Statue_Humanoid_Small,
            CreatureConstants.AnimatedObject_Stool_Small,
            CreatureConstants.AnimatedObject_Table_Small,
            CreatureConstants.AnimatedObject_Tapestry_Small,
            CreatureConstants.AnimatedObject_Wagon_Small,
            CreatureConstants.Camel_Bactrian,
            CreatureConstants.Camel_Dromedary,
            CreatureConstants.Darkmantle)]
        [TestCase(ChallengeRatingConstants.CR2,
            CreatureConstants.AnimatedObject_Anvil_Medium,
            CreatureConstants.AnimatedObject_Block_Stone_Medium,
            CreatureConstants.AnimatedObject_Block_Wood_Medium,
            CreatureConstants.AnimatedObject_Box_Medium,
            CreatureConstants.AnimatedObject_Carpet_Medium,
            CreatureConstants.AnimatedObject_Carriage_Medium,
            CreatureConstants.AnimatedObject_Chain_Medium,
            CreatureConstants.AnimatedObject_Chair_Medium,
            CreatureConstants.AnimatedObject_Clothes_Medium,
            CreatureConstants.AnimatedObject_Ladder_Medium,
            CreatureConstants.AnimatedObject_Rope_Medium,
            CreatureConstants.AnimatedObject_Rug_Medium,
            CreatureConstants.AnimatedObject_Sled_Medium,
            CreatureConstants.AnimatedObject_Statue_Animal_Medium,
            CreatureConstants.AnimatedObject_Statue_Humanoid_Medium,
            CreatureConstants.AnimatedObject_Stool_Medium,
            CreatureConstants.AnimatedObject_Table_Medium,
            CreatureConstants.AnimatedObject_Tapestry_Medium,
            CreatureConstants.AnimatedObject_Wagon_Medium,
            CreatureConstants.Ape,
            CreatureConstants.Azer,
            CreatureConstants.Bat_Swarm,
            CreatureConstants.Bison,
            CreatureConstants.Bear_Black,
            CreatureConstants.BlinkDog,
            CreatureConstants.Boar,
            CreatureConstants.Bugbear,
            CreatureConstants.Cheetah,
            CreatureConstants.Choker,
            CreatureConstants.Snake_Constrictor,
            CreatureConstants.Crocodile,
            CreatureConstants.Badger_Dire,
            CreatureConstants.Bat_Dire,
            CreatureConstants.Weasel_Dire)]
        [TestCase(ChallengeRatingConstants.CR3,
            CreatureConstants.Elemental_Air_Medium,
            CreatureConstants.Elemental_Earth_Medium,
            CreatureConstants.Elemental_Fire_Medium,
            CreatureConstants.Elemental_Water_Medium,
            CreatureConstants.Groups.Mephit,
            CreatureConstants.Allip,
            CreatureConstants.AnimatedObject_Anvil_Large,
            CreatureConstants.AnimatedObject_Block_Stone_Large,
            CreatureConstants.AnimatedObject_Block_Wood_Large,
            CreatureConstants.AnimatedObject_Box_Large,
            CreatureConstants.AnimatedObject_Carpet_Large,
            CreatureConstants.AnimatedObject_Carriage_Large,
            CreatureConstants.AnimatedObject_Chain_Large,
            CreatureConstants.AnimatedObject_Chair_Large,
            CreatureConstants.AnimatedObject_Clothes_Large,
            CreatureConstants.AnimatedObject_Ladder_Large,
            CreatureConstants.AnimatedObject_Rope_Large,
            CreatureConstants.AnimatedObject_Rug_Large,
            CreatureConstants.AnimatedObject_Sled_Large,
            CreatureConstants.AnimatedObject_Statue_Animal_Large,
            CreatureConstants.AnimatedObject_Statue_Humanoid_Large,
            CreatureConstants.AnimatedObject_Stool_Large,
            CreatureConstants.AnimatedObject_Table_Large,
            CreatureConstants.AnimatedObject_Tapestry_Large,
            CreatureConstants.AnimatedObject_Wagon_Large,
            CreatureConstants.Ankheg,
            CreatureConstants.AssassinVine,
            CreatureConstants.Dragon_Black_Wyrmling,
            CreatureConstants.Dragon_Blue_Wyrmling,
            CreatureConstants.Dragon_Brass_Wyrmling,
            CreatureConstants.Dragon_Bronze_Wyrmling,
            CreatureConstants.Centaur,
            CreatureConstants.Cockatrice,
            CreatureConstants.Dragon_Copper_Wyrmling,
            CreatureConstants.Deinonychus,
            CreatureConstants.Derro_Sane,
            CreatureConstants.Derro,
            CreatureConstants.Ape_Dire,
            CreatureConstants.Wolf_Dire)]
        [TestCase(ChallengeRatingConstants.CR4,
            CreatureConstants.Aranea,
            CreatureConstants.Barghest,
            CreatureConstants.Dragon_Black_VeryYoung,
            CreatureConstants.Dragon_Blue_VeryYoung,
            CreatureConstants.Dragon_Brass_VeryYoung,
            CreatureConstants.Bear_Brown,
            CreatureConstants.CarrionCrawler,
            CreatureConstants.Centipede_Swarm,
            CreatureConstants.Boar_Dire,
            CreatureConstants.Wolverine_Dire)]
        [TestCase(ChallengeRatingConstants.CR5,
            CreatureConstants.Achaierai,
            CreatureConstants.Arrowhawk_Adult,
            CreatureConstants.Tojanida_Adult,
            CreatureConstants.Elemental_Air_Large,
            CreatureConstants.Elemental_Earth_Large,
            CreatureConstants.Elemental_Fire_Large,
            CreatureConstants.Elemental_Water_Large,
            CreatureConstants.AnimatedObject_Anvil_Huge,
            CreatureConstants.AnimatedObject_Block_Stone_Huge,
            CreatureConstants.AnimatedObject_Block_Wood_Huge,
            CreatureConstants.AnimatedObject_Box_Huge,
            CreatureConstants.AnimatedObject_Carpet_Huge,
            CreatureConstants.AnimatedObject_Carriage_Huge,
            CreatureConstants.AnimatedObject_Chain_Huge,
            CreatureConstants.AnimatedObject_Chair_Huge,
            CreatureConstants.AnimatedObject_Clothes_Huge,
            CreatureConstants.AnimatedObject_Ladder_Huge,
            CreatureConstants.AnimatedObject_Rope_Huge,
            CreatureConstants.AnimatedObject_Rug_Huge,
            CreatureConstants.AnimatedObject_Sled_Huge,
            CreatureConstants.AnimatedObject_Statue_Animal_Huge,
            CreatureConstants.AnimatedObject_Statue_Humanoid_Huge,
            CreatureConstants.AnimatedObject_Stool_Huge,
            CreatureConstants.AnimatedObject_Table_Huge,
            CreatureConstants.AnimatedObject_Tapestry_Huge,
            CreatureConstants.AnimatedObject_Wagon_Huge,
            CreatureConstants.Basilisk,
            CreatureConstants.BeardedDevil_Barbazu,
            CreatureConstants.Dragon_Black_Young,
            CreatureConstants.Dragon_Bronze_VeryYoung,
            CreatureConstants.Cloaker,
            CreatureConstants.Dragon_Copper_VeryYoung,
            CreatureConstants.Lion_Dire)]
        [TestCase(ChallengeRatingConstants.CR6,
            CreatureConstants.Annis,
            CreatureConstants.Salamander_Average,
            CreatureConstants.Xorn_Average,
            CreatureConstants.Babau,
            CreatureConstants.Whale_Baleen,
            CreatureConstants.Belker,
            CreatureConstants.Dragon_Blue_Young,
            CreatureConstants.Bralani,
            CreatureConstants.Dragon_Brass_Young,
            CreatureConstants.ChainDevil_Kyton,
            CreatureConstants.Digester)]
        [TestCase(ChallengeRatingConstants.CR7,
            CreatureConstants.Aboleth,
            CreatureConstants.Elemental_Air_Huge,
            CreatureConstants.Elemental_Earth_Huge,
            CreatureConstants.Elemental_Fire_Huge,
            CreatureConstants.Elemental_Water_Huge,
            CreatureConstants.AnimatedObject_Anvil_Gargantuan,
            CreatureConstants.AnimatedObject_Block_Stone_Gargantuan,
            CreatureConstants.AnimatedObject_Block_Wood_Gargantuan,
            CreatureConstants.AnimatedObject_Box_Gargantuan,
            CreatureConstants.AnimatedObject_Carpet_Gargantuan,
            CreatureConstants.AnimatedObject_Carriage_Gargantuan,
            CreatureConstants.AnimatedObject_Chain_Gargantuan,
            CreatureConstants.AnimatedObject_Chair_Gargantuan,
            CreatureConstants.AnimatedObject_Clothes_Gargantuan,
            CreatureConstants.AnimatedObject_Ladder_Gargantuan,
            CreatureConstants.AnimatedObject_Rope_Gargantuan,
            CreatureConstants.AnimatedObject_Rug_Gargantuan,
            CreatureConstants.AnimatedObject_Sled_Gargantuan,
            CreatureConstants.AnimatedObject_Statue_Animal_Gargantuan,
            CreatureConstants.AnimatedObject_Statue_Humanoid_Gargantuan,
            CreatureConstants.AnimatedObject_Stool_Gargantuan,
            CreatureConstants.AnimatedObject_Table_Gargantuan,
            CreatureConstants.AnimatedObject_Tapestry_Gargantuan,
            CreatureConstants.AnimatedObject_Wagon_Gargantuan,
            CreatureConstants.Dragon_Black_Juvenile,
            CreatureConstants.BlackPudding,
            CreatureConstants.Dragon_Bronze_Young,
            CreatureConstants.Bulette,
            CreatureConstants.Whale_Cachalot,
            CreatureConstants.ChaosBeast,
            CreatureConstants.Groups.Chimera,
            CreatureConstants.Chuul,
            CreatureConstants.Dragon_Copper_Young,
            CreatureConstants.Criosphinx,
            CreatureConstants.Bear_Dire)]
        [TestCase(ChallengeRatingConstants.CR8,
            CreatureConstants.Athach,
            CreatureConstants.Behir,
            CreatureConstants.Dragon_Blue_Juvenile,
            CreatureConstants.Slaad_Blue,
            CreatureConstants.Bodak,
            CreatureConstants.Dragon_Brass_Juvenile,
            CreatureConstants.Naga_Dark,
            CreatureConstants.Destrachan,
            CreatureConstants.Tiger_Dire)]
        [TestCase(ChallengeRatingConstants.CR9,
            CreatureConstants.Elemental_Air_Greater,
            CreatureConstants.Elemental_Earth_Greater,
            CreatureConstants.Elemental_Fire_Greater,
            CreatureConstants.Elemental_Water_Greater,
            CreatureConstants.Androsphinx,
            CreatureConstants.Avoral,
            CreatureConstants.Dragon_Black_YoungAdult,
            CreatureConstants.BoneDevil_Osyluth,
            CreatureConstants.Dragon_Bronze_Juvenile,
            CreatureConstants.Dragon_Copper_Juvenile,
            CreatureConstants.Delver,
            CreatureConstants.Shark_Dire)]
        [TestCase(ChallengeRatingConstants.CR10,
            CreatureConstants.AnimatedObject_Anvil_Colossal,
            CreatureConstants.AnimatedObject_Block_Stone_Colossal,
            CreatureConstants.AnimatedObject_Block_Wood_Colossal,
            CreatureConstants.AnimatedObject_Box_Colossal,
            CreatureConstants.AnimatedObject_Carpet_Colossal,
            CreatureConstants.AnimatedObject_Carriage_Colossal,
            CreatureConstants.AnimatedObject_Chain_Colossal,
            CreatureConstants.AnimatedObject_Chair_Colossal,
            CreatureConstants.AnimatedObject_Clothes_Colossal,
            CreatureConstants.AnimatedObject_Ladder_Colossal,
            CreatureConstants.AnimatedObject_Rope_Colossal,
            CreatureConstants.AnimatedObject_Rug_Colossal,
            CreatureConstants.AnimatedObject_Sled_Colossal,
            CreatureConstants.AnimatedObject_Statue_Animal_Colossal,
            CreatureConstants.AnimatedObject_Statue_Humanoid_Colossal,
            CreatureConstants.AnimatedObject_Stool_Colossal,
            CreatureConstants.AnimatedObject_Table_Colossal,
            CreatureConstants.AnimatedObject_Tapestry_Colossal,
            CreatureConstants.AnimatedObject_Wagon_Colossal,
            CreatureConstants.Bebilith,
            CreatureConstants.Dragon_Brass_YoungAdult,
            CreatureConstants.Golem_Clay,
            CreatureConstants.Couatl)]
        [TestCase(ChallengeRatingConstants.CR11,
            CreatureConstants.Elemental_Air_Elder,
            CreatureConstants.Elemental_Earth_Elder,
            CreatureConstants.Elemental_Fire_Elder,
            CreatureConstants.Elemental_Water_Elder,
            CreatureConstants.BarbedDevil_Hamatula,
            CreatureConstants.Dragon_Black_Adult,
            CreatureConstants.Dragon_Blue_YoungAdult,
            CreatureConstants.Giant_Cloud,
            CreatureConstants.Dragon_Copper_YoungAdult,
            CreatureConstants.Devourer)]
        [TestCase(ChallengeRatingConstants.CR12,
            CreatureConstants.Dragon_Brass_Adult,
            CreatureConstants.Dragon_Bronze_YoungAdult,
            CreatureConstants.DisplacerBeast_PackLord)]
        [TestCase(ChallengeRatingConstants.CR13,
            CreatureConstants.Beholder,
            CreatureConstants.Slaad_Death)]
        [TestCase(ChallengeRatingConstants.CR14,
            CreatureConstants.Angel_AstralDeva,
            CreatureConstants.Dragon_Black_MatureAdult,
            CreatureConstants.Dragon_Blue_Adult,
            CreatureConstants.Dragon_Copper_Adult)]
        [TestCase(ChallengeRatingConstants.CR15,
            CreatureConstants.Dragon_Brass_MatureAdult,
            CreatureConstants.Dragon_Bronze_Adult)]
        [TestCase(ChallengeRatingConstants.CR16,
            CreatureConstants.Angel_Planetar,
            CreatureConstants.Dragon_Black_Old,
            CreatureConstants.Dragon_Blue_MatureAdult,
            CreatureConstants.Dragon_Copper_MatureAdult)]
        [TestCase(ChallengeRatingConstants.CR17,
            CreatureConstants.Dragon_Brass_Old,
            CreatureConstants.Dragon_Bronze_MatureAdult)]
        [TestCase(ChallengeRatingConstants.CR18,
            CreatureConstants.Dragon_Black_VeryOld,
            CreatureConstants.Dragon_Blue_Old)]
        [TestCase(ChallengeRatingConstants.CR19,
            CreatureConstants.Dragon_Black_Ancient,
            CreatureConstants.Dragon_Blue_VeryOld,
            CreatureConstants.Dragon_Brass_VeryOld,
            CreatureConstants.Dragon_Bronze_Old,
            CreatureConstants.Dragon_Copper_Old)]
        [TestCase(ChallengeRatingConstants.CR20,
            CreatureConstants.Balor,
            CreatureConstants.Dragon_Black_Wyrm,
            CreatureConstants.Dragon_Brass_Ancient,
            CreatureConstants.Dragon_Bronze_VeryOld,
            CreatureConstants.Dragon_Copper_VeryOld)]
        [TestCase(ChallengeRatingConstants.CR21,
            CreatureConstants.Dragon_Blue_Ancient,
            CreatureConstants.Dragon_Brass_Wyrm)]
        [TestCase(ChallengeRatingConstants.CR22,
            CreatureConstants.Dragon_Black_GreatWyrm,
            CreatureConstants.Dragon_Bronze_Ancient,
            CreatureConstants.Dragon_Copper_Ancient)]
        [TestCase(ChallengeRatingConstants.CR23,
            CreatureConstants.Angel_Solar,
            CreatureConstants.Dragon_Blue_Wyrm,
            CreatureConstants.Dragon_Brass_GreatWyrm,
            CreatureConstants.Dragon_Bronze_Wyrm,
            CreatureConstants.Dragon_Copper_Wyrm)]
        [TestCase(ChallengeRatingConstants.CR24)]
        [TestCase(ChallengeRatingConstants.CR25,
            CreatureConstants.Dragon_Blue_GreatWyrm,
            CreatureConstants.Dragon_Bronze_GreatWyrm,
            CreatureConstants.Dragon_Copper_GreatWyrm)]
        [TestCase(ChallengeRatingConstants.CR26)]
        [TestCase(ChallengeRatingConstants.CR27)]
        public void CreatureChallengeRatingGroup(string name, params string[] entries)
        {
            AssertDistinctCollection(name, entries);
        }

        [TestCaseSource(typeof(CreatureTestData), nameof(CreatureTestData.Creatures))]
        public void CreatureChallengeRatingGroupMatchesCreatureData(string creature)
        {
            var data = creatureDataSelector.SelectFor(creature);
            var ofChallengeRating = collectionSelector.Explode(tableName, data.ChallengeRating);
            Assert.That(ofChallengeRating, Contains.Item(creature), data.ChallengeRating);

            var challengeRatings = ChallengeRatingConstants.GetOrdered().Except(new[] { data.ChallengeRating });
            foreach (var challengeRating in challengeRatings)
            {
                ofChallengeRating = collectionSelector.Explode(tableName, challengeRating);
                Assert.That(ofChallengeRating, Does.Not.Contain(creature), challengeRating);
            }
        }
    }
}