using DnDGen.CreatureGen.Magics;
using NUnit.Framework;

namespace DnDGen.CreatureGen.Tests.Unit.Magics
{
    [TestFixture]
    public class SpellConstantsTests
    {
        [TestCase(SpellConstants.Aid, "Aid")]
        [TestCase(SpellConstants.Blasphemy, "Blasphemy")]
        [TestCase(SpellConstants.Bless, "Bless")]
        [TestCase(SpellConstants.BlindnessDeafness, "Blindness/Deafness")]
        [TestCase(SpellConstants.Blur, "Blur")]
        [TestCase(SpellConstants.CharmMonster, "Charm monster")]
        [TestCase(SpellConstants.CharmPerson, "Charm person")]
        [TestCase(SpellConstants.ConeOfCold, "Cone of cold")]
        [TestCase(SpellConstants.Contagion, "Contagion")]
        [TestCase(SpellConstants.CureInflictCriticalWounds, "Cure/Inflict critical wounds")]
        [TestCase(SpellConstants.CureInflictLightWounds, "Cure/Inflict light wounds")]
        [TestCase(SpellConstants.CureInflictModerateWounds, "Cure/Inflict moderate wounds")]
        [TestCase(SpellConstants.CureInflictSeriousWounds, "Cure/Inflict serious wounds")]
        [TestCase(SpellConstants.DancingLights, "Dancing lights")]
        [TestCase(SpellConstants.Darkness, "Darkness")]
        [TestCase(SpellConstants.Daylight, "Daylight")]
        [TestCase(SpellConstants.Daze, "Daze")]
        [TestCase(SpellConstants.Desecrate, "Desecrate")]
        [TestCase(SpellConstants.Destruction, "Destruction")]
        [TestCase(SpellConstants.DetectThoughts, "Detect thoughts")]
        [TestCase(SpellConstants.DisguiseSelf, "Disguise self")]
        [TestCase(SpellConstants.DispelAlignment, "Dispel chaos/evil/good/law")]
        [TestCase(SpellConstants.EnlargePerson, "Enlarge person")]
        [TestCase(SpellConstants.FaerieFire, "Faerie fire")]
        [TestCase(SpellConstants.FreedomOfMovement, "Freedom of movement")]
        [TestCase(SpellConstants.GaseousForm, "Gaseous form")]
        [TestCase(SpellConstants.GhostSound, "Ghost sound")]
        [TestCase(SpellConstants.Hallow, "Hallow")]
        [TestCase(SpellConstants.HealHarm, "Heal/Harm")]
        [TestCase(SpellConstants.HolyAura, "Holy aura")]
        [TestCase(SpellConstants.HolySmite, "Holy smite")]
        [TestCase(SpellConstants.HolyWord, "Holy word")]
        [TestCase(SpellConstants.HorridWilting, "Horrid wilting")]
        [TestCase(SpellConstants.Invisibility, "Invisibility")]
        [TestCase(SpellConstants.Levitate, "Levitate")]
        [TestCase(SpellConstants.NeutralizePoison, "Neutralize poison")]
        [TestCase(SpellConstants.Nondetection, "Nondetection")]
        [TestCase(SpellConstants.PassWithoutTrace, "Pass without trace")]
        [TestCase(SpellConstants.PlaneShift, "Plane shift")]
        [TestCase(SpellConstants.Poison, "Poison")]
        [TestCase(SpellConstants.Polymorph, "Polymorph")]
        [TestCase(SpellConstants.Prestidigitation, "Prestidigitation")]
        [TestCase(SpellConstants.RemoveDisease, "Remove disease")]
        [TestCase(SpellConstants.Resurrection, "Resurrection")]
        [TestCase(SpellConstants.Sleep, "Sleep")]
        [TestCase(SpellConstants.SoundBurst, "Sound burst")]
        [TestCase(SpellConstants.SpeakWithAnimals, "Speak with animals")]
        [TestCase(SpellConstants.SpiderClimb, "Spider climb")]
        [TestCase(SpellConstants.Suggestion, "Suggestion")]
        [TestCase(SpellConstants.SummonMonsterI, "Summon monster I")]
        [TestCase(SpellConstants.SummonMonsterII, "Summon monster II")]
        [TestCase(SpellConstants.SummonMonsterIII, "Summon monster III")]
        [TestCase(SpellConstants.SummonMonsterIV, "Summon monster IV")]
        [TestCase(SpellConstants.SummonMonsterV, "Summon monster V")]
        [TestCase(SpellConstants.SummonMonsterVI, "Summon monster VI")]
        [TestCase(SpellConstants.SummonMonsterVII, "Summon monster VII")]
        [TestCase(SpellConstants.SummonMonsterVIII, "Summon monster VIII")]
        [TestCase(SpellConstants.SummonMonsterIX, "Summon monster IX")]
        [TestCase(SpellConstants.SummonNaturesAllyI, "Summon nature's ally I")]
        [TestCase(SpellConstants.SummonNaturesAllyII, "Summon nature's ally II")]
        [TestCase(SpellConstants.SummonNaturesAllyIII, "Summon nature's ally III")]
        [TestCase(SpellConstants.SummonNaturesAllyIV, "Summon nature's ally IV")]
        [TestCase(SpellConstants.SummonNaturesAllyV, "Summon nature's ally V")]
        [TestCase(SpellConstants.SummonNaturesAllyVI, "Summon nature's ally VI")]
        [TestCase(SpellConstants.SummonNaturesAllyVII, "Summon nature's ally VII")]
        [TestCase(SpellConstants.SummonNaturesAllyVIII, "Summon nature's ally VIII")]
        [TestCase(SpellConstants.SummonNaturesAllyIX, "Summon nature's ally IX")]
        [TestCase(SpellConstants.Unhallow, "Unhallow")]
        [TestCase(SpellConstants.UnholyAura, "Unholy aura")]
        [TestCase(SpellConstants.UnholyBlight, "Unholy blight")]
        [TestCase(SpellConstants.AcidSplash, "Acid splash")]
        [TestCase(SpellConstants.Resistance, "Resistance")]
        [TestCase(SpellConstants.DetectPoison, "Detect poison")]
        [TestCase(SpellConstants.DetectMagic, "Detect magic")]
        [TestCase(SpellConstants.ReadMagic, "Read magic")]
        [TestCase(SpellConstants.Flare, "Flare")]
        [TestCase(SpellConstants.Light, "Light")]
        [TestCase(SpellConstants.RayOfFrost, "Ray of frost")]
        [TestCase(SpellConstants.DisruptUndead, "Disrupt undead")]
        [TestCase(SpellConstants.TouchOfFatigue, "Touch of fatigue")]
        [TestCase(SpellConstants.MageHand, "Mage hand")]
        [TestCase(SpellConstants.Mending, "Mending")]
        [TestCase(SpellConstants.Message, "Message")]
        [TestCase(SpellConstants.OpenClose, "Open/Close")]
        [TestCase(SpellConstants.ArcaneMark, "Arcane mark")]
        [TestCase(SpellConstants.Alarm, "Alarm")]
        [TestCase(SpellConstants.EndureElements, "Endure elements")]
        [TestCase(SpellConstants.HoldPortal, "Hold portal")]
        [TestCase(SpellConstants.ProtectionFromAlignment, "Protection from chaos/evil/good/law")]
        [TestCase(SpellConstants.Shield, "Shield")]
        [TestCase(SpellConstants.Grease, "Grease")]
        [TestCase(SpellConstants.MageArmor, "Mage armor")]
        [TestCase(SpellConstants.Mount, "Mount")]
        [TestCase(SpellConstants.ObscuringMist, "Obscuring mist")]
        [TestCase(SpellConstants.UnseenServant, "Unseen servant")]
        [TestCase(SpellConstants.ComprehendLanguages, "Comprehend languages")]
        [TestCase(SpellConstants.DetectSecretDoors, "Detect secret doors")]
        [TestCase(SpellConstants.DetectUndead, "Detect undead")]
        [TestCase(SpellConstants.Identify, "Identify")]
        [TestCase(SpellConstants.TrueStrike, "True strike")]
        [TestCase(SpellConstants.Hypnotism, "Hypnotism")]
        [TestCase(SpellConstants.BurningHands, "Burning hands")]
        [TestCase(SpellConstants.FloatingDisk, "Floating disk")]
        [TestCase(SpellConstants.MagicMissile, "Magic missile")]
        [TestCase(SpellConstants.ShockingGrasp, "Shocking grasp")]
        [TestCase(SpellConstants.ColorSpray, "Color spray")]
        [TestCase(SpellConstants.MagicAura, "Magic aura")]
        [TestCase(SpellConstants.SilentImage, "Silent image")]
        [TestCase(SpellConstants.Ventriloquism, "Ventriloquism")]
        [TestCase(SpellConstants.CauseFear, "Cause fear")]
        [TestCase(SpellConstants.ChillTouch, "Chill touch")]
        [TestCase(SpellConstants.RayOfEnfeeblement, "Ray of enfeeblement")]
        [TestCase(SpellConstants.AnimateRope, "Animate rope")]
        [TestCase(SpellConstants.Erase, "Erase")]
        [TestCase(SpellConstants.ExpeditiousRetreat, "Expeditious retreat")]
        [TestCase(SpellConstants.FeatherFall, "Feather fall")]
        [TestCase(SpellConstants.Jump, "Jump")]
        [TestCase(SpellConstants.MagicWeapon, "Magic weapon")]
        [TestCase(SpellConstants.ReducePerson, "Reduce person")]
        [TestCase(SpellConstants.ArcaneLock, "Arcane lock")]
        [TestCase(SpellConstants.ObscureObject, "Obscure object")]
        [TestCase(SpellConstants.ProtectionFromArrows, "Protection from arrows")]
        [TestCase(SpellConstants.ResistEnergy, "Resist energy")]
        [TestCase(SpellConstants.AcidArrow, "Acid arrow")]
        [TestCase(SpellConstants.FogCloud, "Fog cloud")]
        [TestCase(SpellConstants.Glitterdust, "Glitterdust")]
        [TestCase(SpellConstants.SummonSwarm, "Summon swarm")]
        [TestCase(SpellConstants.Web, "Web")]
        [TestCase(SpellConstants.LocateObject, "Locate object")]
        [TestCase(SpellConstants.SeeInvisibility, "See invisibility")]
        [TestCase(SpellConstants.DazeMonster, "Daze monster")]
        [TestCase(SpellConstants.HideousLaughter, "Hideous laughter")]
        [TestCase(SpellConstants.TouchOfIdiocy, "Touch of idiocy")]
        [TestCase(SpellConstants.ContinualFlame, "Continual flame")]
        [TestCase(SpellConstants.FlamingSphere, "Flaming sphere")]
        [TestCase(SpellConstants.GustOfWind, "Gust of wind")]
        [TestCase(SpellConstants.ScorchingRay, "Scorching ray")]
        [TestCase(SpellConstants.Shatter, "Shatter")]
        [TestCase(SpellConstants.HypnoticPattern, "Hypnotic pattern")]
        [TestCase(SpellConstants.MagicMouth, "Magic mouth")]
        [TestCase(SpellConstants.MinorImage, "Minor image")]
        [TestCase(SpellConstants.MirrorImage, "Mirror image")]
        [TestCase(SpellConstants.Misdirection, "Misdirection")]
        [TestCase(SpellConstants.PhantomTrap, "Phantom trap")]
        [TestCase(SpellConstants.CommandUndead, "Command undead")]
        [TestCase(SpellConstants.FalseLife, "False life")]
        [TestCase(SpellConstants.GhoulTouch, "Ghoul touch")]
        [TestCase(SpellConstants.Scare, "Scare")]
        [TestCase(SpellConstants.SpectralHand, "Spectral hand")]
        [TestCase(SpellConstants.AlterSelf, "Alter self")]
        [TestCase(SpellConstants.BearsEndurance, "Bear's endurance")]
        [TestCase(SpellConstants.BullsStrength, "Bull's strength")]
        [TestCase(SpellConstants.CatsGrace, "Cat's grace")]
        [TestCase(SpellConstants.Darkvision, "Darkvision")]
        [TestCase(SpellConstants.EaglesSplendor, "Eagle's splendor")]
        [TestCase(SpellConstants.FoxsCunning, "Fox's cunning")]
        [TestCase(SpellConstants.Knock, "Knock")]
        [TestCase(SpellConstants.OwlsWisdom, "Owl's wisdom")]
        [TestCase(SpellConstants.Pyrotechnics, "Pyrotechnics")]
        [TestCase(SpellConstants.RopeTrick, "Rope trick")]
        [TestCase(SpellConstants.WhisperingWind, "Whispering wind")]
        [TestCase(SpellConstants.DispelMagic, "Dispel magic")]
        [TestCase(SpellConstants.ExplosiveRunes, "Explosive runes")]
        [TestCase(SpellConstants.MagicCircleAgainstAlignment, "Magic circle against chaos/evil/good/law")]
        [TestCase(SpellConstants.ProtectionFromEnergy, "Protection from energy")]
        [TestCase(SpellConstants.PhantomSteed, "Phantom steed")]
        [TestCase(SpellConstants.SepiaSnakeSigil, "Sepia snake sigil")]
        [TestCase(SpellConstants.SleetStorm, "Sleet storm")]
        [TestCase(SpellConstants.StinkingCloud, "Stinking cloud")]
        [TestCase(SpellConstants.ArcaneSight, "Arcane sight")]
        [TestCase(SpellConstants.ClairaudienceClairvoyance, "Clairaudience/Clairvoyance")]
        [TestCase(SpellConstants.Tongues, "Tongues")]
        [TestCase(SpellConstants.DeepSlumber, "Deep slumber")]
        [TestCase(SpellConstants.Heroism, "Heroism")]
        [TestCase(SpellConstants.HoldPerson, "Hold person")]
        [TestCase(SpellConstants.Rage, "Rage")]
        [TestCase(SpellConstants.Fireball, "Fireball")]
        [TestCase(SpellConstants.LightningBolt, "Lightning bolt")]
        [TestCase(SpellConstants.TinyHut, "Tiny hut")]
        [TestCase(SpellConstants.WindWall, "Wind wall")]
        [TestCase(SpellConstants.Displacement, "Displacement")]
        [TestCase(SpellConstants.IllusoryScript, "Illusory script")]
        [TestCase(SpellConstants.InvisibilitySphere, "Invisibility sphere")]
        [TestCase(SpellConstants.MajorImage, "Major image")]
        [TestCase(SpellConstants.GentleRepose, "Gentle repose")]
        [TestCase(SpellConstants.HaltUndead, "Halt undead")]
        [TestCase(SpellConstants.RayOfExhaustion, "Ray of exhaustion")]
        [TestCase(SpellConstants.VampiricTouch, "Vampiric touch")]
        [TestCase(SpellConstants.Blink, "Blink")]
        [TestCase(SpellConstants.FlameArrow, "Flame arrow")]
        [TestCase(SpellConstants.Fly, "Fly")]
        [TestCase(SpellConstants.Haste, "Haste")]
        [TestCase(SpellConstants.KeenEdge, "Keen edge")]
        [TestCase(SpellConstants.MagicWeapon_Greater, "Greater magic weapon")]
        [TestCase(SpellConstants.SecretPage, "Secret page")]
        [TestCase(SpellConstants.ShrinkItem, "Shrink item")]
        [TestCase(SpellConstants.Slow, "Slow")]
        [TestCase(SpellConstants.WaterBreathing, "Water breathing")]
        [TestCase(SpellConstants.FireTrap, "Fire trap")]
        [TestCase(SpellConstants.GlobeOfInvulnerability_Lesser, "Lesser globe of invulnerability")]
        [TestCase(SpellConstants.RemoveCurse, "Remove curse")]
        [TestCase(SpellConstants.Stoneskin, "Stoneskin")]
        [TestCase(SpellConstants.BlackTentacles, "Black tentacles")]
        [TestCase(SpellConstants.DimensionDoor, "Dimension door")]
        [TestCase(SpellConstants.MinorCreation, "Minor creation")]
        [TestCase(SpellConstants.SecureShelter, "Secure shelter")]
        [TestCase(SpellConstants.SolidFog, "Solid fog")]
        [TestCase(SpellConstants.ArcaneEye, "Arcane eye")]
        [TestCase(SpellConstants.DetectScrying, "Detect scrying")]
        [TestCase(SpellConstants.LocateCreature, "Locate creature")]
        [TestCase(SpellConstants.Scrying, "Scrying")]
        [TestCase(SpellConstants.Confusion, "Confusion")]
        [TestCase(SpellConstants.CrushingDespair, "Crushing despair")]
        [TestCase(SpellConstants.Geas_Lesser, "Lesser geas")]
        [TestCase(SpellConstants.FireShield, "Fire shield")]
        [TestCase(SpellConstants.IceStorm, "Ice storm")]
        [TestCase(SpellConstants.ResilientSphere, "Resilient sphere")]
        [TestCase(SpellConstants.Shout, "Shout")]
        [TestCase(SpellConstants.WallOfFire, "Wall of fire")]
        [TestCase(SpellConstants.WallOfIce, "Wall of ice")]
        [TestCase(SpellConstants.HallucinatoryTerrain, "Hallucinatory terrain")]
        [TestCase(SpellConstants.IllusoryWall, "Illusory wall")]
        [TestCase(SpellConstants.Invisibility_Greater, "Greater invisibility")]
        [TestCase(SpellConstants.PhantasmalKiller, "Phantasmal killer")]
        [TestCase(SpellConstants.RainbowPattern, "Rainbow pattern")]
        [TestCase(SpellConstants.AnimateDead, "Animate dead")]
        [TestCase(SpellConstants.BestowCurse, "Bestow curse")]
        [TestCase(SpellConstants.Enervation, "Enervation")]
        [TestCase(SpellConstants.Fear, "Fear")]
        [TestCase(SpellConstants.EnlargePerson_Mass, "Mass enlarge person")]
        [TestCase(SpellConstants.MnemonicEnhancer, "Mnemonic enhancer")]
        [TestCase(SpellConstants.ReducePerson_Mass, "Mass reduce person")]
        [TestCase(SpellConstants.StoneShape, "Stone shape")]
        [TestCase(SpellConstants.BreakEnchantment, "Break enchantment")]
        [TestCase(SpellConstants.Dismissal, "Dismissal")]
        [TestCase(SpellConstants.MagesPrivateSanctum, "Mage's private sanctum")]
        [TestCase(SpellConstants.Cloudkill, "Cloudkill")]
        [TestCase(SpellConstants.MagesFaithfulHound, "Mage's faithful hound")]
        [TestCase(SpellConstants.MajorCreation, "Major creation")]
        [TestCase(SpellConstants.PlanarBinding_Lesser, "Lesser planar binding")]
        [TestCase(SpellConstants.SecretChest, "Secret chest")]
        [TestCase(SpellConstants.Teleport, "Teleport")]
        [TestCase(SpellConstants.WallOfStone, "Wall of stone")]
        [TestCase(SpellConstants.ContactOtherPlane, "Contact other plane")]
        [TestCase(SpellConstants.PryingEyes, "Prying eyes")]
        [TestCase(SpellConstants.TelepathicBond, "Telepathic bond")]
        [TestCase(SpellConstants.DominatePerson, "Dominate person")]
        [TestCase(SpellConstants.Feeblemind, "Feeblemind")]
        [TestCase(SpellConstants.HoldMonster, "Hold monster")]
        [TestCase(SpellConstants.MindFog, "Mind fog")]
        [TestCase(SpellConstants.SymbolOfSleep, "Symbol of sleep")]
        [TestCase(SpellConstants.InterposingHand, "Interposing hand")]
        [TestCase(SpellConstants.Sending, "Sending")]
        [TestCase(SpellConstants.WallOfForce, "Wall of force")]
        [TestCase(SpellConstants.Dream, "Dream")]
        [TestCase(SpellConstants.FalseVision, "False vision")]
        [TestCase(SpellConstants.MirageArcana, "Mirage arcana")]
        [TestCase(SpellConstants.Nightmare, "Nightmare")]
        [TestCase(SpellConstants.PersistentImage, "Persistent image")]
        [TestCase(SpellConstants.Seeming, "Seeming")]
        [TestCase(SpellConstants.ShadowEvocation, "Shadow evocation")]
        [TestCase(SpellConstants.Blight, "Blight")]
        [TestCase(SpellConstants.MagicJar, "Magic jar")]
        [TestCase(SpellConstants.SymbolOfPain, "Symbol of pain")]
        [TestCase(SpellConstants.WavesOfFatigue, "Waves of fatigue")]
        [TestCase(SpellConstants.AnimalGrowth, "Animal growth")]
        [TestCase(SpellConstants.Fabricate, "Fabricate")]
        [TestCase(SpellConstants.OverlandFlight, "Overland flight")]
        [TestCase(SpellConstants.Passwall, "Passwall")]
        [TestCase(SpellConstants.Telekinesis, "Telekinesis")]
        [TestCase(SpellConstants.TransmuteMudToRock, "Transmute mud to rock")]
        [TestCase(SpellConstants.TransmuteRockToMud, "Transmute rock to mud")]
        [TestCase(SpellConstants.Permanency, "Permanency")]
        [TestCase(SpellConstants.AntimagicField, "Antimagic field")]
        [TestCase(SpellConstants.DispelMagic_Greater, "Greater dispel magic")]
        [TestCase(SpellConstants.GlobeOfInvulnerability, "Globe of invulnerability")]
        [TestCase(SpellConstants.GuardsAndWards, "Guards and wards")]
        [TestCase(SpellConstants.Repulsion, "Repulsion")]
        [TestCase(SpellConstants.AcidFog, "Acid fog")]
        [TestCase(SpellConstants.PlanarBinding, "Planar binding")]
        [TestCase(SpellConstants.WallOfIron, "Wall of iron")]
        [TestCase(SpellConstants.AnalyzeDweomer, "Analyze dweomer")]
        [TestCase(SpellConstants.LegendLore, "Legend lore")]
        [TestCase(SpellConstants.TrueSeeing, "True seeing")]
        [TestCase(SpellConstants.GeasQuest, "Geas/Quest")]
        [TestCase(SpellConstants.Heroism_Greater, "Greater heroism")]
        [TestCase(SpellConstants.Suggestion_Mass, "Mass suggestion")]
        [TestCase(SpellConstants.SymbolOfPersuasion, "Symbol of persuasion")]
        [TestCase(SpellConstants.ChainLightning, "Chain lightning")]
        [TestCase(SpellConstants.Contingency, "Contingency")]
        [TestCase(SpellConstants.ForcefulHand, "Forceful hand")]
        [TestCase(SpellConstants.FreezingSphere, "Freezing sphere")]
        [TestCase(SpellConstants.Mislead, "Mislead")]
        [TestCase(SpellConstants.PermanentImage, "Permanent image")]
        [TestCase(SpellConstants.ProgrammedImage, "Programmed image")]
        [TestCase(SpellConstants.ShadowWalk, "Shadow walk")]
        [TestCase(SpellConstants.Veil, "Veil")]
        [TestCase(SpellConstants.CircleOfDeath, "Circle of death")]
        [TestCase(SpellConstants.Eyebite, "Eyebite")]
        [TestCase(SpellConstants.SymbolOfFear, "Symbol of fear")]
        [TestCase(SpellConstants.ArcaneSight_Greater, "Greater arcane sight")]
        [TestCase(SpellConstants.Banishment, "Banishment")]
        [TestCase(SpellConstants.BearsEndurance_Mass, "Mass bear's endurance")]
        [TestCase(SpellConstants.BullsStrength_Mass, "Mass bull's strength")]
        [TestCase(SpellConstants.CatsGrace_Mass, "Mass cat's grace")]
        [TestCase(SpellConstants.ControlUndead, "Control undead")]
        [TestCase(SpellConstants.ControlWater, "Control water")]
        [TestCase(SpellConstants.ControlWeather, "Control weather")]
        [TestCase(SpellConstants.DelayedBlastFireball, "Delayed blast fireball")]
        [TestCase(SpellConstants.DimensionalLock, "Dimensional lock")]
        [TestCase(SpellConstants.Disintegrate, "Disintegrate")]
        [TestCase(SpellConstants.EaglesSplendor_Mass, "Mass eagle's splendor")]
        [TestCase(SpellConstants.EtherealJaunt, "Ethereal jaunt")]
        [TestCase(SpellConstants.FingerOfDeath, "Finger of death")]
        [TestCase(SpellConstants.FleshToStone, "Flesh to stone")]
        [TestCase(SpellConstants.Forcecage, "Forcecage")]
        [TestCase(SpellConstants.FoxsCunning_Mass, "Mass fox's cunning")]
        [TestCase(SpellConstants.GraspingHand, "Grasping hand")]
        [TestCase(SpellConstants.HoldPerson_Mass, "Mass hold person")]
        [TestCase(SpellConstants.IncendiaryCloud, "Incendiary cloud")]
        [TestCase(SpellConstants.Insanity, "Insanity")]
        [TestCase(SpellConstants.InstantSummons, "Instant summons")]
        [TestCase(SpellConstants.Invisibility_Mass, "Mass invisibility")]
        [TestCase(SpellConstants.LimitedWish, "Limited wish")]
        [TestCase(SpellConstants.MagesLucubration, "Mage's lucubration")]
        [TestCase(SpellConstants.MagesMagnificentMansion, "Mage's magnificent mansion")]
        [TestCase(SpellConstants.MagesSword, "Mage's sword")]
        [TestCase(SpellConstants.MindBlank, "Mind blank")]
        [TestCase(SpellConstants.MoveEarth, "Move earth")]
        [TestCase(SpellConstants.OwlsWisdom_Mass, "Mass owl's wisdom")]
        [TestCase(SpellConstants.PhaseDoor, "Phase door")]
        [TestCase(SpellConstants.PowerWordBlind, "Power word blind")]
        [TestCase(SpellConstants.PrismaticSpray, "Prismatic spray")]
        [TestCase(SpellConstants.PrismaticWall, "Prismatic wall")]
        [TestCase(SpellConstants.ProjectImage, "Project image")]
        [TestCase(SpellConstants.ProtectionFromSpells, "Protection from spells")]
        [TestCase(SpellConstants.ReverseGravity, "Reverse gravity")]
        [TestCase(SpellConstants.Scrying_Greater, "Greater scrying")]
        [TestCase(SpellConstants.Sequester, "Sequester")]
        [TestCase(SpellConstants.ShadowConjuration_Greater, "Greater shadow conjuration")]
        [TestCase(SpellConstants.Simulacrum, "Simulacrum")]
        [TestCase(SpellConstants.SpellTurning, "Spell turning")]
        [TestCase(SpellConstants.Statue, "Statue")]
        [TestCase(SpellConstants.StoneToFlesh, "Stone to flesh")]
        [TestCase(SpellConstants.SymbolOfStunning, "Symbol of stunning")]
        [TestCase(SpellConstants.SymbolOfWeakness, "Symbol of weakness")]
        [TestCase(SpellConstants.Teleport_Greater, "Greater teleport")]
        [TestCase(SpellConstants.TeleportObject, "Teleport object")]
        [TestCase(SpellConstants.Transformation, "Transformation")]
        [TestCase(SpellConstants.UndeathToDeath, "Undeath to death")]
        [TestCase(SpellConstants.Vision, "Vision")]
        [TestCase(SpellConstants.WavesOfExhaustion, "Waves of exhaustion")]
        [TestCase(SpellConstants.Antipathy, "Antipathy")]
        [TestCase(SpellConstants.AstralProjection, "Astral projection")]
        [TestCase(SpellConstants.Binding, "Binding")]
        [TestCase(SpellConstants.CharmMonster_Mass, "Mass charm monster")]
        [TestCase(SpellConstants.ClenchedFist, "Clenched fist")]
        [TestCase(SpellConstants.Clone, "Clone")]
        [TestCase(SpellConstants.CreateGreaterUndead, "Create greater undead")]
        [TestCase(SpellConstants.CrushingHand, "Crushing hand")]
        [TestCase(SpellConstants.Demand, "Demand")]
        [TestCase(SpellConstants.DiscernLocation, "Discern location")]
        [TestCase(SpellConstants.DominateMonster, "Dominate monster")]
        [TestCase(SpellConstants.EnergyDrain, "Energy drain")]
        [TestCase(SpellConstants.Etherealness, "Etherealness")]
        [TestCase(SpellConstants.Foresight, "Foresight")]
        [TestCase(SpellConstants.Freedom, "Freedom")]
        [TestCase(SpellConstants.Gate, "Gate")]
        [TestCase(SpellConstants.HoldMonster_Mass, "Mass hold monster")]
        [TestCase(SpellConstants.Imprisonment, "Imprisonment")]
        [TestCase(SpellConstants.IronBody, "Iron body")]
        [TestCase(SpellConstants.MagesDisjunction, "Mage's disjunction")]
        [TestCase(SpellConstants.Maze, "Maze")]
        [TestCase(SpellConstants.MeteorSwarm, "Meteor swarm")]
        [TestCase(SpellConstants.MomentOfPrescience, "Moment of prescience")]
        [TestCase(SpellConstants.PlanarBinding_Greater, "Greater planar binding")]
        [TestCase(SpellConstants.PolarRay, "Polar ray")]
        [TestCase(SpellConstants.PolymorphAnyObject, "Polymorph any object")]
        [TestCase(SpellConstants.PowerWordKill, "Power word kill")]
        [TestCase(SpellConstants.PowerWordStun, "Power word stun")]
        [TestCase(SpellConstants.PrismaticSphere, "Prismatic sphere")]
        [TestCase(SpellConstants.PryingEyes_Greater, "Greater prying eyes")]
        [TestCase(SpellConstants.Refuge, "Refuge")]
        [TestCase(SpellConstants.ScintillatingPattern, "Scintillating pattern")]
        [TestCase(SpellConstants.Screen, "Screen")]
        [TestCase(SpellConstants.Shades, "Shades")]
        [TestCase(SpellConstants.ShadowEvocation_Greater, "Greater shadow evocation")]
        [TestCase(SpellConstants.Shapechange, "Shapechange")]
        [TestCase(SpellConstants.Shout_Greater, "Greater shout")]
        [TestCase(SpellConstants.SoulBind, "Soul bind")]
        [TestCase(SpellConstants.Sunburst, "Sunburst")]
        [TestCase(SpellConstants.SymbolOfDeath, "Symbol of death")]
        [TestCase(SpellConstants.SymbolOfInsanity, "Symbol of insanity")]
        [TestCase(SpellConstants.Sympathy, "Sympathy")]
        [TestCase(SpellConstants.TelekineticSphere, "Telekinetic sphere")]
        [TestCase(SpellConstants.TeleportationCircle, "Teleportation circle")]
        [TestCase(SpellConstants.TemporalStasis, "Temporal stasis")]
        [TestCase(SpellConstants.TimeStop, "Time stop")]
        [TestCase(SpellConstants.TrapTheSoul, "Trap the soul")]
        [TestCase(SpellConstants.WailOfTheBanshee, "Wail of the banshee")]
        [TestCase(SpellConstants.Weird, "Weird")]
        [TestCase(SpellConstants.Wish, "Wish")]
        [TestCase(SpellConstants.AirWalk, "Air walk")]
        [TestCase(SpellConstants.AnimalShapes, "Animal shapes")]
        [TestCase(SpellConstants.AnimateObjects, "Animate objects")]
        [TestCase(SpellConstants.AnimatePlants, "Animate plants")]
        [TestCase(SpellConstants.AntilifeShell, "Antilife shell")]
        [TestCase(SpellConstants.Barkskin, "Barkskin")]
        [TestCase(SpellConstants.BladeBarrier, "Blade barrier")]
        [TestCase(SpellConstants.CalmAnimals, "Calm animals")]
        [TestCase(SpellConstants.CalmEmotions, "Calm emotions")]
        [TestCase(SpellConstants.ChaosHammer, "Chaos hammer")]
        [TestCase(SpellConstants.CloakOfChaos, "Cloak of chaos")]
        [TestCase(SpellConstants.CommandPlants, "Command plants")]
        [TestCase(SpellConstants.CommuneWithNature, "Commune with nature")]
        [TestCase(SpellConstants.ControlPlants, "Control plants")]
        [TestCase(SpellConstants.ControlWinds, "Control winds")]
        [TestCase(SpellConstants.CreateUndead, "Create undead")]
        [TestCase(SpellConstants.CureInflictCriticalWounds_Mass, "Mass cure/inflict critical wounds")]
        [TestCase(SpellConstants.CureInflictLightWounds_Mass, "Mass cure/inflict light wounds")]
        [TestCase(SpellConstants.DeathKnell, "Death knell")]
        [TestCase(SpellConstants.DeathWard, "Death ward")]
        [TestCase(SpellConstants.Dictum, "Dictum")]
        [TestCase(SpellConstants.Divination, "Divination")]
        [TestCase(SpellConstants.DivinePower, "Divine power")]
        [TestCase(SpellConstants.DominateAnimal, "Dominate animal")]
        [TestCase(SpellConstants.Earthquake, "Earthquake")]
        [TestCase(SpellConstants.ElementalSwarm, "Elemental swarm")]
        [TestCase(SpellConstants.Entangle, "Entangle")]
        [TestCase(SpellConstants.EntropicShield, "Entropic shield")]
        [TestCase(SpellConstants.FindThePath, "Find the path")]
        [TestCase(SpellConstants.FireSeeds, "Fire seeds")]
        [TestCase(SpellConstants.FireStorm, "Fire storm")]
        [TestCase(SpellConstants.FlameStrike, "Flame strike")]
        [TestCase(SpellConstants.HealHarm_Mass, "Mass heal/harm")]
        [TestCase(SpellConstants.HeatMetal, "Heat metal")]
        [TestCase(SpellConstants.HoldAnimal, "Hold animal")]
        [TestCase(SpellConstants.ImbueWithSpellAbility, "Imbue with spell ability")]
        [TestCase(SpellConstants.Implosion, "Implosion")]
        [TestCase(SpellConstants.Longstrider, "Longstrider")]
        [TestCase(SpellConstants.MagicStone, "Magic stone")]
        [TestCase(SpellConstants.MagicVestment, "Magic vestment")]
        [TestCase(SpellConstants.Miracle, "Miracle")]
        [TestCase(SpellConstants.OrdersWrath, "Order's wrath")]
        [TestCase(SpellConstants.PlantGrowth, "Plant growth")]
        [TestCase(SpellConstants.ProduceFlame, "Produce flame")]
        [TestCase(SpellConstants.Regenerate, "Regenerate")]
        [TestCase(SpellConstants.RepelWood, "Repel wood")]
        [TestCase(SpellConstants.RighteousMight, "Righteous might")]
        [TestCase(SpellConstants.Sanctuary, "Sanctuary")]
        [TestCase(SpellConstants.SearingLight, "Searing light")]
        [TestCase(SpellConstants.Shambler, "Shambler")]
        [TestCase(SpellConstants.ShieldOfLaw, "Shield of law")]
        [TestCase(SpellConstants.ShieldOther, "Shield other")]
        [TestCase(SpellConstants.SlayLiving, "Slay living")]
        [TestCase(SpellConstants.SoftenEarthAndStone, "Soften earth and stone")]
        [TestCase(SpellConstants.SpellImmunity, "Spell immunity")]
        [TestCase(SpellConstants.SpellResistance, "Spell resistance")]
        [TestCase(SpellConstants.SpikeStones, "Spike stones")]
        [TestCase(SpellConstants.SpiritualWeapon, "Spiritual weapon")]
        [TestCase(SpellConstants.Sunbeam, "Sunbeam")]
        [TestCase(SpellConstants.Whirlwind, "Whirlwind")]
        [TestCase(SpellConstants.WordOfChaos, "Word of chaos")]
        [TestCase(SpellConstants.WallOfThorns, "Wall of thorns")]
        [TestCase(SpellConstants.AnimalMessenger, "Animal messenger")]
        [TestCase(SpellConstants.CharmAnimal, "Charm animal")]
        [TestCase(SpellConstants.DelayPoison, "Delay poison")]
        [TestCase(SpellConstants.DetectAnimalsOrPlants, "Detect animals or plants")]
        [TestCase(SpellConstants.DetectSnaresAndPits, "Detect snares and pits")]
        [TestCase(SpellConstants.HideFromAnimals, "Hide from animals")]
        [TestCase(SpellConstants.MagicFang, "Magic fang")]
        [TestCase(SpellConstants.Snare, "Snare")]
        [TestCase(SpellConstants.SpeakWithPlants, "Speak with plants")]
        [TestCase(SpellConstants.SpikeGrowth, "Spike growth")]
        [TestCase(SpellConstants.DiminishPlants, "Diminish plants")]
        [TestCase(SpellConstants.MagicFang_Greater, "Greater magic fang")]
        [TestCase(SpellConstants.ReduceAnimal, "Reduce animal")]
        [TestCase(SpellConstants.RepelVermin, "Repel vermin")]
        [TestCase(SpellConstants.TreeShape, "Tree shape")]
        [TestCase(SpellConstants.WaterWalk, "Water walk")]
        [TestCase(SpellConstants.TreeStride, "Tree stride")]
        [TestCase(SpellConstants.CreateWater, "Create water")]
        [TestCase(SpellConstants.CureInflictMinorWounds, "Cure/Inflict minor wounds")]
        [TestCase(SpellConstants.Guidance, "Guidance")]
        [TestCase(SpellConstants.PurifyFoodAndDrink, "Purify food and drink")]
        [TestCase(SpellConstants.Virtue, "Virtue")]
        [TestCase(SpellConstants.Bane, "Bane")]
        [TestCase(SpellConstants.BlessWater, "Bless water")]
        [TestCase(SpellConstants.Command, "Command")]
        [TestCase(SpellConstants.CurseWater, "Curse water")]
        [TestCase(SpellConstants.Deathwatch, "Deathwatch")]
        [TestCase(SpellConstants.DetectAlignment, "Detect chaos/evil/good/law")]
        [TestCase(SpellConstants.DivineFavor, "Divine favor")]
        [TestCase(SpellConstants.Doom, "Doom")]
        [TestCase(SpellConstants.HideFromUndead, "Hide from undead")]
        [TestCase(SpellConstants.RemoveFear, "Remove fear")]
        [TestCase(SpellConstants.ShieldOfFaith, "Shield of faith")]
        [TestCase(SpellConstants.AlignWeapon, "Align weapon")]
        [TestCase(SpellConstants.Augury, "Augury")]
        [TestCase(SpellConstants.Consecrate, "Consecrate")]
        [TestCase(SpellConstants.Enthrall, "Enthrall")]
        [TestCase(SpellConstants.FindTraps, "Find traps")]
        [TestCase(SpellConstants.MakeWhole, "Make whole")]
        [TestCase(SpellConstants.RemoveParalysis, "Remove paralysis")]
        [TestCase(SpellConstants.Restoration_Lesser, "Lesser restoration")]
        [TestCase(SpellConstants.Silence, "Silence")]
        [TestCase(SpellConstants.Status, "Status")]
        [TestCase(SpellConstants.UndetectableAlignment, "Undetectable alignment")]
        [TestCase(SpellConstants.ZoneOfTruth, "Zone of truth")]
        [TestCase(SpellConstants.CreateFoodAndWater, "Create food and water")]
        [TestCase(SpellConstants.DeeperDarkness, "Deeper darkness")]
        [TestCase(SpellConstants.GlyphOfWarding, "Glyph of warding")]
        [TestCase(SpellConstants.HelpingHand, "Helping hand")]
        [TestCase(SpellConstants.InvisibilityPurge, "Invisibility purge")]
        [TestCase(SpellConstants.MeldIntoStone, "Meld into stone")]
        [TestCase(SpellConstants.Prayer, "Prayer")]
        [TestCase(SpellConstants.RemoveBlindnessDeafness, "Remove blindness/deafness")]
        [TestCase(SpellConstants.SpeakWithDead, "Speak with dead")]
        [TestCase(SpellConstants.DimensionalAnchor, "Dimensional anchor")]
        [TestCase(SpellConstants.DiscernLies, "Discern lies")]
        [TestCase(SpellConstants.GiantVermin, "Giant vermin")]
        [TestCase(SpellConstants.PlanarAlly_Lesser, "Lesser planar ally")]
        [TestCase(SpellConstants.Restoration, "Restoration")]
        [TestCase(SpellConstants.Atonement, "Atonement")]
        [TestCase(SpellConstants.Command_Greater, "Greater command")]
        [TestCase(SpellConstants.Commune, "Commune")]
        [TestCase(SpellConstants.DisruptingWeapon, "Disrupting weapon")]
        [TestCase(SpellConstants.InsectPlague, "Insect plague")]
        [TestCase(SpellConstants.MarkOfJustice, "Mark of justice")]
        [TestCase(SpellConstants.RaiseDead, "Raise dead")]
        [TestCase(SpellConstants.CureInflictModerateWounds_Mass, "Mass cure/inflict moderate wounds")]
        [TestCase(SpellConstants.Forbiddance, "Forbiddance")]
        [TestCase(SpellConstants.GlyphOfWarding_Greater, "Greater glyph of warding")]
        [TestCase(SpellConstants.HeroesFeast, "Heroes' feast")]
        [TestCase(SpellConstants.PlanarAlly, "Planar ally")]
        [TestCase(SpellConstants.WindWalk, "Wind walk")]
        [TestCase(SpellConstants.WordOfRecall, "Word of recall")]
        [TestCase(SpellConstants.CureInflictSeriousWounds_Mass, "Mass cure/inflict serious wounds")]
        [TestCase(SpellConstants.Restoration_Greater, "Greater restoration")]
        [TestCase(SpellConstants.PlanarAlly_Greater, "Greater planar ally")]
        [TestCase(SpellConstants.SpellImmunity_Greater, "Greater spell immunity")]
        [TestCase(SpellConstants.StormOfVengeance, "Storm of vengeance")]
        [TestCase(SpellConstants.TrueResurrection, "True resurrection")]
        [TestCase(SpellConstants.KnowDirection, "Know direction")]
        [TestCase(SpellConstants.Goodberry, "Goodberry")]
        [TestCase(SpellConstants.Shillelagh, "Shillelagh")]
        [TestCase(SpellConstants.AnimalTrance, "Animal trance")]
        [TestCase(SpellConstants.ChillMetal, "Chill metal")]
        [TestCase(SpellConstants.FlameBlade, "Flame blade")]
        [TestCase(SpellConstants.WarpWood, "Warp wood")]
        [TestCase(SpellConstants.WoodShape, "Wood shape")]
        [TestCase(SpellConstants.CallLightning, "Call lightning")]
        [TestCase(SpellConstants.Quench, "Quench")]
        [TestCase(SpellConstants.AntiplantShell, "Antiplant shell")]
        [TestCase(SpellConstants.Reincarnate, "Reincarnate")]
        [TestCase(SpellConstants.RustingGrasp, "Rusting grasp")]
        [TestCase(SpellConstants.Awaken, "Awaken")]
        [TestCase(SpellConstants.BalefulPolymorph, "Baleful polymorph")]
        [TestCase(SpellConstants.CallLightningStorm, "Call lightning storm")]
        [TestCase(SpellConstants.Ironwood, "Ironwood")]
        [TestCase(SpellConstants.Liveoak, "Liveoak")]
        [TestCase(SpellConstants.Spellstaff, "Spellstaff")]
        [TestCase(SpellConstants.StoneTell, "Stone tell")]
        [TestCase(SpellConstants.TransportViaPlants, "Transport via plants")]
        [TestCase(SpellConstants.Changestaff, "Changestaff")]
        [TestCase(SpellConstants.CreepingDoom, "Creeping doom")]
        [TestCase(SpellConstants.TransmuteMetalToWood, "Transmute metal to wood")]
        [TestCase(SpellConstants.RepelMetalOrStone, "Repel metal or stone")]
        [TestCase(SpellConstants.Lullaby, "Lullaby")]
        [TestCase(SpellConstants.SummonInstrument, "Summon instrument")]
        [TestCase(SpellConstants.Confusion_Lesser, "Lesser confusion")]
        [TestCase(SpellConstants.Glibness, "Glibness")]
        [TestCase(SpellConstants.GoodHope, "Good hope")]
        [TestCase(SpellConstants.SculptSound, "Sculpt sound")]
        [TestCase(SpellConstants.ModifyMemory, "Modify memory")]
        [TestCase(SpellConstants.ShadowConjuration, "Shadow conjuration")]
        [TestCase(SpellConstants.ZoneOfSilence, "Zone of silence")]
        [TestCase(SpellConstants.SongOfDiscord, "Song of discord")]
        [TestCase(SpellConstants.IrresistibleDance, "Irresistible dance")]
        [TestCase(SpellConstants.SympatheticVibration, "Sympathetic vibration")]
        [TestCase(SpellConstants.BlessWeapon, "Bless weapon")]
        [TestCase(SpellConstants.HealMount, "Heal mount")]
        [TestCase(SpellConstants.HolySword, "Holy sword")]
        [TestCase(SpellConstants.Sources.Arcane, "Arcane")]
        [TestCase(SpellConstants.Sources.Divine, "Divine")]
        [TestCase(SpellConstants.Casters.Bard, "Bard")]
        [TestCase(SpellConstants.Casters.Cleric, "Cleric")]
        [TestCase(SpellConstants.Casters.Druid, "Druid")]
        [TestCase(SpellConstants.Casters.Sorcerer, "Sorcerer")]
        [TestCase(SpellConstants.Casters.Wizard, "Wizard")]
        [TestCase(SpellConstants.Domains.Air, "Air")]
        [TestCase(SpellConstants.Domains.Animal, "Animal")]
        [TestCase(SpellConstants.Domains.Chaos, "Chaos")]
        [TestCase(SpellConstants.Domains.Destruction, "Destruction")]
        [TestCase(SpellConstants.Domains.Earth, "Earth")]
        [TestCase(SpellConstants.Domains.Enchantment, "Enchantment")]
        [TestCase(SpellConstants.Domains.Evil, "Evil")]
        [TestCase(SpellConstants.Domains.Fire, "Fire")]
        [TestCase(SpellConstants.Domains.Good, "Good")]
        [TestCase(SpellConstants.Domains.Healing, "Healing")]
        [TestCase(SpellConstants.Domains.Illusion, "Illusion")]
        [TestCase(SpellConstants.Domains.Knowledge, "Knowledge")]
        [TestCase(SpellConstants.Domains.Law, "Law")]
        [TestCase(SpellConstants.Domains.Luck, "Luck")]
        [TestCase(SpellConstants.Domains.Plant, "Plant")]
        [TestCase(SpellConstants.Domains.Protection, "Protection")]
        [TestCase(SpellConstants.Domains.Sun, "Sun")]
        [TestCase(SpellConstants.Domains.Trickery, "Trickery")]
        [TestCase(SpellConstants.Domains.War, "War")]
        [TestCase(SpellConstants.Domains.Water, "Water")]
        public void SpellConstant(string constant, string value)
        {
            Assert.That(constant, Is.EqualTo(value));
        }
    }
}
