using DnDGen.CreatureGen.Creatures;
using DnDGen.CreatureGen.Generators.Creatures;
using DnDGen.CreatureGen.Selectors.Collections;
using DnDGen.CreatureGen.Tables;
using DnDGen.Infrastructure.Selectors.Collections;
using DnDGen.RollGen;
using NUnit.Framework;
using System.Collections;
using System.Collections.Generic;

namespace DnDGen.CreatureGen.Tests.Integration.Tables.Creatures
{
    [TestFixture]
    public class AgeRollsTests : TypesAndAmountsTests
    {
        private ICollectionSelector collectionSelector;
        private ITypeAndAmountSelector typesAndAmountsSelector;

        protected override string tableName => TableNameConstants.TypeAndAmount.AgeRolls;

        [SetUp]
        public void Setup()
        {
            collectionSelector = GetNewInstanceOf<ICollectionSelector>();
            typesAndAmountsSelector = GetNewInstanceOf<ITypeAndAmountSelector>();
        }

        [Test]
        public void AgeRollsNames()
        {
            var creatures = CreatureConstants.GetAll();
            AssertCollectionNames(creatures);
        }

        [TestCaseSource(nameof(CreatureAgeRollsData))]
        public void CreatureAgeRolls(string name, Dictionary<string, string> typesAndRolls)
        {
            Assert.That(typesAndRolls, Is.Not.Empty
                .And.Count.AtLeast(2)
                .And.ContainKey(AgeConstants.Categories.Maximum), name);
            AssertTypesAndAmounts(name, typesAndRolls);
        }

        public static IEnumerable CreatureAgeRollsData
        {
            get
            {
                var testCases = new Dictionary<string, Dictionary<string, string>>();
                var creatures = CreatureConstants.GetAll();

                foreach (var creature in creatures)
                {
                    testCases[creature] = new Dictionary<string, string>();
                }

                testCases[CreatureConstants.Aasimar][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(20, 34);
                testCases[CreatureConstants.Aasimar][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(35, 52);
                testCases[CreatureConstants.Aasimar][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(53, 69);
                testCases[CreatureConstants.Aasimar][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(70, 110);
                testCases[CreatureConstants.Aboleth][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(15, 10_000);
                testCases[CreatureConstants.Aboleth][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.Achaierai][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(3, 30);
                testCases[CreatureConstants.Achaierai][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(31, 40);
                testCases[CreatureConstants.Achaierai][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(41, 50);
                testCases[CreatureConstants.Achaierai][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(51, 60);
                testCases[CreatureConstants.Achaierai][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.Allip][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(20, 1000);
                testCases[CreatureConstants.Allip][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.Androsphinx][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(16, 10_000);
                testCases[CreatureConstants.Androsphinx][AgeConstants.Categories.Maximum] = RollHelper.GetRollWithFewestDice(5_000, 10_000);
                testCases[CreatureConstants.Angel_AstralDeva][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(1, 10_000);
                testCases[CreatureConstants.Angel_AstralDeva][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.Angel_Planetar][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(1_000, 10_000);
                testCases[CreatureConstants.Angel_Planetar][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.Angel_Solar][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(5_000, 10_000);
                testCases[CreatureConstants.Angel_Solar][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Anvil_Colossal][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Anvil_Colossal][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Anvil_Gargantuan][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Anvil_Gargantuan][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Anvil_Huge][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Anvil_Huge][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Anvil_Large][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Anvil_Large][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Anvil_Medium][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Anvil_Medium][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Anvil_Small][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Anvil_Small][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Anvil_Tiny][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Anvil_Tiny][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Block_Stone_Colossal][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Block_Stone_Colossal][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Block_Stone_Gargantuan][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Block_Stone_Gargantuan][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Block_Stone_Huge][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Block_Stone_Huge][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Block_Stone_Large][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Block_Stone_Large][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Block_Stone_Medium][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Block_Stone_Medium][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Block_Stone_Small][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Block_Stone_Small][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Block_Stone_Tiny][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Block_Stone_Tiny][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Block_Wood_Colossal][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Block_Wood_Colossal][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Block_Wood_Gargantuan][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Block_Wood_Gargantuan][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Block_Wood_Huge][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Block_Wood_Huge][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Block_Wood_Large][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Block_Wood_Large][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Block_Wood_Medium][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Block_Wood_Medium][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Block_Wood_Small][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Block_Wood_Small][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Block_Wood_Tiny][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Block_Wood_Tiny][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Box_Colossal][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Box_Colossal][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Box_Gargantuan][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Box_Gargantuan][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Box_Huge][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Box_Huge][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Box_Large][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Box_Large][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Box_Medium][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Box_Medium][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Box_Small][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Box_Small][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Box_Tiny][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Box_Tiny][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Carpet_Colossal][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Carpet_Colossal][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Carpet_Gargantuan][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Carpet_Gargantuan][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Carpet_Huge][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Carpet_Huge][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Carpet_Large][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Carpet_Large][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Carpet_Medium][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Carpet_Medium][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Carpet_Small][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Carpet_Small][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Carpet_Tiny][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Carpet_Tiny][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Carriage_Colossal][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Carriage_Colossal][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Carriage_Gargantuan][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Carriage_Gargantuan][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Carriage_Huge][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Carriage_Huge][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Carriage_Large][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Carriage_Large][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Carriage_Medium][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Carriage_Medium][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Carriage_Small][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Carriage_Small][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Carriage_Tiny][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Carriage_Tiny][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Chain_Colossal][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Chain_Colossal][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Chain_Gargantuan][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Chain_Gargantuan][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Chain_Huge][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Chain_Huge][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Chain_Large][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Chain_Large][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Chain_Medium][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Chain_Medium][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Chain_Small][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Chain_Small][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Chain_Tiny][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Chain_Tiny][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Chair_Colossal][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Chair_Colossal][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Chair_Gargantuan][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Chair_Gargantuan][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Chair_Huge][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Chair_Huge][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Chair_Large][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Chair_Large][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Chair_Medium][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Chair_Medium][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Chair_Small][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Chair_Small][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Chair_Tiny][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Chair_Tiny][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Clothes_Colossal][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Clothes_Colossal][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Clothes_Gargantuan][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Clothes_Gargantuan][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Clothes_Huge][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Clothes_Huge][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Clothes_Large][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Clothes_Large][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Clothes_Medium][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Clothes_Medium][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Clothes_Small][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Clothes_Small][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Clothes_Tiny][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Clothes_Tiny][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Ladder_Colossal][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Ladder_Colossal][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Ladder_Gargantuan][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Ladder_Gargantuan][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Ladder_Huge][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Ladder_Huge][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Ladder_Large][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Ladder_Large][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Ladder_Medium][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Ladder_Medium][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Ladder_Small][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Ladder_Small][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Ladder_Tiny][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Ladder_Tiny][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Rope_Colossal][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Rope_Colossal][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Rope_Gargantuan][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Rope_Gargantuan][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Rope_Huge][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Rope_Huge][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Rope_Large][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Rope_Large][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Rope_Medium][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Rope_Medium][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Rope_Small][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Rope_Small][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Rope_Tiny][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Rope_Tiny][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Rug_Colossal][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Rug_Colossal][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Rug_Gargantuan][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Rug_Gargantuan][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Rug_Huge][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Rug_Huge][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Rug_Large][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Rug_Large][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Rug_Medium][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Rug_Medium][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Rug_Small][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Rug_Small][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Rug_Tiny][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Rug_Tiny][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Sled_Colossal][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Sled_Colossal][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Sled_Gargantuan][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Sled_Gargantuan][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Sled_Huge][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Sled_Huge][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Sled_Large][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Sled_Large][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Sled_Medium][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Sled_Medium][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Sled_Small][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Sled_Small][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Sled_Tiny][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Sled_Tiny][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Statue_Animal_Colossal][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Statue_Animal_Colossal][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Statue_Animal_Gargantuan][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Statue_Animal_Gargantuan][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Statue_Animal_Huge][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Statue_Animal_Huge][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Statue_Animal_Large][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Statue_Animal_Large][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Statue_Animal_Medium][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Statue_Animal_Medium][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Statue_Animal_Small][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Statue_Animal_Small][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Statue_Animal_Tiny][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Statue_Animal_Tiny][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Statue_Humanoid_Colossal][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Statue_Humanoid_Colossal][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Statue_Humanoid_Gargantuan][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Statue_Humanoid_Gargantuan][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Statue_Humanoid_Huge][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Statue_Humanoid_Huge][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Statue_Humanoid_Large][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Statue_Humanoid_Large][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Statue_Humanoid_Medium][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Statue_Humanoid_Medium][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Statue_Humanoid_Small][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Statue_Humanoid_Small][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Statue_Humanoid_Tiny][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Statue_Humanoid_Tiny][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Stool_Colossal][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Stool_Colossal][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Stool_Gargantuan][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Stool_Gargantuan][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Stool_Huge][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Stool_Huge][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Stool_Large][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Stool_Large][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Stool_Medium][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Stool_Medium][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Stool_Small][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Stool_Small][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Stool_Tiny][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Stool_Tiny][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Table_Colossal][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Table_Colossal][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Table_Gargantuan][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Table_Gargantuan][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Table_Huge][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Table_Huge][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Table_Large][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Table_Large][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Table_Medium][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Table_Medium][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Table_Small][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Table_Small][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Table_Tiny][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Table_Tiny][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Tapestry_Colossal][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Tapestry_Colossal][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Tapestry_Gargantuan][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Tapestry_Gargantuan][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Tapestry_Huge][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Tapestry_Huge][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Tapestry_Large][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Tapestry_Large][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Tapestry_Medium][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Tapestry_Medium][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Tapestry_Small][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Tapestry_Small][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Tapestry_Tiny][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Tapestry_Tiny][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Wagon_Colossal][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Wagon_Colossal][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Wagon_Gargantuan][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Wagon_Gargantuan][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Wagon_Huge][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Wagon_Huge][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Wagon_Large][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Wagon_Large][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Wagon_Medium][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Wagon_Medium][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Wagon_Small][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Wagon_Small][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.AnimatedObject_Wagon_Tiny][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(0, 1_000);
                testCases[CreatureConstants.AnimatedObject_Wagon_Tiny][AgeConstants.Categories.Maximum] = AgeConstants.Ageless.ToString();
                testCases[CreatureConstants.Ankheg][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(20, 299);
                testCases[CreatureConstants.Ankheg][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(300, 399);
                testCases[CreatureConstants.Ankheg][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(400, 499);
                testCases[CreatureConstants.Ankheg][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(500, 550);
                testCases[CreatureConstants.Ankheg][AgeConstants.Categories.Maximum] = RollHelper.GetRollWithFewestDice(501, 550);
                testCases[CreatureConstants.Criosphinx][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(16, 10_000);
                testCases[CreatureConstants.Criosphinx][AgeConstants.Categories.Maximum] = RollHelper.GetRollWithFewestDice(5_000, 10_000);
                testCases[CreatureConstants.Dwarf_Deep][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(40, 124);
                testCases[CreatureConstants.Dwarf_Deep][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(125, 187);
                testCases[CreatureConstants.Dwarf_Deep][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(188, 249);
                testCases[CreatureConstants.Dwarf_Deep][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(250, 450);
                testCases[CreatureConstants.Dwarf_Deep][AgeConstants.Categories.Maximum] = "250+2d100";
                testCases[CreatureConstants.Dwarf_Duergar][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(40, 124);
                testCases[CreatureConstants.Dwarf_Duergar][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(125, 187);
                testCases[CreatureConstants.Dwarf_Duergar][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(188, 249);
                testCases[CreatureConstants.Dwarf_Duergar][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(250, 450);
                testCases[CreatureConstants.Dwarf_Duergar][AgeConstants.Categories.Maximum] = "250+2d100";
                testCases[CreatureConstants.Dwarf_Hill][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(40, 124);
                testCases[CreatureConstants.Dwarf_Hill][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(125, 187);
                testCases[CreatureConstants.Dwarf_Hill][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(188, 249);
                testCases[CreatureConstants.Dwarf_Hill][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(250, 450);
                testCases[CreatureConstants.Dwarf_Hill][AgeConstants.Categories.Maximum] = "250+2d100";
                testCases[CreatureConstants.Dwarf_Mountain][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(40, 124);
                testCases[CreatureConstants.Dwarf_Mountain][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(125, 187);
                testCases[CreatureConstants.Dwarf_Mountain][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(188, 249);
                testCases[CreatureConstants.Dwarf_Mountain][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(250, 450);
                testCases[CreatureConstants.Dwarf_Mountain][AgeConstants.Categories.Maximum] = "250+2d100";
                testCases[CreatureConstants.Elf_Aquatic][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(110, 174);
                testCases[CreatureConstants.Elf_Aquatic][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(175, 262);
                testCases[CreatureConstants.Elf_Aquatic][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(263, 349);
                testCases[CreatureConstants.Elf_Aquatic][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(350, 750);
                testCases[CreatureConstants.Elf_Aquatic][AgeConstants.Categories.Maximum] = "350+4d100";
                testCases[CreatureConstants.Elf_Drow][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(110, 174);
                testCases[CreatureConstants.Elf_Drow][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(175, 262);
                testCases[CreatureConstants.Elf_Drow][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(263, 349);
                testCases[CreatureConstants.Elf_Drow][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(350, 750);
                testCases[CreatureConstants.Elf_Drow][AgeConstants.Categories.Maximum] = "350+4d100";
                testCases[CreatureConstants.Elf_Gray][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(110, 174);
                testCases[CreatureConstants.Elf_Gray][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(175, 262);
                testCases[CreatureConstants.Elf_Gray][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(263, 349);
                testCases[CreatureConstants.Elf_Gray][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(350, 750);
                testCases[CreatureConstants.Elf_Gray][AgeConstants.Categories.Maximum] = "350+4d100";
                testCases[CreatureConstants.Elf_Half][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(20, 61);
                testCases[CreatureConstants.Elf_Half][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(62, 92);
                testCases[CreatureConstants.Elf_Half][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(93, 124);
                testCases[CreatureConstants.Elf_Half][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(125, 185);
                testCases[CreatureConstants.Elf_Half][AgeConstants.Categories.Maximum] = "125+3d20";
                testCases[CreatureConstants.Elf_High][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(110, 174);
                testCases[CreatureConstants.Elf_High][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(175, 262);
                testCases[CreatureConstants.Elf_High][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(263, 349);
                testCases[CreatureConstants.Elf_High][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(350, 750);
                testCases[CreatureConstants.Elf_High][AgeConstants.Categories.Maximum] = "350+4d100";
                testCases[CreatureConstants.Elf_Wild][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(110, 174);
                testCases[CreatureConstants.Elf_Wild][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(175, 262);
                testCases[CreatureConstants.Elf_Wild][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(263, 349);
                testCases[CreatureConstants.Elf_Wild][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(350, 750);
                testCases[CreatureConstants.Elf_Wild][AgeConstants.Categories.Maximum] = "350+4d100";
                testCases[CreatureConstants.Elf_Wood][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(110, 174);
                testCases[CreatureConstants.Elf_Wood][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(175, 262);
                testCases[CreatureConstants.Elf_Wood][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(263, 349);
                testCases[CreatureConstants.Elf_Wood][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(350, 750);
                testCases[CreatureConstants.Elf_Wood][AgeConstants.Categories.Maximum] = "350+4d100";
                testCases[CreatureConstants.Gnome_Forest][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(40, 99);
                testCases[CreatureConstants.Gnome_Forest][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(100, 149);
                testCases[CreatureConstants.Gnome_Forest][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(150, 199);
                testCases[CreatureConstants.Gnome_Forest][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(200, 500);
                testCases[CreatureConstants.Gnome_Forest][AgeConstants.Categories.Maximum] = "200+3d100";
                testCases[CreatureConstants.Gnome_Rock][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(40, 99);
                testCases[CreatureConstants.Gnome_Rock][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(100, 149);
                testCases[CreatureConstants.Gnome_Rock][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(150, 199);
                testCases[CreatureConstants.Gnome_Rock][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(200, 500);
                testCases[CreatureConstants.Gnome_Rock][AgeConstants.Categories.Maximum] = "200+3d100";
                testCases[CreatureConstants.Gnome_Svirfneblin][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(40, 99);
                testCases[CreatureConstants.Gnome_Svirfneblin][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(100, 149);
                testCases[CreatureConstants.Gnome_Svirfneblin][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(150, 199);
                testCases[CreatureConstants.Gnome_Svirfneblin][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(200, 500);
                testCases[CreatureConstants.Gnome_Svirfneblin][AgeConstants.Categories.Maximum] = "200+3d100";
                testCases[CreatureConstants.Gynosphinx][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(16, 10_000);
                testCases[CreatureConstants.Gynosphinx][AgeConstants.Categories.Maximum] = RollHelper.GetRollWithFewestDice(5_000, 10_000);
                testCases[CreatureConstants.Halfling_Deep][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(20, 49);
                testCases[CreatureConstants.Halfling_Deep][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(50, 74);
                testCases[CreatureConstants.Halfling_Deep][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(75, 99);
                testCases[CreatureConstants.Halfling_Deep][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(100, 200);
                testCases[CreatureConstants.Halfling_Deep][AgeConstants.Categories.Maximum] = "100+5d20";
                testCases[CreatureConstants.Halfling_Lightfoot][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(20, 49);
                testCases[CreatureConstants.Halfling_Lightfoot][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(50, 74);
                testCases[CreatureConstants.Halfling_Lightfoot][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(75, 99);
                testCases[CreatureConstants.Halfling_Lightfoot][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(100, 200);
                testCases[CreatureConstants.Halfling_Lightfoot][AgeConstants.Categories.Maximum] = "100+5d20";
                testCases[CreatureConstants.Halfling_Tallfellow][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(20, 49);
                testCases[CreatureConstants.Halfling_Tallfellow][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(50, 74);
                testCases[CreatureConstants.Halfling_Tallfellow][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(75, 99);
                testCases[CreatureConstants.Halfling_Tallfellow][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(100, 200);
                testCases[CreatureConstants.Halfling_Tallfellow][AgeConstants.Categories.Maximum] = "100+5d20";
                testCases[CreatureConstants.Hieracosphinx][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(16, 10_000);
                testCases[CreatureConstants.Hieracosphinx][AgeConstants.Categories.Maximum] = RollHelper.GetRollWithFewestDice(5_000, 10_000);
                testCases[CreatureConstants.Human][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(15, 34);
                testCases[CreatureConstants.Human][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(35, 52);
                testCases[CreatureConstants.Human][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(53, 69);
                testCases[CreatureConstants.Human][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(70, 110);
                testCases[CreatureConstants.Human][AgeConstants.Categories.Maximum] = "70+2d20";
                testCases[CreatureConstants.Orc_Half][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(14, 29);
                testCases[CreatureConstants.Orc_Half][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(30, 44);
                testCases[CreatureConstants.Orc_Half][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(45, 59);
                testCases[CreatureConstants.Orc_Half][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(60, 80);
                testCases[CreatureConstants.Orc_Half][AgeConstants.Categories.Maximum] = "60+2d10";
                testCases[CreatureConstants.Tiefling][AgeConstants.Categories.Adulthood] = RollHelper.GetRollWithFewestDice(20, 34);
                testCases[CreatureConstants.Tiefling][AgeConstants.Categories.MiddleAge] = RollHelper.GetRollWithFewestDice(35, 52);
                testCases[CreatureConstants.Tiefling][AgeConstants.Categories.Old] = RollHelper.GetRollWithFewestDice(53, 69);
                testCases[CreatureConstants.Tiefling][AgeConstants.Categories.Venerable] = RollHelper.GetRollWithFewestDice(70, 110);
                testCases[CreatureConstants.Tiefling][AgeConstants.Categories.Maximum] = "70+2d20";

                foreach (var testCase in testCases)
                {
                    yield return new TestCaseData(testCase.Key, testCase.Value);
                }
            }
        }
    }
}