using DnDGen.CreatureGen.Creatures;
using DnDGen.CreatureGen.Tables;
using NUnit.Framework;

namespace DnDGen.CreatureGen.Tests.Integration.Tables.Creatures
{
    [TestFixture]
    public class MaxAgeDescriptionsTests : CollectionTests
    {
        protected override string tableName => TableNameConstants.Collection.MaxAgeDescriptions;

        private const string NaturalCauses = "Will die of natural causes";
        private const string LiveIndefinitely = "Will live indefinitely";
        private const string Unknown = "No known limit to lifespan";
        private const string Swarm = "Swarm will disperse";
        private const string Undead = CreatureConstants.Types.Undead;
        private const string Outsider = CreatureConstants.Types.Outsider;
        private const string Construct = CreatureConstants.Types.Construct;

        [Test]
        public void MaxAgeDescriptionsNames()
        {
            var creatures = CreatureConstants.GetAll();
            AssertCollectionNames(creatures);
        }

        [TestCase(CreatureConstants.Aasimar, NaturalCauses)]
        [TestCase(CreatureConstants.Aboleth, LiveIndefinitely)]
        [TestCase(CreatureConstants.Achaierai, NaturalCauses)]
        [TestCase(CreatureConstants.Allip, Undead)]
        [TestCase(CreatureConstants.Androsphinx, LiveIndefinitely)]
        [TestCase(CreatureConstants.Angel_AstralDeva, Outsider)]
        [TestCase(CreatureConstants.Angel_Planetar, Outsider)]
        [TestCase(CreatureConstants.Angel_Solar, Outsider)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal_Flexible, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal_MultipleLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal_MultipleLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal_Sheetlike, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal_TwoLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal_TwoLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal_Wheels_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan_Flexible, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan_MultipleLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan_MultipleLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan_Sheetlike, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan_TwoLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan_TwoLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan_Wheels_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge_Flexible, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge_MultipleLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge_MultipleLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge_Sheetlike, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge_TwoLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge_TwoLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge_Wheels_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large_Flexible, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large_MultipleLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large_MultipleLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large_Sheetlike, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large_TwoLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large_TwoLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large_Wheels_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Medium, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Medium_Flexible, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Medium_MultipleLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Medium_MultipleLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Medium_Sheetlike, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Medium_TwoLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Medium_TwoLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Medium_Wheels_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Medium_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Small, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Small_Flexible, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Small_MultipleLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Small_MultipleLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Small_Sheetlike, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Small_TwoLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Small_TwoLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Small_Wheels_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Small_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny_Flexible, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny_MultipleLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny_MultipleLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny_Sheetlike, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny_TwoLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny_TwoLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny_Wheels_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny_Wooden, Construct)]
        [TestCase(CreatureConstants.Ankheg, NaturalCauses)]
        [TestCase(CreatureConstants.Annis, Unknown)]
        [TestCase(CreatureConstants.Ant_Giant_Queen, NaturalCauses)]
        [TestCase(CreatureConstants.Ant_Giant_Soldier, NaturalCauses)]
        [TestCase(CreatureConstants.Ant_Giant_Worker, NaturalCauses)]
        [TestCase(CreatureConstants.Ape, NaturalCauses)]
        [TestCase(CreatureConstants.Ape_Dire, NaturalCauses)]
        [TestCase(CreatureConstants.Aranea, NaturalCauses)]
        [TestCase(CreatureConstants.Arrowhawk_Adult, "Become Elder")]
        [TestCase(CreatureConstants.Arrowhawk_Elder, NaturalCauses)]
        [TestCase(CreatureConstants.Arrowhawk_Juvenile, "Become Adult")]
        [TestCase(CreatureConstants.AssassinVine, NaturalCauses)]
        [TestCase(CreatureConstants.Athach, NaturalCauses)]
        [TestCase(CreatureConstants.Avoral, NaturalCauses)]
        [TestCase(CreatureConstants.Azer, NaturalCauses)]
        [TestCase(CreatureConstants.Babau, Outsider)]
        [TestCase(CreatureConstants.Baboon, NaturalCauses)]
        [TestCase(CreatureConstants.Badger, NaturalCauses)]
        [TestCase(CreatureConstants.Badger_Dire, NaturalCauses)]
        [TestCase(CreatureConstants.Balor, Outsider)]
        [TestCase(CreatureConstants.BarbedDevil_Hamatula, Outsider)]
        [TestCase(CreatureConstants.Barghest, Unknown)]
        [TestCase(CreatureConstants.Barghest_Greater, Unknown)]
        [TestCase(CreatureConstants.Basilisk, NaturalCauses)]
        [TestCase(CreatureConstants.Basilisk_Greater, NaturalCauses)]
        [TestCase(CreatureConstants.Bat, NaturalCauses)]
        [TestCase(CreatureConstants.Bat_Dire, NaturalCauses)]
        [TestCase(CreatureConstants.Bat_Swarm, Swarm)]
        [TestCase(CreatureConstants.Bear_Black, NaturalCauses)]
        [TestCase(CreatureConstants.Bear_Brown, NaturalCauses)]
        [TestCase(CreatureConstants.Bear_Dire, NaturalCauses)]
        [TestCase(CreatureConstants.Bear_Polar, NaturalCauses)]
        [TestCase(CreatureConstants.BeardedDevil_Barbazu, Outsider)]
        [TestCase(CreatureConstants.Bebilith, Outsider)]
        [TestCase(CreatureConstants.Bee_Giant, NaturalCauses)]
        [TestCase(CreatureConstants.Behir, NaturalCauses)]
        [TestCase(CreatureConstants.Beholder, NaturalCauses)]
        [TestCase(CreatureConstants.Beholder_Gauth, NaturalCauses)]
        [TestCase(CreatureConstants.Belker, Outsider)]
        [TestCase(CreatureConstants.Bison, NaturalCauses)]
        [TestCase(CreatureConstants.BlackPudding, "Become Elder")]
        [TestCase(CreatureConstants.BlackPudding_Elder, Unknown)]
        [TestCase(CreatureConstants.BlinkDog, NaturalCauses)]
        [TestCase(CreatureConstants.Boar, NaturalCauses)]
        [TestCase(CreatureConstants.Boar_Dire, NaturalCauses)]
        [TestCase(CreatureConstants.Bodak, Undead)]
        [TestCase(CreatureConstants.BombardierBeetle_Giant, NaturalCauses)]
        [TestCase(CreatureConstants.BoneDevil_Osyluth, Outsider)]
        [TestCase(CreatureConstants.Bralani, NaturalCauses)]
        [TestCase(CreatureConstants.Bugbear, NaturalCauses)]
        [TestCase(CreatureConstants.Bulette, NaturalCauses)]
        [TestCase(CreatureConstants.Camel_Bactrian, NaturalCauses)]
        [TestCase(CreatureConstants.Camel_Dromedary, NaturalCauses)]
        [TestCase(CreatureConstants.CarrionCrawler, NaturalCauses)]
        [TestCase(CreatureConstants.Cat, NaturalCauses)]
        [TestCase(CreatureConstants.Centaur, NaturalCauses)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Colossal, NaturalCauses)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Gargantuan, NaturalCauses)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Huge, NaturalCauses)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Large, NaturalCauses)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Medium, NaturalCauses)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Small, NaturalCauses)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Tiny, NaturalCauses)]
        [TestCase(CreatureConstants.Centipede_Swarm, Swarm)]
        [TestCase(CreatureConstants.ChainDevil_Kyton, Outsider)]
        [TestCase(CreatureConstants.ChaosBeast, Unknown)]
        [TestCase(CreatureConstants.Cheetah, NaturalCauses)]
        [TestCase(CreatureConstants.Chimera_Black, NaturalCauses)]
        [TestCase(CreatureConstants.Chimera_Blue, NaturalCauses)]
        [TestCase(CreatureConstants.Chimera_Green, NaturalCauses)]
        [TestCase(CreatureConstants.Chimera_Red, NaturalCauses)]
        [TestCase(CreatureConstants.Chimera_White, NaturalCauses)]
        [TestCase(CreatureConstants.Choker, NaturalCauses)]
        [TestCase(CreatureConstants.Chuul, NaturalCauses)]
        [TestCase(CreatureConstants.Cloaker, NaturalCauses)]
        [TestCase(CreatureConstants.Cockatrice, NaturalCauses)]
        [TestCase(CreatureConstants.Couatl, Outsider)]
        [TestCase(CreatureConstants.Criosphinx, LiveIndefinitely)]
        [TestCase(CreatureConstants.Crocodile, NaturalCauses)]
        [TestCase(CreatureConstants.Crocodile_Giant, NaturalCauses)]
        [TestCase(CreatureConstants.Cryohydra_10Heads, Unknown)]
        [TestCase(CreatureConstants.Cryohydra_11Heads, Unknown)]
        [TestCase(CreatureConstants.Cryohydra_12Heads, Unknown)]
        [TestCase(CreatureConstants.Cryohydra_5Heads, Unknown)]
        [TestCase(CreatureConstants.Cryohydra_6Heads, Unknown)]
        [TestCase(CreatureConstants.Cryohydra_7Heads, Unknown)]
        [TestCase(CreatureConstants.Cryohydra_8Heads, Unknown)]
        [TestCase(CreatureConstants.Cryohydra_9Heads, Unknown)]
        [TestCase(CreatureConstants.Darkmantle, NaturalCauses)]
        [TestCase(CreatureConstants.Deinonychus, NaturalCauses)]
        [TestCase(CreatureConstants.Delver, NaturalCauses)]
        [TestCase(CreatureConstants.Derro, NaturalCauses)]
        [TestCase(CreatureConstants.Derro_Sane, NaturalCauses)]
        [TestCase(CreatureConstants.Destrachan, NaturalCauses)]
        [TestCase(CreatureConstants.Devourer, Undead)]
        [TestCase(CreatureConstants.Digester, NaturalCauses)]
        [TestCase(CreatureConstants.DisplacerBeast, NaturalCauses)]
        [TestCase(CreatureConstants.DisplacerBeast_PackLord, NaturalCauses)]
        [TestCase(CreatureConstants.Djinni, Outsider)]
        [TestCase(CreatureConstants.Djinni_Noble, Outsider)]
        [TestCase(CreatureConstants.Dog, NaturalCauses)]
        [TestCase(CreatureConstants.Dog_Riding, NaturalCauses)]
        [TestCase(CreatureConstants.Donkey, NaturalCauses)]
        [TestCase(CreatureConstants.Doppelganger, NaturalCauses)]
        [TestCase(CreatureConstants.Dragon_Black_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_Black_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_Black_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_Black_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_Black_MatureAdult, "Become Old")]
        [TestCase(CreatureConstants.Dragon_Black_Old, "Become Very Old")]
        [TestCase(CreatureConstants.Dragon_Black_VeryOld, "Become Ancient")]
        [TestCase(CreatureConstants.Dragon_Black_VeryYoung, "Become Young")]
        [TestCase(CreatureConstants.Dragon_Black_Wyrm, "Become Great Wyrm")]
        [TestCase(CreatureConstants.Dragon_Black_Wyrmling, "Become Very Young")]
        [TestCase(CreatureConstants.Dragon_Black_Young, "Become Juvenile")]
        [TestCase(CreatureConstants.Dragon_Black_YoungAdult, "Become Adult")]
        [TestCase(CreatureConstants.Dragon_Blue_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_Blue_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_Blue_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_Blue_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_Blue_MatureAdult, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Blue_Old, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Blue_VeryOld, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Blue_VeryYoung, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Blue_Wyrm, "Clumsy Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Blue_Wyrmling, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Blue_Young, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Blue_YoungAdult, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Brass_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_Brass_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_Brass_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_Brass_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_Brass_MatureAdult, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Brass_Old, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Brass_VeryOld, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Brass_VeryYoung, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Brass_Wyrm, "Clumsy Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Brass_Wyrmling, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Brass_Young, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Brass_YoungAdult, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Bronze_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_Bronze_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_Bronze_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_Bronze_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_Bronze_MatureAdult, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Bronze_Old, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Bronze_VeryOld, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Bronze_VeryYoung, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Bronze_Wyrm, "Clumsy Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Bronze_Wyrmling, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Bronze_Young, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Bronze_YoungAdult, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Copper_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_Copper_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_Copper_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_Copper_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_Copper_MatureAdult, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Copper_Old, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Copper_VeryOld, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Copper_VeryYoung, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Copper_Wyrm, "Clumsy Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Copper_Wyrmling, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Copper_Young, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Copper_YoungAdult, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Gold_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_Gold_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_Gold_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_Gold_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_Gold_MatureAdult, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Gold_Old, "Clumsy Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Gold_VeryOld, "Clumsy Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Gold_VeryYoung, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Gold_Wyrm, "Clumsy Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Gold_Wyrmling, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Gold_Young, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Gold_YoungAdult, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Green_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_Green_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_Green_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_Green_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_Green_MatureAdult, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Green_Old, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Green_VeryOld, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Green_VeryYoung, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Green_Wyrm, "Clumsy Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Green_Wyrmling, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Green_Young, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Green_YoungAdult, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Red_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_Red_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_Red_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_Red_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_Red_MatureAdult, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Red_Old, "Clumsy Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Red_VeryOld, "Clumsy Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Red_VeryYoung, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Red_Wyrm, "Clumsy Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Red_Wyrmling, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Red_Young, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Red_YoungAdult, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Silver_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_Silver_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_Silver_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_Silver_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_Silver_MatureAdult, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Silver_Old, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Silver_VeryOld, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Silver_VeryYoung, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Silver_Wyrm, "Clumsy Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Silver_Wyrmling, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Silver_Young, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_Silver_YoungAdult, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_White_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_White_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_White_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_White_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_White_MatureAdult, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_White_Old, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_White_VeryOld, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_White_VeryYoung, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_White_Wyrm, "Clumsy Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_White_Wyrmling, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_White_Young, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dragon_White_YoungAdult, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.DragonTurtle)]
        [TestCase(CreatureConstants.Dragonne, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Dretch)]
        [TestCase(CreatureConstants.Drider)]
        [TestCase(CreatureConstants.Dryad)]
        [TestCase(CreatureConstants.Dwarf_Deep)]
        [TestCase(CreatureConstants.Dwarf_Duergar)]
        [TestCase(CreatureConstants.Dwarf_Hill)]
        [TestCase(CreatureConstants.Dwarf_Mountain)]
        [TestCase(CreatureConstants.Eagle, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Eagle_Giant, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Efreeti, "Perfect Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Elasmosaurus)]
        [TestCase(CreatureConstants.Elemental_Air_Elder, "Perfect Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Elemental_Air_Greater, "Perfect Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Elemental_Air_Huge, "Perfect Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Elemental_Air_Large, "Perfect Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Elemental_Air_Medium, "Perfect Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Elemental_Air_Small, "Perfect Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Elemental_Earth_Elder)]
        [TestCase(CreatureConstants.Elemental_Earth_Greater)]
        [TestCase(CreatureConstants.Elemental_Earth_Huge)]
        [TestCase(CreatureConstants.Elemental_Earth_Large)]
        [TestCase(CreatureConstants.Elemental_Earth_Medium)]
        [TestCase(CreatureConstants.Elemental_Earth_Small)]
        [TestCase(CreatureConstants.Elemental_Fire_Elder)]
        [TestCase(CreatureConstants.Elemental_Fire_Greater)]
        [TestCase(CreatureConstants.Elemental_Fire_Huge)]
        [TestCase(CreatureConstants.Elemental_Fire_Large)]
        [TestCase(CreatureConstants.Elemental_Fire_Medium)]
        [TestCase(CreatureConstants.Elemental_Fire_Small)]
        [TestCase(CreatureConstants.Elemental_Water_Elder)]
        [TestCase(CreatureConstants.Elemental_Water_Greater)]
        [TestCase(CreatureConstants.Elemental_Water_Huge)]
        [TestCase(CreatureConstants.Elemental_Water_Large)]
        [TestCase(CreatureConstants.Elemental_Water_Medium)]
        [TestCase(CreatureConstants.Elemental_Water_Small)]
        [TestCase(CreatureConstants.Elephant)]
        [TestCase(CreatureConstants.Elf_Aquatic)]
        [TestCase(CreatureConstants.Elf_Drow)]
        [TestCase(CreatureConstants.Elf_Gray)]
        [TestCase(CreatureConstants.Elf_Half)]
        [TestCase(CreatureConstants.Elf_High)]
        [TestCase(CreatureConstants.Elf_Wild)]
        [TestCase(CreatureConstants.Elf_Wood)]
        [TestCase(CreatureConstants.Erinyes, "Good Maneuverability (Wings)")]
        [TestCase(CreatureConstants.EtherealFilcher)]
        [TestCase(CreatureConstants.EtherealMarauder)]
        [TestCase(CreatureConstants.Ettercap)]
        [TestCase(CreatureConstants.Ettin)]
        [TestCase(CreatureConstants.FireBeetle_Giant)]
        [TestCase(CreatureConstants.FormianMyrmarch)]
        [TestCase(CreatureConstants.FormianQueen)]
        [TestCase(CreatureConstants.FormianTaskmaster)]
        [TestCase(CreatureConstants.FormianWarrior)]
        [TestCase(CreatureConstants.FormianWorker)]
        [TestCase(CreatureConstants.FrostWorm)]
        [TestCase(CreatureConstants.Gargoyle, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Gargoyle_Kapoacinth)]
        [TestCase(CreatureConstants.GelatinousCube)]
        [TestCase(CreatureConstants.Ghaele, "Perfect Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Ghoul)]
        [TestCase(CreatureConstants.Ghoul_Ghast)]
        [TestCase(CreatureConstants.Ghoul_Lacedon)]
        [TestCase(CreatureConstants.Giant_Cloud)]
        [TestCase(CreatureConstants.Giant_Fire)]
        [TestCase(CreatureConstants.Giant_Frost)]
        [TestCase(CreatureConstants.Giant_Hill)]
        [TestCase(CreatureConstants.Giant_Stone)]
        [TestCase(CreatureConstants.Giant_Stone_Elder)]
        [TestCase(CreatureConstants.Giant_Storm)]
        [TestCase(CreatureConstants.GibberingMouther)]
        [TestCase(CreatureConstants.Girallon)]
        [TestCase(CreatureConstants.Githyanki)]
        [TestCase(CreatureConstants.Githzerai)]
        [TestCase(CreatureConstants.Glabrezu)]
        [TestCase(CreatureConstants.Gnoll)]
        [TestCase(CreatureConstants.Gnome_Forest)]
        [TestCase(CreatureConstants.Gnome_Rock)]
        [TestCase(CreatureConstants.Gnome_Svirfneblin)]
        [TestCase(CreatureConstants.Goblin)]
        [TestCase(CreatureConstants.Golem_Clay)]
        [TestCase(CreatureConstants.Golem_Flesh)]
        [TestCase(CreatureConstants.Golem_Iron)]
        [TestCase(CreatureConstants.Golem_Stone)]
        [TestCase(CreatureConstants.Golem_Stone_Greater)]
        [TestCase(CreatureConstants.Gorgon)]
        [TestCase(CreatureConstants.GrayOoze)]
        [TestCase(CreatureConstants.GrayRender)]
        [TestCase(CreatureConstants.GreenHag)]
        [TestCase(CreatureConstants.Grick)]
        [TestCase(CreatureConstants.Griffon, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Grig, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Grig_WithFiddle, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Grimlock)]
        [TestCase(CreatureConstants.Gynosphinx, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Halfling_Deep)]
        [TestCase(CreatureConstants.Halfling_Lightfoot)]
        [TestCase(CreatureConstants.Halfling_Tallfellow)]
        [TestCase(CreatureConstants.Harpy, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Hawk, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.HellHound)]
        [TestCase(CreatureConstants.HellHound_NessianWarhound)]
        [TestCase(CreatureConstants.Hellcat_Bezekira)]
        [TestCase(CreatureConstants.Hellwasp_Swarm, Swarm)]
        [TestCase(CreatureConstants.Hezrou)]
        [TestCase(CreatureConstants.Hieracosphinx, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Hippogriff, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Hobgoblin)]
        [TestCase(CreatureConstants.Homunculus, "Good Maneuverability (Wings)")]
        [TestCase(CreatureConstants.HornedDevil_Cornugon, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Horse_Heavy)]
        [TestCase(CreatureConstants.Horse_Heavy_War)]
        [TestCase(CreatureConstants.Horse_Light)]
        [TestCase(CreatureConstants.Horse_Light_War)]
        [TestCase(CreatureConstants.HoundArchon)]
        [TestCase(CreatureConstants.Howler)]
        [TestCase(CreatureConstants.Human)]
        [TestCase(CreatureConstants.Hydra_10Heads)]
        [TestCase(CreatureConstants.Hydra_11Heads)]
        [TestCase(CreatureConstants.Hydra_12Heads)]
        [TestCase(CreatureConstants.Hydra_5Heads)]
        [TestCase(CreatureConstants.Hydra_6Heads)]
        [TestCase(CreatureConstants.Hydra_7Heads)]
        [TestCase(CreatureConstants.Hydra_8Heads)]
        [TestCase(CreatureConstants.Hydra_9Heads)]
        [TestCase(CreatureConstants.Hyena)]
        [TestCase(CreatureConstants.IceDevil_Gelugon)]
        [TestCase(CreatureConstants.Imp, "Perfect Maneuverability (Wings)")]
        [TestCase(CreatureConstants.InvisibleStalker, "Perfect Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Janni, "Perfect Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Kobold)]
        [TestCase(CreatureConstants.Kolyarut)]
        [TestCase(CreatureConstants.Kraken)]
        [TestCase(CreatureConstants.Krenshar)]
        [TestCase(CreatureConstants.KuoToa)]
        [TestCase(CreatureConstants.Lamia)]
        [TestCase(CreatureConstants.Lammasu, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.LanternArchon, "Perfect Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Lemure)]
        [TestCase(CreatureConstants.Leonal)]
        [TestCase(CreatureConstants.Leopard)]
        [TestCase(CreatureConstants.Lillend, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Lion)]
        [TestCase(CreatureConstants.Lion_Dire)]
        [TestCase(CreatureConstants.Lizard)]
        [TestCase(CreatureConstants.Lizardfolk)]
        [TestCase(CreatureConstants.Lizard_Monitor)]
        [TestCase(CreatureConstants.Locathah)]
        [TestCase(CreatureConstants.Locust_Swarm, Swarm)]
        [TestCase(CreatureConstants.Magmin)]
        [TestCase(CreatureConstants.MantaRay)]
        [TestCase(CreatureConstants.Manticore, "Clumsy Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Marilith)]
        [TestCase(CreatureConstants.Marut)]
        [TestCase(CreatureConstants.Medusa)]
        [TestCase(CreatureConstants.Megaraptor)]
        [TestCase(CreatureConstants.Merfolk)]
        [TestCase(CreatureConstants.Mephit_Air, "Perfect Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Mephit_Dust, "Perfect Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Mephit_Earth, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Mephit_Fire, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Mephit_Ice, "Perfect Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Mephit_Magma, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Mephit_Ooze, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Mephit_Salt, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Mephit_Steam, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Mephit_Water, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Mimic)]
        [TestCase(CreatureConstants.MindFlayer)]
        [TestCase(CreatureConstants.Minotaur)]
        [TestCase(CreatureConstants.Mohrg)]
        [TestCase(CreatureConstants.Monkey)]
        [TestCase(CreatureConstants.Mule)]
        [TestCase(CreatureConstants.Mummy)]
        [TestCase(CreatureConstants.Naga_Dark)]
        [TestCase(CreatureConstants.Naga_Guardian)]
        [TestCase(CreatureConstants.Naga_Spirit)]
        [TestCase(CreatureConstants.Naga_Water)]
        [TestCase(CreatureConstants.Nalfeshnee, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.NightHag)]
        [TestCase(CreatureConstants.Nightcrawler)]
        [TestCase(CreatureConstants.Nightmare, "Good Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Nightmare_Cauchemar, "Good Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Nightwalker, "Poor Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Nightwing, "Good Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Nixie)]
        [TestCase(CreatureConstants.Nymph)]
        [TestCase(CreatureConstants.OchreJelly)]
        [TestCase(CreatureConstants.Octopus)]
        [TestCase(CreatureConstants.Octopus_Giant)]
        [TestCase(CreatureConstants.Ogre)]
        [TestCase(CreatureConstants.Ogre_Merrow)]
        [TestCase(CreatureConstants.OgreMage, "Good Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Orc)]
        [TestCase(CreatureConstants.Orc_Half)]
        [TestCase(CreatureConstants.Otyugh)]
        [TestCase(CreatureConstants.Owl, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Owl_Giant, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Owlbear)]
        [TestCase(CreatureConstants.Pegasus, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.PhantomFungus)]
        [TestCase(CreatureConstants.PhaseSpider)]
        [TestCase(CreatureConstants.Phasm)]
        [TestCase(CreatureConstants.PitFiend, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Pixie, "Good Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Pixie_WithIrresistibleDance, "Good Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Pony)]
        [TestCase(CreatureConstants.Pony_War)]
        [TestCase(CreatureConstants.Porpoise)]
        [TestCase(CreatureConstants.PrayingMantis_Giant, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Pseudodragon, "Good Maneuverability (Wings)")]
        [TestCase(CreatureConstants.PurpleWorm)]
        [TestCase(CreatureConstants.Pyrohydra_10Heads)]
        [TestCase(CreatureConstants.Pyrohydra_11Heads)]
        [TestCase(CreatureConstants.Pyrohydra_12Heads)]
        [TestCase(CreatureConstants.Pyrohydra_5Heads)]
        [TestCase(CreatureConstants.Pyrohydra_6Heads)]
        [TestCase(CreatureConstants.Pyrohydra_7Heads)]
        [TestCase(CreatureConstants.Pyrohydra_8Heads)]
        [TestCase(CreatureConstants.Pyrohydra_9Heads)]
        [TestCase(CreatureConstants.Quasit, "Perfect Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Rakshasa)]
        [TestCase(CreatureConstants.Rast, "Good Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Rat)]
        [TestCase(CreatureConstants.Rat_Dire)]
        [TestCase(CreatureConstants.Rat_Swarm, Swarm)]
        [TestCase(CreatureConstants.Raven, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Ravid, "Perfect Maneuverability (Magic)")]
        [TestCase(CreatureConstants.RazorBoar)]
        [TestCase(CreatureConstants.Remorhaz)]
        [TestCase(CreatureConstants.Retriever)]
        [TestCase(CreatureConstants.Rhinoceras)]
        [TestCase(CreatureConstants.Roc, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Roper)]
        [TestCase(CreatureConstants.RustMonster)]
        [TestCase(CreatureConstants.Sahuagin)]
        [TestCase(CreatureConstants.Sahuagin_Malenti)]
        [TestCase(CreatureConstants.Sahuagin_Mutant)]
        [TestCase(CreatureConstants.Salamander_Average)]
        [TestCase(CreatureConstants.Salamander_Flamebrother)]
        [TestCase(CreatureConstants.Salamander_Noble)]
        [TestCase(CreatureConstants.Satyr)]
        [TestCase(CreatureConstants.Satyr_WithPipes)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Colossal)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Gargantuan)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Huge)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Large)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Medium)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Small)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Tiny)]
        [TestCase(CreatureConstants.Scorpionfolk)]
        [TestCase(CreatureConstants.SeaCat)]
        [TestCase(CreatureConstants.SeaHag)]
        [TestCase(CreatureConstants.Shadow, "Good Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Shadow_Greater, "Good Maneuverability (Magic)")]
        [TestCase(CreatureConstants.ShadowMastiff)]
        [TestCase(CreatureConstants.ShamblingMound)]
        [TestCase(CreatureConstants.Shark_Dire)]
        [TestCase(CreatureConstants.Shark_Huge)]
        [TestCase(CreatureConstants.Shark_Large)]
        [TestCase(CreatureConstants.Shark_Medium)]
        [TestCase(CreatureConstants.ShieldGuardian)]
        [TestCase(CreatureConstants.ShockerLizard)]
        [TestCase(CreatureConstants.Shrieker)]
        [TestCase(CreatureConstants.Skum)]
        [TestCase(CreatureConstants.Slaad_Blue)]
        [TestCase(CreatureConstants.Slaad_Death)]
        [TestCase(CreatureConstants.Slaad_Gray)]
        [TestCase(CreatureConstants.Slaad_Green)]
        [TestCase(CreatureConstants.Slaad_Red)]
        [TestCase(CreatureConstants.Snake_Constrictor)]
        [TestCase(CreatureConstants.Snake_Constrictor_Giant)]
        [TestCase(CreatureConstants.Snake_Viper_Huge)]
        [TestCase(CreatureConstants.Snake_Viper_Large)]
        [TestCase(CreatureConstants.Snake_Viper_Medium)]
        [TestCase(CreatureConstants.Snake_Viper_Small)]
        [TestCase(CreatureConstants.Snake_Viper_Tiny)]
        [TestCase(CreatureConstants.Spectre, "Perfect Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Colossal)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Gargantuan)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Huge)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Large)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Medium)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Small)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Tiny)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Colossal)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Gargantuan)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Huge)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Large)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Medium)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Small)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Tiny)]
        [TestCase(CreatureConstants.Spider_Swarm, Swarm)]
        [TestCase(CreatureConstants.SpiderEater, "Good Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Squid)]
        [TestCase(CreatureConstants.Squid_Giant)]
        [TestCase(CreatureConstants.StagBeetle_Giant)]
        [TestCase(CreatureConstants.Stirge, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Succubus, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Tarrasque)]
        [TestCase(CreatureConstants.Tendriculos)]
        [TestCase(CreatureConstants.Thoqqua)]
        [TestCase(CreatureConstants.Tiefling)]
        [TestCase(CreatureConstants.Tiger)]
        [TestCase(CreatureConstants.Tiger_Dire)]
        [TestCase(CreatureConstants.Titan)]
        [TestCase(CreatureConstants.Toad)]
        [TestCase(CreatureConstants.Tojanida_Adult)]
        [TestCase(CreatureConstants.Tojanida_Elder)]
        [TestCase(CreatureConstants.Tojanida_Juvenile)]
        [TestCase(CreatureConstants.Treant)]
        [TestCase(CreatureConstants.Triceratops)]
        [TestCase(CreatureConstants.Triton)]
        [TestCase(CreatureConstants.Troglodyte)]
        [TestCase(CreatureConstants.Troll)]
        [TestCase(CreatureConstants.Troll_Scrag)]
        [TestCase(CreatureConstants.TrumpetArchon, "Good Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Tyrannosaurus)]
        [TestCase(CreatureConstants.UmberHulk)]
        [TestCase(CreatureConstants.UmberHulk_TrulyHorrid)]
        [TestCase(CreatureConstants.Unicorn)]
        [TestCase(CreatureConstants.VampireSpawn)]
        [TestCase(CreatureConstants.Vargouille, "Good Maneuverability (Wings)")]
        [TestCase(CreatureConstants.VioletFungus)]
        [TestCase(CreatureConstants.Vrock, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Wasp_Giant, "Good Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Weasel)]
        [TestCase(CreatureConstants.Weasel_Dire)]
        [TestCase(CreatureConstants.Whale_Baleen)]
        [TestCase(CreatureConstants.Whale_Cachalot)]
        [TestCase(CreatureConstants.Whale_Orca)]
        [TestCase(CreatureConstants.Wight)]
        [TestCase(CreatureConstants.WillOWisp, "Perfect Maneuverability (Magic)")]
        [TestCase(CreatureConstants.WinterWolf)]
        [TestCase(CreatureConstants.Wolf)]
        [TestCase(CreatureConstants.Wolf_Dire)]
        [TestCase(CreatureConstants.Wolverine)]
        [TestCase(CreatureConstants.Wolverine_Dire)]
        [TestCase(CreatureConstants.Worg)]
        [TestCase(CreatureConstants.Wraith, "Good Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Wraith_Dread, "Good Maneuverability (Magic)")]
        [TestCase(CreatureConstants.Wyvern, "Poor Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Xill)]
        [TestCase(CreatureConstants.Xorn_Average)]
        [TestCase(CreatureConstants.Xorn_Elder)]
        [TestCase(CreatureConstants.Xorn_Minor)]
        [TestCase(CreatureConstants.YethHound, "Good Maneuverability (Wings)")]
        [TestCase(CreatureConstants.Yrthak, "Average Maneuverability (Wings)")]
        [TestCase(CreatureConstants.YuanTi_Abomination)]
        [TestCase(CreatureConstants.YuanTi_Halfblood_SnakeArms)]
        [TestCase(CreatureConstants.YuanTi_Halfblood_SnakeHead)]
        [TestCase(CreatureConstants.YuanTi_Halfblood_SnakeTail)]
        [TestCase(CreatureConstants.YuanTi_Halfblood_SnakeTailAndHumanLegs)]
        [TestCase(CreatureConstants.YuanTi_Pureblood)]
        [TestCase(CreatureConstants.Zelekhut, "Average Maneuverability (Wings)")]
        public void MaxAgeDescription(string creature, string maxAgeDescription)
        {
            Assert.Fail("Still making correct data. Working on Dragons");

            Assert.That(maxAgeDescription, Is.Not.Empty, creature);
            AssertDistinctCollection(creature, new[] { maxAgeDescription });
        }
    }
}
